### ISSUE TITLE
Linux 11.0.11+9 tar installs version 11.0.10

### ISSUE THREAD

**Issue by flyingcircle** [AdoptOpenJDK/openjdk-website#1005]
I installed the most recent release version from this webpage: https://adoptopenjdk.net/upstream.html using the linux x64 distribution which says it is version 11.0.11+9.

However after the install when I run `java -version` it says that my current version is:
```
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
```

I have reverified through multiple downloads and uploads from different locations, but it simply looks the release is pointing to the wrong package or needs to be rebuilt correctly.

**Comment by jerboaa** [comment]
This cannot be right. Binaries from  https://adoptopenjdk.net/upstream.html identify as *OpenJDK*. Yours is an Oracle JDK build (note the `Java(TM)` bit):

```
$ ./openjdk-11.0.11_9/bin/java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode)
```

**Comment by flyingcircle** [comment]
You're right. Dumb mistake on my part.
