### ISSUE TITLE
Poor French translations

### ISSUE THREAD

**Issue by Arkanosis** [AdoptOpenJDK/openjdk-website#1011]
Hello,

The French translations of the website are extremely poor. As a French speaker, there are some parts I only understand because I also know English and can translate back to it.

The best example is probably the fact that “Hotspot” (the VM) is being translated as “Point chaud”!

![image](https://user-images.githubusercontent.com/124583/119631930-a613c600-be10-11eb-87a1-0ff9155e0ad6.png)

I wanted to send a pull request, but it appears that localization is performed automatically by localize.js, so one has no control over the result.

I see that a similar problem has been reported for German in #198, and I'd suggest like @ChristianStadelmann to simply disable Localize. I don't think it's any better than no translation at all for someone who's not able to translate it back to English.

**Comment by karianna** [comment]
We're looking for a new system when we move to Adoptium.net

**Comment by Zlika** [comment]
I agree with @Arkanosis , just drop the translations as a quick workaround, they are more harmful than helpful.

**Comment by CatMe0w** [comment]
Chinese translations have the same issue. Proper nouns such as "Hotspot" and "Windows" should not be translated.

The whole translations are automatically generated by machine and mostly are incomprehensible.

![Hotspot](https://user-images.githubusercontent.com/7774491/121771056-9ed61180-cb9f-11eb-80ab-17ef32da5218.jpg)
![Windows](https://user-images.githubusercontent.com/7774491/121771057-9f6ea800-cb9f-11eb-88a0-4f1f75ec527f.jpg)

**Comment by pgscada** [comment]
Also "Windows" is translated as "les fenetres".
This is not just bad translation but also breaks the version lookup because no version with OS "les fenetres"
+1 @Arkanosis for reverting back untranslated version until a proper solution is found

![image](https://user-images.githubusercontent.com/23451157/123542511-4891d280-d74a-11eb-9b78-672dfe158cf7.png)

**Comment by proteriax** [comment]
Please remove the French translation in the meanwhile. It’s incomprehensible and gibberish for native speakers.

**Comment by karianna** [comment]
This site is effectively deprecated for adoptopenjdk.net
