### ISSUE TITLE
add download mirrors as github is blocked in some organizations

### ISSUE THREAD

**Issue by VictorS** [AdoptOpenJDK/openjdk-website#1040]
* **All browsers**: 

Some organizations block github.com for security reasons.
Please add a mirror alternative for the downloads.

**Comment by karianna** [comment]
This is unlikely to be worked on at AdoptOpenJDK as we are transferring to Eclipse Adoptium (adoptium.net).  You may want to open an issue on the API repo in the adoptium org.
