### ISSUE TITLE
German translation of "Build archive" is wrong

### ISSUE THREAD

**Issue by dEajL3kA** [AdoptOpenJDK/openjdk-website#1041]
* **Browser**: Firefox 90.0b12
* **Problem:** German translation for *"Build archive"* currently is ***"Archiv erstellen"***, which actually means *"Create an archive"*.
  * Obvisouly doesn't capture the original meaning!
* **Solution:** German translation should probably be changed to *"Archivierte Veröffentlichungen"* (archived releases). Or, if it is okay to use the English word *build* in German (I'd be okay with that), then the translation *"Archivierte Builds"* could be used.
  * After all, you are already using *"Nächtliche Builds"* for *"Nightly builds"* - which is okay, IMHO.

![grafik](https://user-images.githubusercontent.com/13333150/125306608-a53ae300-e32f-11eb-9a46-3872b87d3717.png)

**Comment by karianna** [comment]
We'll be moving to a new translation system over at adoptium.net
