### ISSUE TITLE
No JDK-17-ea download?

### ISSUE THREAD

**Issue by RDKRACZ** [AdoptOpenJDK/openjdk-website#1043]
↓↓↓ this link from the template is dead.

http://www.bbc.co.uk/accessibility/guides/which_browser.shtml

Why is there no download links for early access java versions?

[Azul Zulu have them](https://www.azul.com/downloads/?version=java-18-ea&os=ubuntu&architecture=x86-64-bit&package=jdk).

**Comment by karianna** [comment]
We're in the middle of transitioning to adoptium.net but you can get 17 builds from the termrun17-binaries repo at the adoptium org in Github.  Ack on the browser link that's being redone as well.
