### ISSUE TITLE
Download links for JRE are pointing to old locations

### ISSUE THREAD

**Issue by AxeTheAxe** [AdoptOpenJDK/openjdk-website#1054]
* **Browser**: Firefox 90.0.2

The download links for the latest Java JREs (at least jdk8u302-b08, jdk-11.0.12+7 and jdk-16.0.2+7) are pointing to old locations for all platforms.
On the adoptium website downloads for JREs are missing at all.

**Comment by karianna** [comment]
This will be resolved when we release the latest JREs, only JDKs are our presently

**Comment by morvael** [comment]
If your infrastructure isn't ready, build JREs and JDKs for other platforms (waiting for ppc64le) using the old AdoptOpenJDK infrastructure. It's not good to boast about transition where majority of files released weren't updated and users are left in the cold :(
