### ISSUE TITLE
Linux x64 jdk-11.0.12+7 jre link is actually 11.0.11+9

### ISSUE THREAD

**Issue by tas50** [AdoptOpenJDK/openjdk-website#1072]
* **Browser**:  Firefox 91

If you browse to `https://adoptopenjdk.net/releases.html` and click the JRE link for Linux x64  11.0.12+7 it downloads 11.0.11+9

![image](https://user-images.githubusercontent.com/1015200/131236792-c62c495b-42a0-4d6d-b91c-77b22a8cfe00.png)

**Comment by karianna** [comment]
Yes, we're just waiting for the JRE release to come out - I'll see if we can patch the website in the meantime

@johnoliver - is there a short-term hack we can put in place here?

**Comment by tas50** [comment]
Thanks for the quick response @karianna. I'll keep an eye out for that JRE release

**Comment by sxa** [comment]
Complete now, and superceded by the downloads from adoptium.net
