### ISSUE TITLE
Cannot filter Windows JDK releases in non-English environment

### ISSUE THREAD

**Issue by nukemiko** [AdoptOpenJDK/openjdk-website#1073]
If your main language not is English (such as Chinese), and you want to filter JDK releases by specified OS (such as Windows, it's displayed that "视窗" in Chinese), you can't see anything.

![图片](https://user-images.githubusercontent.com/53572814/131355803-5a2e6462-eb2c-4e24-a3b3-2607e5f6fa54.png)

**Comment by karianna** [comment]
Hi there, our website is now at adoptium.net where we will be applying a new internationalization library.
