### ISSUE TITLE
Resolve Cloudflare cacheing issues

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#108]
To avoid cacheing preventing new changes from showing up:

**Option 1:**
Cache Control headers etc is a bit of a minefield.  Apache and NginX and other ‘web’ or ‘app’ servers have different ways of configuring them, but they are a std so to speak and CDNs, Browsers etc are supposed to adhere to them.  This is the field of web performance tuning.  Not sure if you’ve got someone in the org who’s an expert, if not then I’d recommend one day setting up a basic site (or a wordpress site with w3total cache plugin if you’re more comfortable with that), get that site fronted by a CDN and start seeing how the different values mean whether the browser just looks locally, goes to the CDN or goes directly to the server.

**Option 2:** 
The CSS and JS files need hashes/unique identifiers in the names every time they are built, and these unique names need to be injected into the HTML. That way, it can’t be cached when the files change, because it looks like a new file.

Once finished, the Cloudflare cache settings can be returned to the normal length of time.

**Comment by tellison** [comment]
IMHO Option 2 is a poor hack.  We should be using the standard headers to identify the cache lifetime for a response.

**Comment by Joe-Brady** [comment]
@tellison **Option 2** isn't seen as a hacky approach in the web dev community - to the point where Webpack (seen as the cutting edge tool to use for a wide variety of web dev tasks) includes a feature specifically for adding hashes to file names in production: https://webpack.js.org/guides/caching#generating-unique-hashes-for-each-file

I have now looked into **Option 1** a bit further (originally suggested by @karianna), and it's useful knowledge but it doesn't solve our problem here. All it would allow us to do is set cache lifetimes, and whether different files are cached differently.

However, it **doesn't** allow us to check whether a file has changed before loading it from the cache. This is because it would render cacheing pointless - if it has to check the server for updates anyway, it may as well not bother with cacheing at all.

The solution we need is for the website to cache files for a reasonably long time, until a file is changed, at which point that file should not be loaded from the cache.
Unless there's a way of doing that that I haven't found yet (been doing a bit of research today), I think I'll be sticking with Option 2, as it seems to be widely used as a solution to this problem.

**Comment by Joe-Brady** [comment]
Adding for history:

Got a response from a full stack web dev who is part of a team that tries to use the most cutting-edge tech… I asked for the best-practice approach to solving our problem, and mentioned using hashes as one example…he said:

“Was going to say exactly that with the hashes on your distribution code. Because caching is a good thing for performance generally, you just want to force it occasionally, if you got it auto generated in your ci you’re on to a winner”
