### ISSUE TITLE
Changelogs should be pulled from the GitHub API

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#11]
Links to changelogs should be changed following the completion of AdoptOpenJDK/openjdk-releases#4

**Comment by Joe-Brady** [comment]
Changelogs have been removed from the website until this issue is resolved.

Code has been commented out, but remains in the source.

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
