### ISSUE TITLE
Add IE compatibility

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#111]
Work out what was causing the original issue with IE and fix

**Comment by Joe-Brady** [comment]
Adding a line to set the HTTP request header as allowing cross-origin requests resolves this problem.

However, on resolving this issue, about 4 more issues sprang up related to IE compatibility. It seems that some fairly fundamental things just don't work in IE. As a result, important JS features that support things like the Latest page, the orange banner, and JSON formatting, get broken in IE.

I think that I could end up spending a lot of time trying to find workarounds for so many fundamental features might be fighting a losing battle, when I could be spending the time on more valuable contributions!

I'm closing this issue in favour of keeping the current 'doesn't work in IE, please use another browser' type message.

**Comment by karianna** [comment]
Not so fast :-D.  I suspect that once we're up and running that we'll have plenty of IE users (even older than 11!) to our site.  We'll need to run Google Analytics to be sure of course.

What are the issues that are occurring?  A common technique is to detect IE and special case some JS or CSS for it.  There are a few libs which really help with this stuff as well.

**Comment by Joe-Brady** [comment]
I'll explore this in depth when there's next time - thanks for highlighting that there are libraries to help with this stuff!

**Comment by allandequeiroz** [comment]
I've been talking with some front-end guys and they gave me some hints on how to solve this. When I finish that DISPLAY stuff on tests I'll give it a try.

**Comment by Joe-Brady** [comment]
@allandequeiroz Brilliant - thank you
