### ISSUE TITLE
Mistake of Chinese Translation of 'Migration'

### ISSUE THREAD

**Issue by RockChinQ** [AdoptOpenJDK/openjdk-website#1121]
* **Browser**:

The "Migration" button at the bottom of page https://adoptopenjdk.net/ has been translated to "移民",but it is completely not the "Migration" means in Chinese.The correct translation should be "迁移".

**Comment by karianna** [comment]
We've migrated to adoptium.net - this site (and it's translations) will be deprecated.

**Comment by LaoshuBaby** [comment]
@karianna sorry, but looks issue haven't been solved. I also caughted by this problem and haven't found any localized string in this repo. 

![图片](https://user-images.githubusercontent.com/42690037/206897474-473c4706-6cd3-4906-9def-7fa826d6985f.png)

If you deprecated this website, why not make eye-catching announcement in adoptopenjdk.net ‘s homepage?
