### ISSUE TITLE
Add missing tags etc. for SEO

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#128]
The `<h1>` tag is missing. (?)
The description is missing in the head section of the page. (not always needed)
The `<img>` tags do not have ALT attributes

**Comment by karianna** [comment]
Do meta tags still work for SEO?

**Comment by Joe-Brady** [comment]
After some research, mostly not. George had someone who works in SEO mention 'tags' to him, and we assumed meta tags... but currently following up on that as you're right, they don't really do much these days!
