### ISSUE TITLE
Minimum OS levels (and any prereqs) required for running our binaries

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#161]
I just had someone tell me that they were having issues running the openjdk binaries on their machine. There were two causes for this - one was the lack of the libffi on their Linux system (RHEL 7.4) and the other Linux system appeared to have a backlevel glibc (SLES11SP4 which was missing GLIBC_2.14)

We should put something on the site to indicate the versions of things that we depend on at runtime. (This issue could possibly have been in one of the other projects to have the discussion about what the levels will be, but ultimately it's something that will need to go on the website!)

**Comment by tellison** [comment]
Please create a wiki page for the particular platform you are trying, I suggest in the [build repo area](https://github.com/AdoptOpenJDK/openjdk-build/wiki) to start capturing the runtime requirements.  Once it looks stable it can be moved to a webpage.  For now easiest if anyone can add comments and findings to the wiki.

That will also be a place where we see the requirements and decide if some look unreasonable, and should be redistributed / hard linked.

**Comment by sxa555** [comment]
Initial seeding of information, based on the build machines we have in the farm, has been added to https://github.com/AdoptOpenJDK/openjdk-build/wiki/%5BWIP%5D-Minimum-OS-levels and can be extended as necessary

**Comment by gdams** [comment]
@sxa555 looks good! I've changed `arm` => `aarch64`

**Comment by sxa555** [comment]
Doc updated after https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256 (Ubuntu->RHEL build machine change) was done
