### ISSUE TITLE
Add a tab / note about licensing (build scripts Apache v2, actual OpenJDK GPlv2 with Classpath)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#18]
Make licensing clear that the OpenJDK source code is GPLv2 and that the build scripts etc are Apache (You can you state what license you are in Github via a LICENSE file).

**Comment by neomatrix369** [comment]
@karianna do you still want to find out about dual-licensing as part of this issue?

**Comment by karianna** [comment]
@neomatrix369 No I think the website and maybe a README will be clear enough.

**Comment by tellison** [comment]
> can you state what license you are in Github

Not sure I understand the question.  There is a LICENSE file.  Github recognizes it and shows the license type in the header strip, and elsewhere. For example, see https://github.com/AdoptOpenJDK/openjdk-build/blob/master/LICENSE

**Comment by karianna** [comment]
@tellison - Ah perfect.  So we just need to make sure we have a LICENSE file for each repo and (optionally) note that on the website in an About section or similar.
