### ISSUE TITLE
No OpenJDK 9 builds for macOS

### ISSUE THREAD

**Issue by electrum** [AdoptOpenJDK/openjdk-website#184]
Many developers use macOS for development, so having builds available would be helpful.

**Comment by gdams** [comment]
Hi there, We actually have some nightly builds of macOS OpenJDK9 (I just haven't pushed a release to the home page for now) you can get a nightly from https://github.com/AdoptOpenJDK/openjdk9-nightly/releases/download/jdk-9%2B181-20171509/OpenJDK9_x64_Mac_20171509.tar.gz for now

**Comment by gdams** [comment]
okay I have just added a macOS build to the releases page

**Comment by electrum** [comment]
Thanks!
