### ISSUE TITLE
Download page containing OpenJDK with OpenJ9 should reference / link to Eclipse OpenJ9 landing page

### ISSUE THREAD

**Issue by jonathanwoodford** [AdoptOpenJDK/openjdk-website#185]
When selecting an (Eclipse) OpenJ9 image, we should be pointing the user to the Eclipse OpenJ9 landing page so that they can obtain additional information.

https://www.eclipse.org/openj9/

* **Browser**:

**Comment by gdams** [comment]
@jonathanwoodford @EnriqueL8 is currently working on adding this, hopefully it should be in by the end of the day :)

**Comment by jonathanwoodford** [comment]
Fantastic.  Thank you  :-)

**Comment by karianna** [comment]
closed via #186
