### ISSUE TITLE
More Mistranslation to French

### ISSUE THREAD

**Issue by dorrab** [AdoptOpenJDK/openjdk-website#193]
* **Browser**: Firefox 52.3.0 (64-bit)

There is a few mistranslations 

- The AdoptOpenJDK download page: https://adoptopenjdk.net/?variant=openjdk8

"La Ferme de construction AdoptOpenJDK est un travaux en cours"
should read
" La Ferme de construction AdoptOpenJDK est un **travail** en cours"

- The About page is translated to "Sur". Sur cannot be used alone (it would mean sure or on). "About" should be translated to "A propos" 

- I would also suggest using the word "build" in french and not translate to "construction". The blue box would have the text "Dernier build" 

- Similarly, I would use "une ferme de serveurs" instead of "Ferme de construction"

As a reference you can look at the language used in http://putaindecode.io/fr/

**Comment by gdams** [comment]
Thanks @dorrab! I have made those suggested changes!

**Comment by gibfahn** [comment]
@gdams I assume this is localize based translation, would it be worth making @dorrab a translatore there?

**Comment by don-vip** [comment]
There are major problems in the translation of "The AdoptOpenJDK Build Farm is still a Work In Progress. Please DO NOT use downloaded binaries for your production purposes." (Currently: "Une ferme de serveurs AdoptOpenJDK est un travail en cours . N'utilisez PAS les fichiers binaires téléchargés à des fins de production."):

- "The" => "La", not "Une" (The/A => La/Une)
- "un travail en cours" is too literate, and "still" is gone. "est toujours en cours de réalisation" would be much better.
- "Please" has not be translated. Thus the message looks aggressive/unpolite/authoritative.

A complete translation would be "**La ferme de serveurs AdoptOpenJDK est toujours en cours de réalisation. Veuillez NE PAS utiliser les fichiers binaires téléchargés à des fins de production.**"

**Comment by EnriqueL8** [comment]
Thanks @don-vip ! Will update those

**Comment by karianna** [comment]
@dorrab and @don-vip Would you like to be added as a translator for this project?

**Comment by don-vip** [comment]
Yep, why not.

**Comment by karianna** [comment]
@don-vip Great - if you can email me the address you'd like an invite to (I'm martijnverburg at gmail) I'll get you started!

**Comment by don-vip** [comment]
Hello,
I said I could participate before Oracle announced its intention to kill Java WebStart.
Now it's clearly not possible as this decision will cause major problems for JOSM.
Can you please remove me from the organization?
Thanks.

**Comment by karianna** [comment]
@don-vip Done

**Comment by gdams** [comment]
closing as changes were made
