### ISSUE TITLE
Prevent google bots crawling dist directory

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#195]
I have noticed some images from the dist directory appearing in google images. We should block this from happening using our `robots.txt` file

**Comment by gdams** [comment]
closed in https://github.com/AdoptOpenJDK/openjdk-website/commit/ed882da80589a93b0ee583cd74accdda5b4d3b60

**Comment by EnriqueL8** [comment]
Nice!
