### ISSUE TITLE
Suggestion: Add -version info to the nightly builds download page

### ISSUE THREAD

**Issue by JamesKingdon** [AdoptOpenJDK/openjdk-website#199]
In order to track the flow of changes from the contributing projects it would be great if we could have an additional column in the table on
https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9
The column would have a link for each build to the results of running "java -version". This would allow us to see the included SHAs for the components which can then be compared with the commit history of each project.

**Comment by sxa555** [comment]
And would also have the benefit of being a very basic "Does the JVM start" test :-)

**Comment by gdams** [comment]
We do already run this at the end of every build: 
https://github.com/AdoptOpenJDK/openjdk-build/blob/8d91d551b65dd4898b98ad75f468dd5a27cc97b0/sbin/build.sh#L241

Perhaps we could archive this file with the build and push it somewhere

**Comment by karianna** [comment]
Also see #51

**Comment by smlambert** [comment]
Also, see that the java -version check currently does not work reliably for all builds:
https://github.com/AdoptOpenJDK/openjdk-build/issues/264

**Comment by karianna** [comment]
Also see https://github.com/AdoptOpenJDK/openjdk-build/issues/367

**Comment by karianna** [comment]
version string is now fixed upstream
