### ISSUE TITLE
Mistranslation to Spanish

### ISSUE THREAD

**Issue by ggam** [AdoptOpenJDK/openjdk-website#200]
There are some errors/inaccuracies on the Spanish translation:
* La lista de correos -> Lista de correo
* Enviar un problema -> Informar de un problema
* Ask on Slack -> Pregunta en Slack  -- https://adoptopenjdk.net/support.html is only half translated
* Casa -> Inicio
* Builds nocturnos -> Construcciones nocturnas
* Apoyo -> Soporte
* Último build -> Última compilación
* (https://adoptopenjdk.net/releases.html?variant=openjdk9-openj9) Construir jdk-9+181 -> Construcción jdk-9+181

Can I help in any way to improve the Spanish translation?

**Comment by karianna** [comment]
@ggam Yes you can!  Please send me your email address and I'll add you to the localise team

**Comment by ggam** [comment]
I translated most of the phrases at that time, but I kep receiving
notifications of new phrases being added that I haven't looked at yet.

Would you please give me until this weekend to review and translate what's
missing?

**Comment by karianna** [comment]
@ggam Thank you!

**Comment by ggam** [comment]
I've reviewed all the Spanish translations (new and already published ones) and they should all be ok now. There are just 6 phrases that I can't find where are used and I don't have context to translate them. Could you please have a look at them at https://localizejs.com/phrases/es?page=1&state=active&inProgressState=review? Some of them doesn't even seem to be valid.

As a suggestion, there are some text used on lots of phrases, like the "AdoptOpenJDK - Open source, prebuilt OpenJDK binaries". Moving them to a separate phrase would ensure consistency.

**Comment by karianna** [comment]
Spanish is now at 97% translated - I'm calling that good enough to close this and people can open up specific issues if need be.  Thank you @ggam !

**Comment by ggam** [comment]
@karianna it's really more towards I think, as there are some phrases  that seems to be unused. Glad to help!
