### ISSUE TITLE
Requesting Access to Localise for Persian/Farsi

### ISSUE THREAD

**Issue by mhrimaz** [AdoptOpenJDK/openjdk-website#201]
Hi,
I'm Persian and I want to help translate AdopOpenJDK to Persian/Farsi.

Best Regards

**Comment by karianna** [comment]
@mhrimaz Welcome!  I just need your email address (and some patience as we're waiting to be allowed to have more languages translated :-)).

**Comment by mhrimaz** [comment]
mhrimaz[at sign]yahoo[dot]com

**Comment by karianna** [comment]
Added!

**Comment by tellison** [comment]
@karianna Why are we blocked on more languages?  Is that a limitation from Localize (and if so can we ask nicely, since it would be a shame to pass up Hossein's offer)

**Comment by karianna** [comment]
@tellison Yes and @gdams and @Joe-Brady are already on the case!

**Comment by gdams** [comment]
We should probably probably create a repo for translations with instructions on how to join/how to use the tool. We also probably need to think up a formal way of onboarding translators

**Comment by karianna** [comment]
@gdams It's all actually in the website project wiki, just need to add link to Contributing.md I think

**Comment by gdams** [comment]
@karianna can you add all translators to https://github.com/orgs/AdoptOpenJDK/teams/translations. We should keep a record of who is being added

**Comment by karianna** [comment]
@gdams I've added who I could map back to a GitHub id.

**Comment by gdams** [comment]
thanks

**Comment by tellison** [comment]
Any progress on the Localize request to allow this to proceed?
