### ISSUE TITLE
Slack signup page clipped images on my browser

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-website#203]
Running Firefox 52.5.0 on Red Hat, the Slack sign-up page shows some clipping on the right hand side, as captured in this partial screenshot.  Notice the email address box and capcha box have no right hand line.

(p.s. would also be good to have a bit of introductory text on that page)

![image](https://user-images.githubusercontent.com/621161/33718199-7c28fc04-db54-11e7-93a8-609ad832d136.png)

**Comment by gdams** [comment]
I'm seeing the same clipping on my laptop. Will investigate now
