### ISSUE TITLE
Add https://adoptopenjdk.net/webconf to redirect to our regular meeting link

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#207]
We have a weekly meeting, usually on google hangouts, which we can provide a simple URL to - I suggest we use https://adoptopenjdk.net/webconf to keep it independent of the provider we are using in case it changes.

For reference, the most recent location of this is https://hangouts.google.com/call/V7XOZeAUKBrnm_G3798xAAEI so that should do for an initial target of the redirect

**Comment by sxa555** [comment]
NOTE: We now have https://calendar.adoptopenjdk.net pointing at the diary for the regular calls.

**Comment by karianna** [comment]
@sxa555 Is there a link on the website to that calendar?  I didn't see one,but I'm jetlagged :-)

**Comment by sxa555** [comment]
@karianna Almost certainly not but now we've got the link I'll get one added somewhere ...
