### ISSUE TITLE
AdoptOpenJDK website is not updated with links to latest nightly builds of openjdk8-openj9

### ISSUE THREAD

**Issue by mbvreddy** [AdoptOpenJDK/openjdk-website#208]
Last nightly build @ https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9 is 16th Jan 2018. But, last successfull artifact in CI https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/ is 26th Jan 2018.

**Comment by mbvreddy** [comment]
https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/ is not updated with latest artifacts.

**Comment by gdams** [comment]
resolved, I stupidly added the windows job to the nightly pipeline (which currently fails) and this was causing the entire pipeline to fail and not publish binaries
