### ISSUE TITLE
Provide a way to mark builds as Java Compliant or Production Ready

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-website#209]
The goal is to mark builds available on the main download page as 'JCK Compliant' or 'Production Ready' (or something) to denote that the build has passed the tests relevant for that java version and platform.

The builds themselves would be the same level as the Oracle quarterly updates, but marking the builds in this way will cater for the situations where there is a time lag between the creation of the build (when it can be made available on the main download page) and the completion of the testing (which may be delayed for reasons such as test machine availability).

**Comment by Joe-Brady** [comment]
This already partially exists - there is a blue 'shield/tick' icon waiting to be used from before JCK tests were happening, although it hasn't been properly tested yet so the code may need some tweaking.

https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/assets/tick.png

From memory, it's triggered by there being a "jck=true" entry in the release/binary object within the releases JSON. So the remaining work is to add this entry to the JSON automatically via the Jenkins job, or something along those lines.

Sorry I can't remember exactly how it worked, but maybe someone like @EnriqueL8 or @gdams have seen the code more recently than me?

**Comment by karianna** [comment]
@Joe-Brady This means your'e back right? :-D

**Comment by Joe-Brady** [comment]
## Area 1:
Line 69 in `releases.js`:
```
ASSETOBJECT.thisVerified = false;
```
This hardcoded value needs updating so that `false` instead gets the value of something in the JSON. If you want to just see the tick icon in-situ, you should be able to just change this to 'true' to make every release appear as jck-tested.

## Area 2:
Conditional HTML in `jck-tick.handlebars`
https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/handlebars/partials/jck-tick.handlebars

## Area 3:
setTickLink function in `0-global.js`:
```
function setTickLink() {
  var ticks = document.getElementsByClassName('tick');
  for (i = 0; i < ticks.length; i++) {
    ticks[i].addEventListener('click', function(event) {
      var win = window.open('https://en.wikipedia.org/wiki/Technology_Compatibility_Kit', '_blank');
      if (win) {
          win.focus();
      } else {
          alert('New tab blocked - please allow popups.');
      }
      event.preventDefault();
    });
  }
}
```

**Comment by sxa555** [comment]
Closing as I believe https://github.com/AdoptOpenJDK/openjdk-website/commit/09707ac18f5ae82aac8ca553bb775479d52c5a03 has resolved this
