### ISSUE TITLE
Missing "Other platforms" button when viewed in Chromium (user agent detection bug)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#210]
* **Browser**: Chromium 64.0.3282.119 on ubuntu/x64

When I go to the top level adoptopenjdk.net page the button for "Other platforms" is absent - it renders fine on Firefox. Also on the main "Latest build" button it doesn't show the download size as it does on firrefox so by default it just says `jdk-9+181`

I'll aim to have a look at the reason for it myself when I get a minute if no-one else takes it :-)

**Comment by karianna** [comment]
@sxa555 Is this still an issue for you?  Works OK on my Chromium.

**Comment by sxa555** [comment]
Still an issue for me on that Chromium version at least - here's firefox on the left and chromium on the right:
![platformsmissing](https://user-images.githubusercontent.com/6487691/38302535-f3527c80-37fa-11e8-9adc-461deed88256.gif)

**Comment by karianna** [comment]
@sxa555 So this is actually the problem I've described in #227 - It's because the website isn't picking up the platform (in the Chromium case) and so it offers up the alternative workflow of the "Latst Build ->" button effectively being the Other Platforms button.  So there's two issues here:

1.) The Ux of 'didn't detect platform' use case is confusing (I've written up a possible solution in #227)
2.) *If* your chromium is also on the same box as the Firefox, then there's a browser / platform detection bug

**Comment by sxa555** [comment]
Yep that screenshot above of the two browsers side by side on the same screen on the same laptop (Ubuntu 16.04/x64) so likely a platform detection (Presumably it's done on the `User-Agent` string?) bug.

**Comment by gdams** [comment]
@Joe-Brady, could you point us to where the user-agent detection takes place? I've done a quick search myself but couldn't dig it out.

**Comment by gdams** [comment]
So this is set in https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/json/config.json#L46. @sxa555 could you go to https://www.whoishostingthis.com/tools/user-agent/ in your browser and paste the output into this issue so we can work out what we are missing

**Comment by sxa555** [comment]
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.167 Chrome/64.0.3282.167 Safari/537.36`

**Comment by gdams** [comment]
hmm so `Linux` and `Ubuntu` are both in that string so I'm not sure why we are having detection errors

**Comment by gdams** [comment]
@sxa555 is this still an issue?

**Comment by sxa555** [comment]
Yes, and I'm also getting it on firefox 60

**Comment by karianna** [comment]
@sxa555 Grab me next time you're online and we can live debug from your desktop.  It'll be similar to the Linux XL problem

**Comment by sxa555** [comment]
.Just went back to test this - the button is showing on My Quantum 60.2.0esr although not on IE on my Windows Phone 10

**Comment by karianna** [comment]
User agent string from your IE10 on your phone?

**Comment by karianna** [comment]
@sxa555 Can you try again in about 30 mins?  We've fixed a few issues in this area and it might be resolved for you now.

**Comment by sxa555** [comment]
Seems ok now on everything I've tried ... Closing :-)
