### ISSUE TITLE
AdoptOpenJDK link pointing to java.net is broken on the About page

### ISSUE THREAD

**Issue by fjeremic** [AdoptOpenJDK/openjdk-website#212]
Under the _About the AdoptOpenJDK Community_ section on https://adoptopenjdk.net/about.html the very first link "AdoptOpenJDK" pointing to https://java.net/projects/adoptopenjdk/ is broken. This page is deprecated.

**Comment by gdams** [comment]
perhaps we could request that java sets up a redirect to adoptopenjdk.net?

**Comment by karianna** [comment]
adoptopenjdk.org once I purchase it - in the meantime I'll link to the Oracle community page
