### ISSUE TITLE
Nightly build archive lists incorrect +x number

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-website#214]
* **Browser**: Firefox

The nightly build archive for jdk10 lists the builds as "+23" builds, however the download untars as "+41".

Is there a number somewhere that wasn't manually updated?

**Comment by karianna** [comment]
@adamfarley Yes this is currently a manual number that needs to be set in the build jobs.  There is an issue to autoupdate this as well.

**Comment by gdams** [comment]
This isn't a website issue. It's actually to do with the openjdk-build scripts. Like @karianna said, we currently have to update the build version when a new version is added to our source code. I'm going to close this and it can be re opened in openjdk-build if needs be
