### ISSUE TITLE
Website is currently not showing all the download links

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#215]
![sitedown](https://user-images.githubusercontent.com/6487691/36982935-028683ba-2089-11e8-9acc-7d49c98ba41d.gif)
Reported by someone else and I'm seeing it just now. At the time of writing the page is mostly rendering but the table under "Downloads" is stuck with a three dot "loading" animation, so no-one can currently download.

**Comment by Joe-Brady** [comment]
It works for me in Chrome, FF and Safari on Mac - was the other person reporting this also on Linux? And can you take a screenshot of the browser dev console if there's some errors showing up?

**Comment by Joe-Brady** [comment]
Also does this show up in staging.adoptopenjdk.net for you?

**Comment by sxa555** [comment]
Yeah happens on staging too. Hmmm it's failing with firefox 52ESR on RHEL6 but is ok on Ubuntu 16.04 with FireFox Quantum 58.0.2

**Comment by sxa555** [comment]
Hmmm https://raw.githubusercontent.com/AdoptOpenJDK/openjdk9-releases/master/latest_release.json isn't working - that site isn't currently resolving which isn't good ...

**Comment by sxa555** [comment]
I'm going to close this (unless it shows up after some timeout) since it looks like it's our local DNS server that isn't resolving raw.githubusercontent.com just now
