### ISSUE TITLE
doc links on the "variant" web pages are broken

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#216]
Not sure how many of the links are affected but if you go to the download site for one of the variants e.g. https://adoptopenjdk.net/?variant=openjdk8-openj9 then the link at the bottom of the page to `Meeting diary` goes to https://calendar.adoptopenjdk.net/?variant=openjdk8-openj9 where it shouldn't have that `variant` on the URL. It doesn't cause a problem for all of the links on the page but is superfluous for most, but it does prevent the diary link from working.

**Comment by gdams** [comment]
Hmm this is weird... When I clone the website and run it on my computer I don't have this issue.
