### ISSUE TITLE
As a user/tester, I want to be able to identify and download a "release candidate" build

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#217]
At the moment we do not have a good mechanism for identifying a "release candidate" bulld which is currently the one under test when we are preparing for a release. Users (and adoptopenjdk testers) would like to be able to identify which build is the correct one to pick up from the nightly build list. There are a couple of options:

1. Have a separate option on the web site alongside the "release" and "nightly" builds for "pre-release" builds under code freeze
2. Have a way to flag one specific nightly build as a formal release candidate (we may wish to have multiple ones if we want to flag multiple release candidates simultaneously)
3. Stop automatically building nightlies while in a "release candidate" phase/iteration so the latest nightly is by implication the release candidate during that period.

I've "assigned" this to a few people as those likely to have a view (feel free to add other assignees if you so desire) I'm fairly easy about which of these three options we go for - the first would be a way of publicising builds of an upcoming release more effectively, but would make the web site a bit more complex. Either way I think having a "latest RC" API call could be useful for test automation, although option 3 would render that unecessary as the nightly would always be the RC.

**Comment by tellison** [comment]
I agree that having a documented release process will be helpful, including a way to reliably identify the release candidate for a particular code stream.

However, I'm not convinced that we should be using the front page of the website to offer up lots of different quality levels to end users, as that would likely be confusing for people.

**Comment by sxa555** [comment]
True - this may simply be a way of tagging the nightly build with an RC logo

**Comment by karianna** [comment]
Yeah this is really an issue that pushes back on the build scripts.  We could add a 'release-candidate' concept in the pipeline which would use a timestamp but perhaps add some extra meta data

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
