### ISSUE TITLE
Add a 'www.' subdomain

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#22]
Currently, www.adoptopenjdk.net does not work.

CNAME needs to be set up:

https://help.github.com/articles/setting-up-a-www-subdomain/

**Comment by Joe-Brady** [comment]
Is this something I can do by simply adding www.adoptopenjdk.net to the CNAME file? Or is it a DNS change too?

**Comment by gdams** [comment]
I believe that you have to add something like this to the CNAME record... `www  CNAME   @`
