### ISSUE TITLE
openjdk8-openj9 version string not being displayed correctly on FireFox/Linux

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#221]
Affected URL: https://adoptopenjdk.net/?variant=openjdk8-openj9

May be affecting other environments too, but it works for me on Chromium and several other environments are similarly ok. It looks like the new longer version string for openjdk8-openj9 is causing firefox to try to wrap the text onto a second line (at various places, usually after a hyphen) depending on the exact string used.

If you drop the font size (`8rem` in the `a.dl-button .dl-description` section of https://adoptopenjdk.net/dist/css/styles.min-35b46ca5.css then it displays the full version string.

![image](https://user-images.githubusercontent.com/6487691/37465246-86da30e6-2852-11e8-8c4b-ccfdcec240ee.png)

**Comment by samkamer** [comment]
I looked through most of the CSS and can't find anything obvious. The only possible culprit I found is the overflow-x=hidden on html and body, that will get inherited. Is it possible to try removing that ? It does not seem ideal to me to put text overflow as hidden at such root elements.

**Comment by sxa555** [comment]
Trying to override `override-x` didn't seem to work, but I've got a fix to force it not to word-wrap which should be ok unless the text gets too big for the button :-)

**Comment by sxa555** [comment]
Now live and confirmed working in FireFox on Linux :-)
