### ISSUE TITLE
Can we use a proper java / duke logo on the certified builds?

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#224]
If we can now do so it would be good to have a recognised "java certified" logo on our web pages instead of the tick now that we've got builds marked as certified via https://github.com/AdoptOpenJDK/openjdk-website/issues/209 . Is there anything stopping us from doing that? Question possibly mostly for @karianna I suspect?

**Comment by karianna** [comment]
Legally not at all.  A Duke logo would have some cool factor, but I'm actually leaning towards a tick being universally more recognized as "This thing is good."

**Comment by DanHeidinga** [comment]
+ 1 to the tick being a better choice.

WRT duke logo, we'd be in the clear.  Based on my reading of the JCK license other Java branding (coffee cup, etc) may be questionable.

**Comment by sxa555** [comment]
See also https://github.com/AdoptOpenJDK/openjdk-build/issues/84

**Comment by gdams** [comment]
I personally like the tick but I'm open to other ideas :)

**Comment by karianna** [comment]
I'm going to close this one as won't fix and I've asked Kerry to take a look at the logo design.
