### ISSUE TITLE
Initial landing page doesn't have any certification indication on it

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#225]
Ref, for example: https://adoptopenjdk.net/?variant=openjdk8-openj9
We should ideally have an indication on the primary page that people will get to indicating it's production ready status.

**Comment by karianna** [comment]
The blue shield could be used here.

**Comment by gdams** [comment]
I started work on this so I'm happy to finish it! the front page seemed to use a whole load of separate javascript so I wanted to refactor it a bit
