### ISSUE TITLE
Update wording on support page now that we have JCK certified builds

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#226]
https://adoptopenjdk.net/support.html currently says our builds "are not JCK/TCK compliant". Now that this is not the case we should update that statement. I would suggest we also explain the meaning of the logo we are using for indicating compliance.

Opening this as a placeholder for suggesting appropriate wording - I shall assign to @karianna as ultimately he's the one who should have the final say :-)

**Comment by mstoodle** [comment]
I took a brief crack at this last night and have a not-quite-right commit people are welcome to use a starting point, in case it's helpful:
https://github.com/mstoodle/openjdk-website/commit/c9d1f6fecddfa23715d4cc5f0a5db6ce56c0fa31

I was trying to show an example of the download button with the checkmark so people would know what they're looking for, but it's not right (@gdams rendered a version of it and all it shows is the actual checkmark as opposed to an example of the download button with the checkmark).

**Comment by gdams** [comment]
Created: https://github.com/AdoptOpenJDK/openjdk-website/pull/223

**Comment by lumpfish** [comment]
We are creating builds from the code level which matches the Oracle quarterly updates, so that a user knows which security (and other) fixes are included.  So our jdk8u162-b12 build matches the Oracle java SE 8u162 (Jan 18) update.  I don't think that relationship would be obvious to the average visitor.

**Comment by sxa555** [comment]
Interesting point @lumpfish ... I would have thought that would be people's default assumption when they see the `8u162` matching what Oracle have released at http://www.oracle.com/technetwork/java/javase/downloads/index.html (Since I suspect most people will not know about quarterly update build numbers) but it might be worth adding a section of explanation. Perhaps someone from Oracle would like to chime into the discussion to suggest any appropriate wording on this topic?

**Comment by lumpfish** [comment]
I was think maybe an extra column with "Java SE 8u162 level (Jan 2018 update)" or something similar.

**Comment by karianna** [comment]
We could even link to the equivalent Oracle page on this?

**Comment by sxa555** [comment]
See also @tellison's support doc proposal at https://docs.google.com/document/d/19zO0yZidQEmDEVx8whnbsGDR2HpnQmP2mJ0nvDeQfsE/edit?usp=sharing

**Comment by karianna** [comment]
Assigning to @tellison as his support doc has what we need :-)

**Comment by gdams** [comment]
closing as this is now live https://adoptopenjdk.net/support.html#quality
