### ISSUE TITLE
Link to "Other Platforms" not working correctly

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-website#227]
Tried on Chromium and Mozilla.

Go to the [OpenJDK8 with OpenJ9 variant page](https://adoptopenjdk.net/?variant=openjdk8-openj9), and click on "Other Platforms".

Depending upon where you click on the button the browser:
1)  starts to download a build for the current platform rather than presenting a list of alternate platform builds, or
2) shows the correct list of alternate architectures

**Comment by karianna** [comment]
I don't get the Other Platforms button - could be related to #210

**Comment by vladimir-dejanovic** [comment]
link form download button  goes over visible part of "other platforms" button,so if you are with mouse at the top off the button, you are actually hitting the link for upper button.

**Comment by vladimir-dejanovic** [comment]
should be fixed by #239

**Comment by gdams** [comment]
closing as this is just confusing UX. This has already been discussed in the website redesign.
