### ISSUE TITLE
Archival of OpenJDK 9 builds once Apr CPU is released

### ISSUE THREAD

**Issue by stevewallin** [AdoptOpenJDK/openjdk-website#236]
Once OpenJDK 10 update 1 comes through in April 2018 Java 9 should be considered insecure unless someone back ports all the fixes into that code stream.  I would propose that OpenJDK 9 is removed from the available list on the website in good time to protect our users from obtaining out of date drivers.

**Comment by karianna** [comment]
I pretty strongly disagree with this.  I'm happy for these to be dropped to an unsupported category or nightly category but not to be removed.

**Comment by tellison** [comment]
@stevewallin  this is only one, user-facing, aspect of removing a code stream from AdoptOpenJDK's build test pipeline.  I've raised the bigger picture as [a TSC issue](https://github.com/AdoptOpenJDK/TSC/issues/18).

**Comment by stevewallin** [comment]
@tellison yes, have seen it and agree with comments...

**Comment by stevewallin** [comment]
yes, perfect

**Comment by karianna** [comment]
This ties into having 8 and 11 as LTS releases displayed front and center but the other releases elsewhere.

**Comment by gdams** [comment]
this is now complete with a warning message
