### ISSUE TITLE
Slack link in support points to the wrong place 

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#246]
From: https://github.com/AdoptOpenJDK/openjdk-build/issues/299

The contact page (https://adoptopenjdk.net/support.html) suggests slack as a medium to contact.

However the slack workspace seems to be closed off:

>  Don't have an account on this workspace yet? Contact the workspace administrator for an invitation

**Comment by gdams** [comment]
should just be a case of switching the URL to https://adoptopenjdk.net/slack

**Comment by karianna** [comment]
#247 will resolve this.
