### ISSUE TITLE
Misleading Latest builds links

### ISSUE THREAD

**Issue by kdt** [AdoptOpenJDK/openjdk-website#250]
The latest "OpenJDK 10 with Hotspot" build (jdk-10+23)
listed on the [front page](https://adoptopenjdk.net/?variant=openjdk10) is from November 2017.
(final Java 10 was released on March 2018)

How bad it is?

It does not include the new API (e.g. List.copyOf)
and probably misses most of the new Java 10 features.
Generally, it's useless.

Anyone who downloaded this build by accident,
should remove it, and use proper version instead.

Thanks :)

**Comment by gdams** [comment]
closing as these releases have been removed
