### ISSUE TITLE
no nightly aarch64 builds on website since the 6th March

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#251]
https://adoptopenjdk.net/nightly.html is now showing no aarch64 builds. I suspsect that this could be to do with @smlambert's changes to allow us to upload a subset of platforms

**Comment by smlambert** [comment]
Expect next Java9 arm64 builds to be uploaded to website (fixed by [build 314](https://github.com/AdoptOpenJDK/openjdk-build/pull/318))

**Comment by smlambert** [comment]
Closing as fixed, the aarch64 nightlies are now being released regularly (example: [May 9th aarch64 build for openjdk9](https://github.com/AdoptOpenJDK/openjdk9-nightly/releases/download/jdk-9%2B181-20180509/OpenJDK9_aarch64_Linux_20180509.tar.gz))
