### ISSUE TITLE
AdoptOpenJDK build pages typically show incorrect "build/release level"

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-website#252]
The build page "Release" build levels seem to be usually wrong, eg.
https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9
Is listed as "jdk8u162-b12", but is actually "jdk8u172-b11".
https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9
Is listed as "jdk-9+181-20", but is actually "jdk-9.0.4+12".

I suspect the website hard codes the release level?

Ideally it would be good to list the actual build's "java -fullversion" string as the level...?

**Comment by karianna** [comment]
Yes this is known issue from our build and deploy scripts, we are currently overhauling those and should have this resolved in a few weeks (once it all filters through).  I'll keep this open though I think the version string is an interesting idea.

**Comment by johnoliver** [comment]
with changes to the website the above links are now:
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9

**Comment by karianna** [comment]
FYI - The page at https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9 has the label `jdk8u162-b12_openj9-0.8.0` which links to https://github.com/AdoptOpenJDK/openjdk8-releases/releases/tag/jdk8u162-b12_openj9-0.8.0 (which doesn't exist, it's the wrong repo).  I think that label should read `jdk8u172-b11__openj9-0.8.0` and point to https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/tag/jdk8u162-b12_openj9-0.8.0

**Comment by karianna** [comment]
@andrew-m-leonard Do you know where you were linking from?  The URL will need to be updated as @johnoliver suggests

**Comment by karianna** [comment]
This has been reported and is being fixed in OpenJ9 website.
