### ISSUE TITLE
GDPR considerations

### ISSUE THREAD

**Issue by SueChaplain** [AdoptOpenJDK/openjdk-website#254]
1. Slackin
The Slackin service knows which email addresses have previously requested an invitation to the workspace. Are there any GDPR considerations here? Does the service store email addresses or does it dynamically query the slack workspace API for this information. Some javascript skills needed to figure this out.

2. Google Analytics
I can see that Google Analytics is enabled on the site. At a minimum I believe this requires a privacy pop up to comply with GDPR, but more importantly is who has access to this data and how are they using it. The Eclipse Foundation are taking steps to ensure that community projects are not collecting data through Google Analytics. Is a similar consideration required at AdoptOpenJDK too?

**Comment by karianna** [comment]
@SueChaplain Thanks for raising this, also pulling in @AdoptOpenJDK/security.

1. AFAIK the slackin service uses a slack workspace API call to determine the user account (i.e. It doesn't store the email address itself.  Ah, I see you've raised https://github.com/rauchg/slackin/issues/373 that's great, thanks!

2. It depends on what data GA is tracking.  We'll need to look into that for sure.  GA have themselves updated their GDPR policies and storage / access etc.

The AdoptOpenJDK community is legally backed by the London Java User group and we value privacy concerns and so we'll take the responsibility here and look to resolve these issues.

@SueChaplain - I assume you have some GDPR expertise?  Would be great to hear the details of what the Eclipse Foundation is doing as an example.

**Comment by SueChaplain** [comment]
Hi @karianna - I'm no expert in GDPR, but I'm trying to make sure that the Eclipse OpenJ9 website meets the requirement. We also use slackin, so I was hoping someone at Adopt might know how it works under the covers. I also think it is an API call, but would be good to have confirmation. I'll share any info I get from https://github.com/rauchg/slackin/issues/373 on that front.

For Google Analytics, the Eclipse Foundation do not want projects to collect data independently on their project websites because that data may be shared with third party companies that employ them. I just happened to see a GA seed in the AdoptOpenJDK page source, so mentioned it in case there are similar concerns. I guess it comes down to notifying users that data is being collected via a cookie consent popup (I believe GA uses IP address at least to produce demographic charts, which is personal data), and then who has access to that data and how it is used.

There is a lot of activity around GDPR at the moment so I guess we'll all be expert soon :-)

**Comment by gdams** [comment]
@tellison the GA data can be useful to us! It's also worth noting that cloudflare collects similar data!

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
