### ISSUE TITLE
api.adoptopenjdk.net giving Error 502: Bad gateway

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#255]
Title says it all - the API is currently unavailable.

May come back soon based on the CloudFare message at the top:

`This page (https://api.adoptopenjdk.net/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert`

**Comment by gdams** [comment]
came back up by running `export PRODUCTION=true && /usr/local/bin/forever start /home/jenkins/openjdk-api/server.js`

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-api/issues/51

**Comment by sxa555** [comment]
According to gdams the forever process had disappeared - reason unclear.
