### ISSUE TITLE
Add download size in MB to home page "Latest release" button

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#26]
Note: this should only appear if the button is linking to the download directly - not if it is the generic 'no appropriate OS' link.

**Comment by tellison** [comment]
On the main download button, really?
It is already quite busy.

p.s. why does the build ID have parentheses around it?  I think it reads better without.

**Comment by Joe-Brady** [comment]
The size in MB is included on the download buttons on the Latest page and Archive page, so I thought it would be good for consistency and information.

If you're thinking not, that's fine.

I can remove the parentheses easily - will do that for my next commit

**Comment by Joe-Brady** [comment]
Parentheses removed

**Comment by gdams** [comment]
No I do think that we should have the file size, just something like `jdk8u152-b01 - 79MB` like on the archive page
