### ISSUE TITLE
Add ability to flag "release candidate" builds 

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#264]
This will likely be a flag against the nightly builds.

The openj9 team produce "release candidate" drivers before the final release ones. These are taken off a separate branch and should be flagged in such a way as to make them easy to distinguish from the normal nightly builds (in the absence of creating a new, potentially confusing, section on the website) This will involve passing through an RC boolean flag on the nightly pipelines to indicate an RC build and having it show up on the web site somehow.

Potentially this could be rolled into the work item that is floating around to add a version number to the downloads page if this is also done for nightlies, but I think a separate clear flag would be preferable

**Comment by karianna** [comment]
See #217

**Comment by sxa555** [comment]
Clearly I can't remember what I did a few months ago - closing as dup ;-)
