### ISSUE TITLE
Check / Fix German translation

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/openjdk-website#273]
Hi,
I would love to have a look at the German translation and add some better translations.

**Comment by tellison** [comment]
Thanks Hendrik.  I can create an account in Locallise for you to use.
Is it ok to use your me.com email address listed in Github, or would you prefer to use another?

**Comment by hendrikebbers** [comment]
no that address will be fine.
THX

**Comment by tellison** [comment]
Done.  You should receive an invite via email to join the team.

Follow [the instructions on the wik](https://github.com/AdoptOpenJDK/openjdk-website/wiki/Becoming-a-translator-of-AdoptOpenJDK.net)i - and of course if you can improve the instructions that would be great too!

Feel free to reopen this issue if the process is not working for you, and join us on the [Slack](https://adoptopenjdk.net/slack.html) #website channel to chat about anything.

I appreciate your help Hendrik!  Danke.
