### ISSUE TITLE
Distinguish linuxXL builds

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-website#278]
Currently on:

https://adoptopenjdk.net/nightly.html?variant=openjdk9&jvmVariant=openj9

There is no way to tell the difference between normal and XL builds unless you look at the link you are being sent to.

Need to add some indication of XL in the page

**Comment by johnoliver** [comment]
Yeah, so the problem I think is that since the file name has changed that searchableName is not matching anymore. I think its a bit brittle to keep matching on the name of the file, think ideally we should start getting the API to return some additional meaningful information about the binary.

Currently its:

```
  {
    "release_name": "jdk9u-2018-07-27-11-04",
    "timestamp": "2018-07-27T11:04:13Z",
    "binaries": [
      {
        "os": "linux",
        "architecture": "x64",
        "binary_type": "jdk",
        "openjdk_impl": "openj9",
        "binary_name": "OpenJDK9U_x64_linux_openj9_linuxXL_2018-07-27-10-36.tar.gz",
        "binary_link": "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk9u-2018-07-27-11-04/OpenJDK9U_x64_linux_openj9_linuxXL_2018-07-27-10-36.tar.gz",
        "binary_size": 212005494,
        "checksum_link": "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk9u-2018-07-27-11-04/OpenJDK9U_x64_linux_openj9_linuxXL_2018-07-27-10-36.tar.gz.sha256.txt",
        "version": "9"
      }
    ]
  },
```

so we could add something to that to indicate "linuxxl" rather than matching on the file name

**Comment by smlambert** [comment]
Agree, I just wanted to make sure you were aware of the (tenuous) way it was before.  :)

**Comment by karianna** [comment]
Resolved
