### ISSUE TITLE
Variant dropdown on archive page missing, if no archived releases available

### ISSUE THREAD

**Issue by Maldivia** [AdoptOpenJDK/openjdk-website#279]
Tested in Chrome 67 and Safari 11.1.2

The Archive page usually displays a drop down where variant can be selected, but if the chosen variant doesn't have any archived releases, the dropdown is not present to select something else.

Example screenshots below of the dropdown present for OpenJ9 Java8, and gone from OpenJ9 Java9 (as there are no archives yet for that variant):

https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9
![image](https://user-images.githubusercontent.com/1133537/43516183-752a7ef2-958d-11e8-8876-ba6e883873ce.png)

https://adoptopenjdk.net/archive.html?variant=openjdk9&jvmVariant=openj9
![image](https://user-images.githubusercontent.com/1133537/43516209-9067ef60-958d-11e8-9fc6-c902ce88ff5c.png)

**Comment by ParkerM** [comment]
I believe this has been resolved by #339.  
The radio buttons remain functional when a release is not found, [example here](https://adoptopenjdk.net/archive.html?variant=openjdk7&jvmVariant=hotspot):

![image](https://user-images.githubusercontent.com/5124113/58292829-92987500-7d88-11e9-90ac-a3d891fba546.png)
