### ISSUE TITLE
Wrong Date displayed on releases page for language german

### ISSUE THREAD

**Issue by rgra** [AdoptOpenJDK/openjdk-website#280]
* **Browser**: Firefox Quantum 61.0.1 (64-bit, Windows)

Build jdk8u172-b11 has an incorrect date format. There seems to be a problem with moment.js?
Datum: 19 Kann 2018
"Kann" is not a month in german.

Selecting other builds with other months works:

Build jdk8u162-b12_openj9-0.8.0
Datum: 15 März 2018

There should be a . behind the day for german. Might be better to use format("ll") instead of formatting day, month, year separately.

![grafik](https://user-images.githubusercontent.com/1619079/43829997-994d8766-9b00-11e8-86d7-577759d2e38f.png)

**Comment by karianna** [comment]
I think this is a localize translation issue

**Comment by Chirlu42** [comment]
Not sure if this should get it's own I18N bug. In the above screenshot the English term "Build archive" was translated to "Archiv erstellen" which means "create an archive". (The noun 'build' was treated as a transitive verb for translation).

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
