### ISSUE TITLE
Modify platform detection so that the openj9 large heap is not the default on Linux/x64

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#283]
1. Go to adoptopenjdk.net from a Linux/x64 browser
2. Select openjdk8-openj9 from the dropdown
3. Large heap build is selected as the default - it should be the standard compressed refs build

**Comment by gdams** [comment]
closing as PR landed

**Comment by sxa555** [comment]
@gdams The default when you go to it on Linux is currently the LH build - it points to https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_linuxXL_8u202b08-openj9-0.12.1.tar.gz - this is not fixed

**Comment by Hello71** [comment]
Seems to work fine now.
