### ISSUE TITLE
JCK checkmark only shows up on the subscreen

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-website#299]
* **Browser**: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

The JCK checkmark only shows up on the subscreen and not the main landing page.

Example
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9
![image](https://user-images.githubusercontent.com/6430052/46028264-1137f800-c0be-11e8-87d1-5ca5d941fc3a.png)

https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#x64_linuxlh
![image](https://user-images.githubusercontent.com/6430052/46028313-2f9df380-c0be-11e8-880d-47675225911e.png)

Also, perhaps a different issue, the big blue download button in the second image just looks out of place having all that space with the JCK checkmark aligned to the right on the button. It almost looks like something isn't being rendered on the button.

**Comment by karianna** [comment]
As per our support statement, we aren't supporting this for now.
