### ISSUE TITLE
What are Hotspot and Eclipse OpenJ9?

### ISSUE THREAD

**Issue by janpio** [AdoptOpenJDK/openjdk-website#301]
When visiting https://adoptopenjdk.net/ on Windows I get these download options:

![image](https://user-images.githubusercontent.com/183673/46078829-93472000-c195-11e8-930d-3a17ce2adfff.png)

What are Hotspot and Eclipse OpenJ9? Which should I choose and why?
(What is "amber"?)
I couldn't find any information on that page or "About".

**Comment by EsRa13** [comment]
short google shows:

https://en.wikipedia.org/wiki/Comparison_of_Java_virtual_machines
https://www.eclipse.org/openj9/oj9_faq.html
...

**Comment by janpio** [comment]
So the expectation should be for everyone to use Google to learn about this? I hope not.

**Comment by karianna** [comment]
This is being resolved in https://github.com/AdoptOpenJDK/openjdk-website/pull/339
