### ISSUE TITLE
Suggestion: Add Test statuses for binaries on nightly page.

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-website#314]
I would like to propose an enhancement to the nightly download page that displays a status for each test level and links to the Jenkins test jobs for each nightly binary. This could give the users on the bleeding edge some level of confidence in what they're getting (good or bad). The Jenkins build badges come to mind but I'm not sure how you would persist that data once the jobs are cleaned up.
I think this is unnecessary for the release binaries as it should be assumed they are all green. The caveat being the JCK checkmark.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/wiki/OpenJDK11-Release-Status
