### ISSUE TITLE
Support MacPorts

### ISSUE THREAD

**Issue by breun** [AdoptOpenJDK/openjdk-website#315]
I'm the maintainer for the OpenJDK ports in MacPorts (currently Oracle's OpenJDK 10 and 11 builds) and I'm considering to support AdoptOpenJDK builds in MacPorts.

After downloading an OpenJDK build from Oracle at jdk.java.net on my Mac I can drop the unpacked archive into `/Library/Java/JavaVirtualMachines` and it will be found by macOS default tools like `/usr/bin/java` and `/usr/libexec/java_home`. This means I don't need to add anything to my `$PATH` to use a specific Java version and can easily switch Java versions. For instance, I can use this in my shell profile to use Java 8 by default:

```
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```

Or just this if I want my `$JAVA_HOME` to be set to the latest version (i.e. 11 if I have that installed):

```
export JAVA_HOME=`/usr/libexec/java_home`
```

The Oracle OpenJDK build will also show up in the output of:

```
$ /usr/libexec/java_home --verbose
```

The `java_home` tool can also be used to execute a command using a specific Java main version:

```
$ /usr/libexec/java_home -v 11 --exec java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
$ /usr/libexec/java_home -v 10 --exec java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

However, the AdoptOpenJDK builds don't seem to integrate with these macOS tools. If I unpack AdoptOpenJDK 8 into `/Library/Java/JavaVirtualMachines` this version is not found by `/usr/libexec/java_home` and not used when executing `/usr/bin/java`. Currently the AdoptOpenJDK installation instructions at https://adoptopenjdk.net/installation.html#x64_mac say to prepend your `$PATH` with the installation directory, but this means users lose the features and convenience offered by the macOS CLI Java tools.

I don't know exactly what is required for a directory under `/Library/Java/JavaVirtualMachines` to be recognised as a JVM by these tools, but one difference seems to be that Oracle OpenJDK builds use a different directory structure starting with `Contents/` containing an `Info.plist` file.

**Comment by breun** [comment]
I'm sorry, I posted this in the wrong repository and this issue also seems to be a duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/321

**Comment by karianna** [comment]
Hi @breun - we've love to be part of ports.  I've added another reference to AdoptOpenJDK/openjdk-build#321 which links to a similar issue for our brew installer.  We'd love to get your advice on how openjdk is packaged in the existing ports, that might help us produce the right installer for Adopt.  Are you able to join us on our slack?  Adoptopenjdk.net/slack.html  CC @gdams

**Comment by karianna** [comment]
@breun Great news!  We're just getting out one more re-release today and that official binary will be available.  I'm going to reopen this issue with a new name to track getting us into MacPorts (which I use myself!) :-)

**Comment by karianna** [comment]
Actually, the wrong approach I guess - should I open an issue over on MacPorts?

**Comment by breun** [comment]
@karianna I'll work on it and open a pull request with MacPorts when I'm done.

**Comment by karianna** [comment]
Awesome thank you so much for the support!

**Comment by gdams** [comment]
@breun probably worth trying to mirror the brew casks as closely as possible: https://github.com/Homebrew/homebrew-cask/pull/52874

**Comment by breun** [comment]
@gdams Thanks, I'll take a look there.

**Comment by breun** [comment]
@gdams Why are those `ln` and `PlistBuddy` commands necessary exactly? If they are necessary it might be good to add comments for why.

**Comment by gdams** [comment]
so the `ln` is what the official openjdk cask does as well so I copied it (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb) The plist commands are essentially needed to populate the other fields so that when you run `/usr/libexec/java_home -V` it pulls in the vendor info:

```bash
    11, x86_64:	"AdoptOpenJDK 11"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
```

**Comment by breun** [comment]
@gdams Shouldn't the vendor info be fixed directly in the plist that is shipped in the release tarball?

**Comment by gdams** [comment]
possibly and it's something that we are going to work on but for this release we've not done so. The idea is that hopefully in the next release we can skip doing this

**Comment by gdams** [comment]
JDK8 monday or tuesday this week, 9 and 10 I'm not so sure.

**Comment by breun** [comment]
Ok, I'll wait for the AdoptOpenJDK 8 release then before submitting to MacPorts. Since Java 9 and 10 are already EOL I think I just won't include those versions.

**Comment by karianna** [comment]
We may rebuild 9 and 10 releases as they are good testbeds for any major changes that we make to our pipelines etc, but yes since 9 and 10 won't get more security and stability updates it's almost better not to let the ecosystem have access to them.
