### ISSUE TITLE
Create a menu system

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#32]
Menu will be hidden by default inside a 'hamburger button', i.e. mobile-style.

Apple.com in mobile size is an example of the minimal appearance we could go for:
<img width="340" alt="screen shot 2017-03-22 at 11 39 44" src="https://cloud.githubusercontent.com/assets/20062773/24196121/62bf5998-0ef4-11e7-8875-b82216c956ed.png">

This menu button will be the consistent appearance for all window widths. This has two advantages:

- We will only need to design one menu system, and it will work for all devices and screen widths
- It will preserve the current minimal appearance of the header

**Comment by Joe-Brady** [comment]
@karianna What items would you like to be in the menu?
e.g.

Home
Latest release
Archive releases
Nightly builds
Installation
Get involved
Support

**Comment by Joe-Brady** [comment]
I'm beginning this work now

**Comment by Joe-Brady** [comment]
<img width="688" alt="screen shot 2017-03-22 at 15 14 14" src="https://cloud.githubusercontent.com/assets/20062773/24205083/4b0b63c8-0f12-11e7-964d-ccc9261f5be8.png">
<img width="711" alt="screen shot 2017-03-22 at 15 14 21" src="https://cloud.githubusercontent.com/assets/20062773/24205084/4b0cb3ea-0f12-11e7-922a-363ecda2c40e.png">

**Comment by karianna** [comment]
I'll add an About page later on which cover the why behind this effort and maybe a Licensing page as well, but this looks like a great start!!
