### ISSUE TITLE
Replace social icons with font-awesome social icons

### ISSUE THREAD

**Issue by xtbe** [AdoptOpenJDK/openjdk-website#326]
In order to make it easier to handle the social icons the images should be replaced with their font-awesome  equivalents

**Comment by xtbe** [comment]
Did a fork and adapted the icons, i also reduced the spacing a little bit so that the icons in the sidebar are again on 1 line after adding the Twitch icon

This is the result in the header

![header](https://user-images.githubusercontent.com/909796/46554523-e3825880-c8e0-11e8-9f46-6023ad1637c4.gif)

I tried to variants for the sidebar 

Without border

![bar-noborder](https://user-images.githubusercontent.com/909796/46554572-090f6200-c8e1-11e8-98fa-24fb930443a9.gif)

With border

![bar-border](https://user-images.githubusercontent.com/909796/46554588-12003380-c8e1-11e8-8104-a6dfab108b77.gif)

If ok, i can create a PR during the weekend, just indicate if the border or borderless version should be used.

**Comment by tellison** [comment]
FWIW I like the border, thanks!

**Comment by gdams** [comment]
Yeah looks great! love the border as well! Please submit a PR

**Comment by xtbe** [comment]
PR request created : https://github.com/AdoptOpenJDK/openjdk-website/pull/328
