### ISSUE TITLE
Update export path on mac for JDK11

### ISSUE THREAD

**Issue by costimuraru** [AdoptOpenJDK/openjdk-website#327]
https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#x64_mac

`export PATH=$PWD/jdk-11+28/Contents/Home/bin:$PATH`
should actually be
`export PATH=$PWD/jdk-11+28/bin:$PATH`

as far as I can tell on my mac.

**Comment by karianna** [comment]
Fixed in #325

**Comment by karianna** [comment]
Sorry, we're releasing a new version where the new PATH will be correct, we did release the site change a little fast.

**Comment by costimuraru** [comment]
Oops, sorry for the duplicate. Keep up the good work!
