### ISSUE TITLE
Display link to JREs in download

### ISSUE THREAD

**Issue by ColinHebert** [AdoptOpenJDK/openjdk-website#331]
Currently we do not display links to the JRE downloads.

The JREs are technically accessible through the API ( https://github.com/AdoptOpenJDK/openjdk11-binaries/blob/master/latest_release.json ), but not from the website.

**Comment by karianna** [comment]
You can now get access to them in the archives.  We do need to think about making it default option alongside the JDK

**Comment by sxa555** [comment]
They are also in the Installation page visible when you click the burger icon in the top top left of the site. I've also also proposing adding it to the main page as part of https://github.com/AdoptOpenJDK/openjdk-website/pull/339#issuecomment-434234799

**Comment by SeanC1083** [comment]
@ddunn2 @karianna @sxa555 I am currently working on some redesigns that include ensuring that users have access to JRE downloads. I will likely share these designs later this week. (Repost from #339)

**Comment by gdams** [comment]
closing as the website now serves both JDK's and JRE's
