### ISSUE TITLE
Help Me Choose link to popup info about both JVMs

### ISSUE THREAD

**Issue by SeanC1083** [AdoptOpenJDK/openjdk-website#336]
![1 1 homepage with jdk info bubble](https://user-images.githubusercontent.com/41338985/46497939-f5cd9b00-c7e9-11e8-854d-f7b412bd23e8.png)

_Originally posted by @SeanC1083 in https://github.com/AdoptOpenJDK/openjdk-website/issues/307#issuecomment-427140786_

**Comment by karianna** [comment]
@SeanC1083 - I'd be happy to look at a PR with just the "Help Me Choose" link and the popover

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-website/issues/301

**Comment by sxa555** [comment]
I commented elsewhere that I quite liked the idea of using radio buttons too, but whether we go for that or not a "Help me choose" would be really helpful - as you can see from the links in my previous comment it does regularly cause confusion!

**Comment by karianna** [comment]
Could do radio buttons but would need to shorten the text above it I think - also need to consider dropping 9 and 10 to a non-LTS page or something like that.  In fact, that might leave us with 4 radio buttons which might be space enough.

Note the JS code isn't as simple as we'd like in this area so changing from a drop down to radio buttons is not as trivial as you'd expect.

**Comment by SeanC1083** [comment]
@karianna When you say shorten the text above it...are you talking about the Welcome text or 'Choose a JDK/Choose a JVM' ? Also, is JDK9 and JDK10 no longer available for HotSpot and Open9?

**Comment by karianna** [comment]
The Welcome text.

Java 9 and 10 are available but are no longer maintained upstream, e.g. no more security patches etc.  So we should really encourage users to use 8 or 11 (which are LTS releases).

So I think we need to have LTS releases on the main index.html page and a separate non-LTS releases page

**Comment by davehobbs** [comment]
JVM is an Oracle trademark. Should the page be using 'Java VM' or at least marking JVM as such?

**Comment by SMadani** [comment]
It would be helpful if there was a delay between hovering over the link and going away from it. The only way to access the links in the popup is to navigate directly across which may be unintuitive or difficult at first. Perhaps make it so that clicking on the underlined "Help me choose" text makes it stay up permanently or until clicking on something else.
