### ISSUE TITLE
Add OpenJ9 version string to OpenJDK11 variant

### ISSUE THREAD

**Issue by Maldivia** [AdoptOpenJDK/openjdk-website#338]
Currently, the [JDK11](https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=openj9) variant of OpenJ9 simply shows `jdk-11+28` as the version string, where as the [JDK10](https://adoptopenjdk.net/index.html?variant=openjdk10&jvmVariant=openj9) page contains the OpenJ9 version as well (shows `jdk-10.0.2+13_openj9-0.9.0`).

Would it be possible to get the OpenJ9 version on the JDK11 variant page?

The version information is in the binary (`java -version` prints out `Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.10.0, JRE 11 ....`), but from the website it's impossible to tell, also knowing that OpenJ9 0.11.0 is coming soon.

**Comment by sxa555** [comment]
Note: jdk8u has the same issue with the 8u192 release

**Comment by karianna** [comment]
This is likely more an issue with the release artifact name (we pass it through).  That said we may add additional logic in the website or API to produce this string.

**Comment by sxa555** [comment]
Yeah I have to admit I'm coming round to the idea of just suffixing the tag name that we pass in with the openj9 version (Since the tag isn't really used as a tag in the openj9 release process)

**Comment by sxa555** [comment]
(I've adjusted the title of this because I keep seeing this issue and panicking that the openj9/JDK11 is missing completely from the web site ;-) )

**Comment by sxa555** [comment]
Extra file name parameter now exposed on the build jobs and the next versions to be released will use this parameter in order to provide the correct extension. Fix to expose the new parameter was in https://github.com/AdoptOpenJDK/openjdk-build/commit/8924f49e5b4cf3a9b8c0d0c5486dc44adce679f1

**Comment by sxa555** [comment]
Current HotSpot builds are named e.g. 
- OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz
Equivalent OpenJ9 without any changes would come out with
- OpenJDK8U-jdk_x64_linux_openj9_8u192b12.tar.gz
Moving `openj9` in there would make the name format inconsistent between openj9 and hotspot which leaves us with two options:
- OpenJDK8U-jdk_x64_linux_openj9_8u192b12.0.11.0.tar.gz
- OpenJDK8U-jdk_x64_linux_openj9_8u192b12_openj9_0.11.0.tar.gz
Unless we do a full rename to
- OpenJDK8U-jdk_x64_linux_8u192b12_hotspot.tar.gz
- OpenJDK8U-jdk_x64_linux_8u192b12_openj9_0.11.0.tar.gz
Also the above only affects the filename, not the release name which it's pushed to (and is the information displayed on the front of the adoptopenjdk.net page) ... If we wanted to have the openJ9 version number on the main page we'd need to put it in a separate release from the HotSpot builds to give it a different name.

For awareness and discussion @pshipton @karianna @johnoliver

**Comment by pshipton** [comment]
I don't think `8u192b12.0.11.0` is a good solution, as this would confuse the OpenJDK release version. I think `openj9_0.11.0` needs to be used. One of:
`OpenJDK8U-jdk_x64_linux_openj9_0.11.0_8u192b12.tar.gz`
`OpenJDK8U-jdk_x64_linux_8u192b12_openj9_0.11.0.tar.gz`

**Comment by sxa555** [comment]
I tentatively agree, but it's a change to the format which also affects hotspot if we move the vm name later than the openjdk version number

**Comment by karianna** [comment]
I think this has now been resolved.
