### ISSUE TITLE
[Request] Access to LocalizeJS.com French

### ISSUE THREAD

**Issue by Mogztter** [AdoptOpenJDK/openjdk-website#346]
Hello,

I've noticed a missing translation and a few errors on the website.
Can I have access to localizejs.com to fix them ?

My email address is ggrossetie (at) gmail {dot} com :wink: 

Thanks,
Guillaume

**Comment by karianna** [comment]
@Mogztter Can you DM me your email address on Slack (adoptopenjdk.net/slack.html) and I'll get you added.

**Comment by karianna** [comment]
We'll look to re-implement internationalization over at Eclipse Adoptium.

**Comment by Mogztter** [comment]
Cool, and congrats on the transition to Eclipse 👍🏻 
I'm involved in another Eclipse project (https://projects.eclipse.org/projects/technology.asciidoc) so we will neighbor 😉
