### ISSUE TITLE
Re-structure of website once more platforms come onboard

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#35]
https://nodejs.org/en/download/ as an example via @gdams

**Comment by Joe-Brady** [comment]
The latest release page, the archive page, and the nightly page are all currently set up to handle Windows as well as Linux and Mac.

The latter will need to be manually changed (see #31 ) following the first Windows build.

The other two pages will automatically show the Windows build.

However, beyond these three operating systems, while the visual appearance of the website will not require too much of a redesign, the JS change is a major undertaking, as I originally designed the website with the expectation that there would only be 3 operating systems.

With these points in mind, what would you like this issue to represent? I.e. the addition of Windows is already covered.

**Comment by Joe-Brady** [comment]
Regarding the reference of Node.js from @gdams, this was already considered at the beginning of the project.

As soon as there is a second release in the 'releases' repo, you will see how the Archive page provides a more condensed version of the 'latest release' information for each release. It's a shame you can't already see it without us creating a 'demo' release!

**Comment by gdams** [comment]
I think that @karianna's concern is more that we are already planning to have linux-x64, linux-s390x, linux-ppc64, win-x64 and macos-x64 releases

**Comment by gdams** [comment]
with so many different architectures, the current 'logo' based system may not work very well

**Comment by karianna** [comment]
@gdams is correct (and also Solaris at some stage).  I'd argue this is a backlog issue until it happens but wanted to give a heads up :-).

**Comment by Joe-Brady** [comment]
This is true - although that kind of visual change is minor compared to the rather enormous task of re-writing the JS to be able to deal with whatever platforms we throw at it.

**Comment by gdams** [comment]
also would be nice to add arm to this

**Comment by Joe-Brady** [comment]
Exactly - there are so many 'it would be nice to add...' that the JS needs to be almost re-written from scratch. Currently, the terms 'linux', 'windows' and 'mac' are hard-coded absolutely everywhere

**Comment by Joe-Brady** [comment]
Just to give you an idea of the scale of this task to incorporate anything new that's not Windows

**Comment by gdams** [comment]
we probably need a re-write of the js at some point as we need to consider architectures as well as multiple file extensions

**Comment by tellison** [comment]
The current site design is great, and provides a good first impression showing what is available in the early days; but I agree that restructuring the js to allow for a growing number of platforms should be considered.  Hopefully that is something you can introduce over time without breaking the existing site.

**Comment by tellison** [comment]
In my simple view of the world, can't we just ...

1. Have a scrollable list of icon blocks on the [releases page](http://adoptopenjdk.net/releases.html).

1. Move the platform information from separate columns into the details line in the [nightly page](http://adoptopenjdk.net/nightly.html), resulting in multiple lines per night to accommodate all platforms.  Then if you want, say, mac builds you would use the "search" box to narrow it down.

I can't remember what the [archive page](http://adoptopenjdk.net/releases.html#archive) looks like now to see what options there are there.

**Comment by Joe-Brady** [comment]
Hi Tim,
First, yep, I agree with everyone that the JS will need restructuring. It's not a short job, but it's necessary.

Second, I like those approaches to the releases and nightly page layouts.

Achieving **1)** would not require any HTML/CSS layout changes - it's already set up to be a grid that would become scrollable with the addition of more platforms. So it's just the JS changes for this one.

Number **2)**  is a nice approach. That would be a relatively simple HTML/CSS change, alongside the JS stuff. And it's a nice solution for the user, with the search box coming in handy as you say.

For the Archive page, the blocks for each release could expand vertically to accommodate more platforms. However, I think you might consider that too chunky, so this page will probably need the biggest change layout-wise.

**Comment by Joe-Brady** [comment]
Complete!
