### ISSUE TITLE
Suggestion: Add release feeds

### ISSUE THREAD

**Issue by redranamber** [AdoptOpenJDK/openjdk-website#350]
It would make it easier to keep updated if your site had rss or atom feeds for each version's releases.

**Comment by supahgreg** [comment]
Looks like GitHub already provides that, although there's some noise from the nightlies.  For example:
* https://github.com/AdoptOpenJDK/openjdk8-binaries/releases.atom
* https://github.com/AdoptOpenJDK/openjdk8-binaries/tags.atom
* https://github.com/AdoptOpenJDK/openjdk8-binaries/commits/master.atom

**Comment by breun** [comment]
I think this issue is a duplicate of https://github.com/AdoptOpenJDK/TSC/issues/33
