### ISSUE TITLE
The link for OpenJDK8 (LTS) is pointing to a JRE

### ISSUE THREAD

**Issue by d-baer** [AdoptOpenJDK/openjdk-website#354]
The Link on 
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot#x64_win
is pointing to 
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jre_x64_windows_hotspot_8u192b12.zip

which is a JRE. Seems to be wrong.

**Comment by karianna** [comment]
Interesting - We probably need to resolve this properly in terms of offering JDK and JRE options.

**Comment by sxa555** [comment]
As it happens I just ran into this issue myself :-), so +1

**Comment by brokenjpl** [comment]
Also getting this issue.

A separate link for JRE and the JDK would be very convenient!

**Comment by karianna** [comment]
Resolved for releases.
