### ISSUE TITLE
Suggestion: Add a message if the latest release is not available

### ISSUE THREAD

**Issue by davehobbs** [AdoptOpenJDK/openjdk-website#355]
* **Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)**:

On macOS x64 the home page has different 'blue buttons' depending on whether Java 8 or Java 11 is chosen:

https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/36768615/48277231-fe953a80-e441-11e8-9c49-877e1b74a5cd.png)

https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/36768615/48277290-24224400-e442-11e8-96d9-863a899dea52.png)

Whilst both buttons are labelled 'Latest release' the OpenJDK 8 button navigates to a 'Latest release' page, whereas the OpenJDK 11 button downloads the latest Java 11 release. The only indication that this may happen are the different icons on each button.

If a download is not available for a particular platform/version  could the page include some text which lets the user know?

**Comment by sxa555** [comment]
As mentioned earlier i think this is a good idea. It's not obvious that the button changes when a suitable direct download is not available and it should be clear to the user what is happening.

**Comment by karianna** [comment]
Fixed
