### ISSUE TITLE
Please add aarch32 builds

### ISSUE THREAD

**Issue by sappling** [AdoptOpenJDK/openjdk-website#356]
* **Browser**:

The Get Involved page has an Available Platforms section that says aarch32/64 are both supported.  I can't seem to find the aarch32 builds and I wasn't sure how to request that the aarch32 builds are added.  This issues system seemed like the best way to communicate this desire.  If I should ask for this in another way, please let me know.

**Comment by sxa555** [comment]
@sappling If you want to try one out have a go with the downloads directly from our jenkins server at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot/ - let us know how you get on :-)

**Comment by sappling** [comment]
We tried using build, but were unsuccessful.  I asked one of our engineers to try this out on both one of our custom ARM7 hardware devices and then on a beagle bone black dev board.  He was unsuccessful running our application, so he tried to compile a simple hello world.  This also failed. The “AOJDK Arm32 Server… .txt” file is a copy of what he did.  The hs_err_pid*.log files are the logs generated during his simple test.

**Comment by sxa555** [comment]
Hmmm the simple `Hello World` works ok on my raspberry pi. I have a BB Black that I haven't used for a while and certainly haven't tried 11 on yet so will try and find some time to test it.

**Comment by mpe85** [comment]
Are there any news on when an 11 aarch32 build will be provided?

**Comment by gdams** [comment]
closing as this seems to be a build issue. Please raise at openjdk-build.
