### ISSUE TITLE
For releases, link to the projects release notes

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-website#362]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

Not sure about OpenJDK, but for OpenJDK+OpenJ9 releases there are release notes. Although users could go hunting to track these down, they would be much easier to find if Adopt linked to the release notes for each release build.

i.e. OpenJ9 0.11.0 [release notes](https://github.com/eclipse/openj9/tree/openj9-0.11.0)

I expect there may also be release notes in the future for the IBM OpenJDK extensions releases that are used to create the OpenJDK+OpenJ9 releases.

At AdoptOpenJDK you can find downloads for the OpenJ9 based binaries for example at https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9

Here we need to add a link to the release notes.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by karianna** [comment]
Done
