### ISSUE TITLE
Missing checksum for OpenJDK8U-jre_x64_linux_openj9_linuxXL_8u192b12_openj9-0.11.0.tar.gz

### ISSUE THREAD

**Issue by io7m** [AdoptOpenJDK/openjdk-website#363]
Browser not relevant; parsed GitHub data directly.

In the `openjdk8-binaries` repos, there is no checksum associated with the `OpenJDK8U-jre_x64_linux_openj9_linuxXL_8u192b12_openj9-0.11.0.tar.gz` or `OpenJDK8U-jre_ppc64_aix_openj9_8u192b12_openj9-0.11.0.tar.gz`.

To reproduce: Open https://raw.githubusercontent.com/AdoptOpenJDK/openjdk8-binaries/master/releases.json, search for either of those strings, and note that there isn't a checksum file associated with either asset.

**Comment by io7m** [comment]
Additionally, some builds specify checksums but those checksums turned out not to be present. For example, the asset for `jdk_x64_linux_openj9_8u192b12_openj9-0.11.0.tar.gz` has an associated checksum file that is supposed to live at:

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12_openj9-0.11.0/OpenJDK8U-jdk_x64_linux_openj9_8u192b12_openj9-0.11.0.tar.gz.sha256.txt

... which gives a `Not Found` error, here.

**Comment by io7m** [comment]
Some similarly broken checksums from the `openjdk11-binaries` repository:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%2B13/OpenJDK11U-jdk_x64_linux_hotspot_11_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%2B13/OpenJDK11U-jre_x64_linux_hotspot_11_13.tar.gz.sha256.txt

**Comment by gdams** [comment]
Is this still an issue? I'm not sure if the releases just got deleted.

**Comment by gdams** [comment]
closing
