### ISSUE TITLE
Provide information on which CVEs impact Adopt builds, and which builds contain the fixes

### ISSUE THREAD

**Issue by paulcheeseman** [AdoptOpenJDK/openjdk-website#366]
This is related to https://github.com/AdoptOpenJDK/openjdk-website/issues/362, but it deserves its own issue.

The AdoptOpenJDK project needs to provide clear, up to date information on which CVEs apply to Adopt builds, and which builds the fixes are included in. This information will differ between major versions and which VM is used.

Adopt builds can be impacted by CVEs in OpenJ9, the extensions, or OpenJDK (am I missing any other components?). I don't think it's sufficient to link to the release notes for the various components (see https://github.com/AdoptOpenJDK/openjdk-website/issues/362) - the Adopt project should collate the information and communicate it clearly in one place.

An example of the sort of wrinkle that can occur is when a CVE is fixed in OpenJDK's HotSpot code. These CVEs are communicated in Oracle's Critical Patch Update release notes, along with affected/fixed version information which can be mapped to OpenJDK. However, consider Adopt builds which combine OpenJDK with OpenJ9 - how does the user know whether the HotSpot CVE is applicable to this build? The answer will not be obvious when reading through each component's release notes, because some HotSpot CVEs also affect OpenJ9, but others do not.

In addition, Oracle's Critical Patch Update release notes often include CVEs which only apply to Oracle's Java binaries - e.g. installer issues, Java Updater issues etc.

**Comment by karianna** [comment]
Agreed - would be nice to find an automated way to pull that list together.  I'll let Natasha know of this issue as well.

**Comment by paulcheeseman** [comment]
@karianna @imifos 

Given that Oracle's January 2019 Critical Patch Update lands tomorrow, I thought I'd just check whether there has been any progress on this.

**Comment by karianna** [comment]
I think we'll manually pull together a list for the next quarterly release.

**Comment by sxa555** [comment]
Added the TSC tag to discuss our plan for this in terms of:

1. Agreeing whether we should have the presence of this document as a gating factor for the release champion to approve
2. Whether we need to host our own copy of any such set of release notes/changelog or link to the upstream project
3. How this will be presented to users on the web page.

**Comment by andrew-m-leonard** [comment]
Given the number of CVE's in a typical CPU is only a handlful, it's not unreasonable to manually put the list together, however the problem with the OpenJDK for Hotspot or OpenJDK Extensions for OpenJ9, is that the OpenJDK community does not publish the list of CVEs contributed as part of a merge of a SVG branch merge. The list of CVEs is only produced for Oracle Java etc.. @paulcheeseman is raising this question with the vulnerability group.

**Comment by karianna** [comment]
I'm working with Red Hat folks on this (OpenJDK upstream) - @andrew-m-leonard LMK if there's an OpenJ9 list I should refer to as well.

**Comment by andrew-m-leonard** [comment]
@pshipton @karianna I can't find the OpenJ9 list, but I thought there is one somewhere for published releases, Peter?

**Comment by paulcheeseman** [comment]
Not a table or list per se, but the information can be found in [OpenJ9's release notes](https://github.com/eclipse/openj9/releases/) - grep for "Security Vulnerabilities Resolved".

**Comment by karianna** [comment]
https://adoptopenjdk.net/release_notes.html - it's not perfect but I'll close this and a new one can be raised to improve the Ux.
