### ISSUE TITLE
AdoptOpenJDK Redesign (NOT VISUAL DESIGN only UX DESIGN) 

### ISSUE THREAD

**Issue by SeanC1083** [AdoptOpenJDK/openjdk-website#368]
Please check out the AdoptOpenJDK Redesign Mockups and share whatever feedback you have! 

<img width="372" alt="screen shot 2018-11-16 at 12 38 14 pm" src="https://user-images.githubusercontent.com/41338985/48638079-998b9880-e99d-11e8-9118-e225ffcf25b9.png">

This mockup is interactive and also include annotations for some aspects of the site. 
https://ibm.invisionapp.com/share/TXNYCWN6WH4

Tips for viewing this prototype:  
Hotspots are enabled if you want to click on the site as you browse the UX to see where clicking a particular button or text will take the user (though some calls to action are not yet available for interaction). If you would prefer to view each page without looking at the interactions, you can use the front and back arrows on your keyboard to navigate.

**Comment by SeanC1083** [comment]
[https://ibm.invisionapp.com/share/TXNYCWN6WH4](url)

**Comment by SeanC1083** [comment]
<img width="372" alt="screen shot 2018-11-16 at 12 38 14 pm" src="https://user-images.githubusercontent.com/41338985/48637714-89bf8480-e99c-11e8-8116-74e63a32a2b2.png">

**Comment by SeanC1083** [comment]
Homepage: 
1. The new home page was designed with the Build Archive page in mind. So any builds that appear on that page will be both the latest and any archive builds that fit the selected JDK, JVM and Platform  criteria. We can continue working on the display so that it makes it more obvious that archive (older) release builds area also being displayed.

Daily Builds: 
1. Thanks for sharing that information! 

2. Thanks for your thoughts. We've discussed the idea of having infinite scrolling on this page and it seems like we might test the idea out to see how the site performs with that design. 

Thanks for Downloading: 
1. Thanks for your feedback. I agree that the current design for that process works well enough. 

2. So, just so I'm clear...you are saying it could like back to the same page that you mentioned in the Daily Builds section about Jenkins details? 

General Feedback: 
1. Thanks for your feedback. Let me provide a little context around the purpose of this new page and how it works. 

**Purpose:**  It was our intent to provide users with a place to re-trigger downloads if that don't start automatically, to reduce redundancy around getting to the  installation process, and to provide other useful tips and info about the JVM/JDK they've just downloaded.

**How it works:**  The 'Thanks for Downloading' page would actually be triggered when users click the download button on either the Release Page (homepage) or the Daily Builds page. So ideally, they download a JDK or a JRE, the download begins and then this page displays. They can then get started with the installation process right way, without clicking another button. They can also click a link and go to the OpenJ9 or HotSpot page or find out about support options. 

2. We had the Checksums info displaying, but we are still trying to find the best place for it. More updates to come soon.

**Comment by karianna** [comment]
OK here goes!  Overall it's a massive improvement, I have lots of small suggestions, I'm afraid it's a mix of Ux and UI comments (sorry, I know Ux/Designers hate that!).

# Home Page

1. _The OpenJDK Revolution_ - There may be Trademark issues around using OpenJDK with that sort of statement.  So I think a slightly different tagline is required, perhaps: _The Adopt*OpenJDK* Revolution_

1. _Choose a JDK Package_ -> _Choose an OpenJDK Package_

1. _JVM_ -> _VM_

1. _JDK_ header -> _Version_

## Download Buttons:

1. Some folks won't know the difference between a JDK and a JRE, I'm almost wondering if that should be an option above-called *Type* with _JDK_ and _JRE_ as the two options and a _Help me choose_ link, like with OpenJ9 vs HotSpot

2. The version number should be the dominant text, with the date and the fact it's HotSpot or OpenJ9 a bit smaller after that.

3. The 2nd button should be JRE as opposed to JDK

4. Once we include installers there may be multiple options for downloading each type of JDK or JRE bundle, I haven't thought about how that might work yet.

5. I think the link to daily builds should be renamed to nightly builds and should not have the same size/weight, it's of lesser importance

# Thanks for downloading

I like the idea. A few small typos and formatting improvements possible, but that's UI not Ux ;-)

# Daily Builds

1. Should probably be called Nightly builds.

1. Not sure what the Jenkins link would lead to, don't think we need it

1. Chances are we'll add more columns, like checksum or metadata (e.g. What host it built on with what parameters etc)

**Comment by SeanC1083** [comment]
Homepage: 
1. Thanks for your feedback. I'm not sure what that text should be but I wanted to suggest that it reworked. 
2. Thanks for your feedback - I like the addition OpenJDK. 
3. Thanks for your feedback. 
4. Thanks for your feedback. I agree that adding version might clarify things a little. 

Download Buttons: 
1. I think we have some design ideas that will better represent what we are proposing here. I am not sure that just using the header to 'Type' will help someone if they don't know the difference. What persona looks for JREs? What information would help them know which to choose? 

2. Based on our research Date helps users determine what is newest so I think that might be the more important criteria. No one mentioned Version number as important.  VM could probably be less dominate, I agree. 

3. I think we have some design ideas that make it easier to access JRE. Will post them soon. 

4. Can you talk a little more about this...I don't know if I understand what you mean. 

5. Weigh and size will be worked out by our visual designer. One of the reasons that Nightly builds was changed to Daily builds came from a conversation with a developer. Nightly builds speaks to when the build, builds. But Daily Builds speaks to the regularity of their occurrence. It is my belief that the former matters more to us, but the latter matters more for users. Some found the term 'nightly builds' confusing. We haven't done a full study of the term Daily Build, but I think it might resonate with other developers as well. 

Thanks for Downloading
1. (Addressed in question 5 above...)

2. Feedback from interviews was that it would be nice if users could view information about a particular build in Jenkins. We can definitely talk more about what information and do some usability tests, but it came up quite a few times. 

3. Is this in reference to the Table View or the Thanks For Downloading page.

**Comment by karianna** [comment]
Hi Sean,

I'll snip bits:

> Download Buttons:
> 
> 1. I think we have some design ideas that will better represent what we are proposing here. I am not sure that just using the header to 'Type' will help someone if they don't know the difference. What persona looks for JREs? What information would help them know which to choose?

A user of Java (not a developer) would typically want the JRE.  E.g. A Minecraft player

> 2. Based on our research Date helps users determine what is newest so I think that might be the more important criteria. No one mentioned Version number as important.  VM could probably be less dominate, I agree.

For nightly builds, I agree date is more important, but for release builds (which only have one date) the version is more important to users.

> 3. I think we have some design ideas that make it easier to access JRE. Will post them soon.
> 4. Can you talk a little more about this...I don't know if I understand what you mean.

At the moment we just offer a zip or tar.gz bundle.  But we are working on native installers for Windows, Mac OS X etc.  For example, MSI, PKG/DMG etc.  So you could imagine that a Mac OS X user could pick between a .tar.gz, a .pkg, a .dmg and so forth.

> 5. Weigh and size will be worked out by our visual designer. One of the reasons that Nightly builds was changed to Daily builds came from a conversation with a developer. Nightly builds speaks to when the build, builds. But Daily Builds speaks to the regularity of their occurrence. It is my belief that the former matters more to us, but the latter matters more for users. Some found the term 'nightly builds' confusing. We haven't done a full study of the term Daily Build, but I think it might resonate with other developers as well.

OK, it's not a biggy, I've just never seen the term daily builds used elsewhere.

> Thanks for Downloading
> 
> 1. (Addressed in question 5 above...)
> 2. Feedback from interviews was that it would be nice if users could view information about a particular build in Jenkins. We can definitely talk more about what information and do some usability tests, but it came up quite a few times.

Yes, we'd like to present metadata to the users, but they shouldn't go to Jenkins for that.  We'll be locking down Jenkins in due course.

> 3. Is this in reference to the Table View or the Thanks For Downloading page?

Good question, perhaps both.  The metadata is things like The host it was built on and which native libraries were used to build it with.

**Comment by SeanC1083** [comment]
Download Buttons:
1. Thanks for your feedback on which type of personas looks for a JRE. 
2. I agree for nightly builds. With Release Builds it is not currently, but we are looking to remove the need for a Archive Builds page (users overwhelmingly found it confusing) and display that information on the homepage. I don't know if you captured that when you reviewed the design mockups - also I didn't see any feedback on the Nightly Build table. 
3. No response needed. 
4. How could we become a part of that conversation to contribute thoughts from a UX perspective? 
5. No response needed. 

Thanks for Downloading
1. No response needed. 
2. Yes, as we have discussed before presenting some metadata would be nice, but we of course need to determine the best metadata to share here. What do you mean by 'locking down Jenkins'? 
3. Okay. Thanks for sharing your thoughts.

**Comment by karianna** [comment]
> Download Buttons:
> 
> 1. Thanks for your feedback on which type of personas looks for a JRE.
> 2. I agree for nightly builds. With Release Builds it is not currently, but we are looking to remove the need for an Archive Builds page (users overwhelmingly found it confusing) and display that information on the homepage. I don't know if you captured that when you reviewed the design mockups - also I didn't see any feedback on the Nightly Build table.
> 3. No response needed.
> 4. How could we become a part of that conversation to contribute thoughts from a UX perspective?

On the #installer channel in slack, we're coordinating work to get the installers in the pipeline.  After that, we'll have a discussion in the #website channel about how we make that available to the end user via the API and the website.

> 5. No response needed.
> 
> Thanks for Downloading
> 
> 1. No response needed.
> 2. Yes, as we have discussed before presenting some metadata would be nice, but we, of course, need to determine the best metadata to share here. What do you mean by 'locking down Jenkins'?

Over time the public won't be able to access Jenkins directly as it's too much of a security risk.  Instead, we will export read-only data (about the builds including metadata) that the public can consume.  This is a little way off though.

> 3. Okay. Thanks for sharing your thoughts.

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
