### ISSUE TITLE
Add an FAQ for AdoptOpenJDK to answer common support questions

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#371]
* GPLv2 and Licensing
* Differences between Adopt and others
*

**Comment by smlambert** [comment]
Security patches, build schedule/timing (goals, how quickly binaries available, etc)

**Comment by sxa555** [comment]
Explanation of OpenJ9 large heap builds e.g. "for >57Gb heaps" (From https://github.com/AdoptOpenJDK/openjdk-build/issues/341)

**Comment by sxa555** [comment]
For reference to anyone finding this work item, the FAQ is at https://adoptopenjdk.net/faq.html
