### ISSUE TITLE
Add supported O/S versions for platforms to download information

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#376]

**Comment by breun** [comment]
I know that the OpenJDK 11 build for Mac doesn't work on OS X 10.7.5. :) 10.10 seems to be the minimum build level.

**Comment by sxa555** [comment]
Related (duplicate?) https://github.com/AdoptOpenJDK/openjdk-website/issues/161

**Comment by sxa555** [comment]
@breun FYI 10.10 is what we build on although I think the 8 binaries worked on earlier versions last time I tried :-)

**Comment by breun** [comment]
Alright, I can't check this myself (I only have macOS 10.14), but it would be nice to know what the minimum required OS version is for each download.

**Comment by karianna** [comment]
Indeed a duplicate.
