### ISSUE TITLE
Google Chrome Tries To Block/Delete Download

### ISSUE THREAD

**Issue by CDBingham** [AdoptOpenJDK/openjdk-website#377]
When I download, 'OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-11.0.1.13_openj9-0.11.0_11.0.1_13.tar.gz' from the adoptopenjdk.net website; Google Chrome tries to block me from opening it and tries to get me to delete it. You can bypass it by opening Downloads and specifically saying you want to keep the file. However, I'm sure this will dissuade quite a few users from keeping the file. I have added some screenshots.

* **Browser**:
Google Chrome - Version 70.0.3538.110 (Official Build) (64-bit)

![screenshot from 2018-11-29 12-12-33](https://user-images.githubusercontent.com/45465610/49241954-51299d00-f3d7-11e8-9512-caf8634bd711.png)

![screenshot from 2018-11-29 12-15-48 2](https://user-images.githubusercontent.com/45465610/49241974-5f77b900-f3d7-11e8-9ec8-8ed667020123.png)

**Comment by karianna** [comment]
@CDBingham can you upgrade/restart chrome and see if the problem clears?  Just reopen if it's still an issue.

**Comment by sxa555** [comment]
Chrome Version 70.0.3538.67 (Official Build) (64-bit) happily downloaded it on my Linux system.

Interesting though ... Thanks for logging in case it's seen again regardless of whether you can reproduce it now!
