### ISSUE TITLE
Logo Change?

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#378]
Hey Everyone, 

So I'm going to tread very carefully here as I know that this may be quite controversial...

 I went to change the logo on [twitter](https://twitter.com/adoptopenjdk) earlier to not be the duke anymore and @karianna told me to change it back to the duke because 

> the Duke has a special meaning to Java developers

Everyone that I have spoken to from outside projects has expressed how pleased they are to not see "dated" java websites that have been dragged out of the 90's. I think that https://adoptopenjdk.net/ is great because it looks like a modern website and it looks like the sort of place that you would expect a good binary to be hosted.

SO...

@Joe-Brady decided to design a new logo (that is already in use on the website) and you can also see it in use on twitter as the cover picture now. The logo looks like this:

![twitter-profile-squares](https://cloud.githubusercontent.com/assets/20224954/25402054/857ce64c-29ef-11e7-9878-da64227e2a50.png)

I propose that we remove the (slightly tired in my opinion) duke and replace it with a new refreshing logo that matches our website.

You can see how much better it looks on twitter here:
<img width="579" alt="screen shot 2017-04-25 at 16 42 42" src="https://cloud.githubusercontent.com/assets/20224954/25402181/dcf51fde-29ef-11e7-832f-9b2168e38fc7.png">

I appreciate that some people may be very fixed on keeping the duke and that's fine but I wanted to get the opinion of everyone in the organization before giving up and throwing the idea away

CC @AdoptOpenJDK/getopenjdk

**Comment by vladimir-dejanovic** [comment]
Hi,

Here are my two cents.

Duke is indeed very special to all Java developers and Java User Groups,
that is why this mascot is always present at events and in logos of
organizations and similar.

Duke is mascot of Java, so for me it would be extremely strange not to have
Duke as part of Adopt Open JDK (Java Development Kit)

Regards
--
Vladimir Dejanovic

**Comment by gdams** [comment]
@karianna please ask your LJC graphics designer to take a look at this one
