### ISSUE TITLE
Update JCK statement

### ISSUE THREAD

**Issue by benelog** [AdoptOpenJDK/openjdk-website#384]
According to https://adoptopenjdk.net/support.html#jck , LJC and Oracle did not agree on using JCK.

> At this stage the London Jamocha Community (LJC) has not been able to reach an agreement with Oracle to use the Java SE Technology Compatibility Kit (TCK) under the terms of the OpenJDK Community TCK License Agreement (OCTLA).

> We will continue to work with Oracle on this matter.

But there is an inconsistent explanation at https://github.com/AdoptOpenJDK/openjdk-tests#jck-tests---compliance-tests

> jck tests - Compliance tests
> TCK tests (under the OpenJDK Community TCK License Agreement), in compliance with the license agreement, are run on a private Jenkins server

Looks like an update is needed at https://adoptopenjdk.net/support.html.

**Comment by smlambert** [comment]
I can update the openjdk-tests documentation to be more clear.  We are leaving in the support to be able to run JCK test material, even though we are not currently running that test material at the AdoptOpenJDK project.  

In the event that those companies or groups with their own OCTLA agreements are using the test automation tooling from AdoptOpenJDK, they can continue to run the JCKs in their own labs and private servers.

**Comment by karianna** [comment]
I'm calling this fixed upstream - @smlambert thank you!
