### ISSUE TITLE
AdoptOpenJDK - Content Evaluation and Re-design

### ISSUE THREAD

**Issue by SeanC1083** [AdoptOpenJDK/openjdk-website#386]
* **Scope of Content Redesign**:
This Git is intended to help facilitate conversations about content udpates/changes to the OpenJ9 Homepage. (Subsequent GitHub issues will be added for each page of the site).  @karianna @sxa555 @gdams

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
