### ISSUE TITLE
Another JDK installation option (OS X)

### ISSUE THREAD

**Issue by 4val0v** [AdoptOpenJDK/openjdk-website#396]
Installation can be made easier.
`tar -xf OpenJDK11U-jdk_x64_mac_hotspot_11.0.2_9.tar.gz`
`sudo mv jdk-11.0.2+9/ /Library/Java/JavaVirtualMachines/`
_and everything, taking into account that jdk was not installed before_
_**Tested on:**_ 10.14.3 (18D42) Mojave

_If it was installed, you can select the desired version as follows:_
`ls /Library/Java/JavaVirtualMachines`
`export JAVA_HOME=$(/usr/libexec/java_home -v <your-jdk-version>)`

Please add it to the installation page

**Comment by breun** [comment]
I would also recommend using `/Library/Java/JavaVirtualMachines` on macOS. This where Apple's Java tools like `/usr/libexec/java_home` look for JDK's and also where the MacPorts ports for AdoptOpenJDK that I maintain install their JDK files.

I think it would be good to mention the option of installing AdoptOpenJDK via a package manager like MacPorts and Homebrew on the macOS installation page.

The installation commands for [MacPorts](https://www.macports.org) users are:

JDK 8 with HotSpot VM:

    sudo port install openjdk8

JDK 8 with Eclipse OpenJ9 VM:

    sudo port install openjdk8-openj9

JDK 11 with HotSpot VM:

    sudo port install openjdk11

JDK 11 with Eclipse OpenJ9 VM:

    sudo port install openjdk11-openj9

**Comment by tresf** [comment]
> If you want to install OpenJDK to `/Library/JavaVirtualMachines/` then I would suggest that you take a look at our brew casks. They automate the above: https://github.com/AdoptOpenJDK/homebrew-openjdk

This assumes Homebrew is used for production machines, but it's often not.  A standard, system-wide installation in the website instructions would make most sense and removes the need to add anything to the `PATH`, as the `Info.plist` will do that portion for you.

I would recommend the wiki is changed to the following:

```bash
sudo mkdir /Library/Java/JavaVirtualMachines/
sudo tar -xf ~/Downloads/openjdk-11.0.2_osx-x64_bin.tar.gz -C /Library/Java/JavaVirtualMachines/
java -version
```

Lower, you may explain that the JDK can be installed locally, (e.g. `~/Applications/JavaVirtualMachines/...`, etc) developers often like this option and providing a default location will help standardize adoption.

Slightly off-topic, but ideally, a `.dmg` or `.pkg` installer would be provided to streamline this for end-users.

**Comment by karianna** [comment]
New instructions at adoptium.net
