### ISSUE TITLE
Missing file name is in OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-11.0.2.9_openj9-0.12.0_11.0.2_9.tar.gz.sha256.txt

### ISSUE THREAD

**Issue by takiguc** [AdoptOpenJDK/openjdk-website#398]
I tried to download "Linux x64 Large Heap" build on jdk 11.0.2+9.
Actual link is as follows:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-11.0.2.9_openj9-0.12.0_11.0.2_9.tar.gz

Downloaded file name was "OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-**11.0.2.9**_openj9-0.12.0_11.0.2_9.tar.gz"

According to Checksum file:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-11.0.2.9_openj9-0.12.0_11.0.2_9.tar.gz.sha256.txt

It said:
f0df1e52458e47319ffed8e43a668d97d728ee8ab0c66992861cbee5b2eaae42  OpenJDK11U-jdk_x64_linux_openj9_linuxXL-jdk-**11.0.2+9**_openj9-0.12.0_11.0.2_9.tar.gz

Download link said "11.0.2.9", Checksum said "11.0.2+9".

It seemed checksum data was same.
File name should be same.
Also I worry about version#, "11.0.2_9" / "11.0.2.9" / "11.0.2+9". Which one is expected ?

**Comment by johnoliver** [comment]
are you sure about those links, none of them seem to work. 
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.2_9-openj9-0.12.0.tar.gz
I believe is the correct link

**Comment by davehobbs** [comment]
@sxa555

**Comment by sxa555** [comment]
They should all be the `_` variant

**Comment by takiguc** [comment]
Many thanks, it worked !

But it seems **jre** side has another issue.

I downloaded new built file via following link:
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#linuxxl

Download link said:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jre_x64_linux_openj9_linuxXL_11.0.2_9-openj9-0.12.0.tar.gz

So download file name may be:
OpenJDK11U-jre_x64_linux_openj9_**linuxXL_11.0.2_9**-openj9-0.12.0.tar.gz

According to checksum file, file name was:
(Link: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jre_x64_linux_openj9_linuxXL_11.0.2_9-openj9-0.12.0.tar.gz.sha256.txt)
target/linux/x64/openj9/OpenJDK11U-jre_x64_linux_openj9_**11.0.2_9_linuxXL**-openj9-0.12.0.tar.gz

Download link said "linuxXL_11.0.2_9", Checksum said "11.0.2_9_linuxXL".
Could you check it again ?

Thanks.

**Comment by takiguc** [comment]
I downloaded the latest builds, there were fine.
Thanks.
But I think file names were longer then expected.
"openj9-0.12.1" was duplicated

OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.0.tar.gz
OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz

**Comment by karianna** [comment]
> I downloaded the latest builds, there were fine.
> Thanks.
> But I think file names were longer then expected.
> "openj9-0.12.1" was duplicated
> 
> OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.0.tar.gz
> OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz

Yes - this is a separate bug being worked on in the openjdk-build repo 884 and 886

**Comment by takiguc** [comment]
Many thanks.
I'll follow the issues:
https://github.com/AdoptOpenJDK/openjdk-build/issues/884
https://github.com/AdoptOpenJDK/openjdk-build/issues/886
