### ISSUE TITLE
Windows installation instruction, usage of unzip

### ISSUE THREAD

**Issue by Maldivia** [AdoptOpenJDK/openjdk-website#400]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

The Windows installation instructions found at https://adoptopenjdk.net/installation.html#x64_win-jdk contains information to use `unzip` to extract the downloaded archive.
Unfortunately, a standard installation of Windows does not contain the `unzip` tool, either need to go through PowerShell (`Expand-Archive`), Windows Explorer or a 3rd party option.

The problem with the above solution is that now:
Step 1 says to start cmd
Step 3 uses PowerShell commands
Step 4 uses cmd commands

If you want to go PowerShell the full way, then Step 4 needs to be something like:
`$Env:path = (Get-Item -Path ".\").FullName + "\jdk8u202-b08\bin;" + $Env:path`

And Step 1 need to be updated accordingly, to mention that you should use PowerShell.

Alternative:
Change step 3 to invoke powershell like:
`powershell -Command Expand-Archive -Path OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip -DestinationPath .`

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by hendrikebbers** [comment]
@Maldivia I edited your issue description to match our template for "good first issue". I will later this week remove your and my comments to have this issue as clear as possible for a newcomer :)

**Comment by hendrikebbers** [comment]
Oh, I just see that a fix was already merged ... @Maldivia should we close this issue?

**Comment by Maldivia** [comment]
@hendrikebbers Hadn't noticed myself that something had been done here.
But step 3 right now is a bit misleading, since the command is a powershell command and the intro text says " use Terminal/Command Prompt ".

But I don't really know how many people are using these instructions anyway; I guess most people choosing to download the .zip file instead of the installer knows how to extract a .zip file.

**Comment by hendrikebbers** [comment]
ok, so the issue will stay open and maybe somebody will provide a small fix for step 3 at hacktoberfest :)

**Comment by Apurwa96** [comment]
Hi, I am an outreachy applicant and first time contributing to Open Source. can I work on this task?

**Comment by smlambert** [comment]
Yes, thanks @Apurwa96 !  If you have questions, please ask them in this issue!

**Comment by Apurwa96** [comment]
Hi, Please review the pull request https://github.com/AdoptOpenJDK/openjdk-website/pull/966 and let me know in case of any changes. :)
