### ISSUE TITLE
Design for new Contribute Page

### ISSUE THREAD

**Issue by SeanC1083** [AdoptOpenJDK/openjdk-website#403]
* **Browser**:

![openjdk developer 1 of 3](https://user-images.githubusercontent.com/41338985/52370597-5cc1c180-2a21-11e9-9b95-3fa3aaa28dad.png)
![web developer 2 of 3](https://user-images.githubusercontent.com/41338985/52370596-5cc1c180-2a21-11e9-9552-10652d3f95d0.png)
![adoptopenjdk contributor 3 of 3](https://user-images.githubusercontent.com/41338985/52370598-5cc1c180-2a21-11e9-9b3a-068ae0342db4.png)

**Comment by karianna** [comment]
I like the direction, I've also realised how out of date our content is!

**Comment by SeanC1083** [comment]
Great. Is there someone that can work with us to get updated content for this page?

**Comment by karianna** [comment]
> Great. Is there someone that can work with us to get updated content for this page?

I'd ask for volunteers in the #website channel on slack

**Comment by SeanC1083** [comment]
Thanks for the suggestion Martijn. I've reached out to the community through the Website channel.

**Comment by ddunn2** [comment]
@SeanC1083 were you successful in finding someone to work on getting this content updated?

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
