### ISSUE TITLE
SSL Configuration Error on blog.adoptopenjdk.net

### ISSUE THREAD

**Issue by deisner** [AdoptOpenJDK/openjdk-website#406]
* **Firefox 65.0** and **Chrome 72.0.3626.96 64-bit** :

It looks like the SSL configuration for https://blog.adoptopenjdk.net/ is broken. When I visit the page I see the following error messages (in Chrome and Firefox, respectively):

![image](https://user-images.githubusercontent.com/742277/52666283-e1a65280-2edb-11e9-9f29-e9be65cc1804.png)

![image](https://user-images.githubusercontent.com/742277/52666308-f2ef5f00-2edb-11e9-8c29-b11a13c82cf9.png)

**Comment by smlambert** [comment]
Yes, in process of moving the wordpress instance over to a different host, and working through some ssl issues, http://blog.adoptopenjdk.net is alive while those issues are being worked out

**Comment by deisner** [comment]
Yep, https://blog.adoptopenjdk.net/ works for me now.
