### ISSUE TITLE
Create a status page status.adoptopenjdk.net

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#408]
We need to have a status.adoptopenjdk.net page hosted on an independent clustered cloud provider (probably AWS across multiple zones) for max reliability and isolation from api / website/ blog.

This status page should be ensuring that our services are up and also report / monitor / alert to our Slack and email when services go down

**Comment by gdams** [comment]
https://www.sorryapp.com/ looks like a good option

**Comment by karianna** [comment]
And we're pretty much up, thanks @gdams - I'll PR in a link to it from our website (yes, yes, the irony if our website is down)
