### ISSUE TITLE
Serve JRE or JDK by default on homepage

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#412]
Do we want to serve JDK's by default on the homepage or switch this to JRE's?

**Comment by karianna** [comment]
I would argue JDKs as JREs will be eliminated at some stage going forwards.  That said, we probably need some user research on this.

**Comment by tresf** [comment]
> I would argue JDKs as JREs will be eliminated at some stage going forwards. That said, we probably need some user research on this.

Agreed.  We're already coding to the JDK now to be able to support JDK 11.  Caveats are:
1. Larger download (minor)
2. Historically, the JDK has installed to a dedicated directory (probably still minor so as long as it can be quickly located by applications which use it)

Some feedback from my side... My Java software has always relied on Java being pre-installed on PCs.  Our product is installed on hundreds of thousands of PCs -- nearly all commercial -- so we're hit hard by the recent changes to Oracle's Java distribution.

To start supporting OpenJDK we now also look for the JDK in our startup script https://github.com/qzind/tray/commit/5b674822b88da9328f52f4579a30c08dad18bfb1.

We haven't fully switched to AdoptOpenJDK.net (we have a commercial Oracle contract) but our clients do not, so we'll eventually have to make recommends to our clients to switch.  I hope this feedback is helpful!

**Comment by tresf** [comment]
As a stop-gap, if the JRE is going away, it may be beneficial to make the JDK installers create the necessary pointers (registry keys, symlinks, `Info.plist`, `update-alternatives`, etc) that the target OS would have historically looked for the JRE under.

**Comment by gdams** [comment]
closing for now, it seems that serving jdk's make sense
