### ISSUE TITLE
Missing link of download stats dashboard

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-website#419]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

The webpage of AdoptOpenJDK (https://adoptopenjdk.net) does not contain any link to the download stats dashboard (https://dash-v2.adoptopenjdk.net). This should be added to the menu.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by gdams** [comment]
we didn't add it to status because it's not something that end users would normally use. As for the dash on the website, it is actually linked on the archive page to allow you to view downloads per release.

**Comment by karianna** [comment]
> we didn't add it to status because it's not something that end users would normally use. As for the dash on the website, it is actually linked on the archive page to allow you to view downloads per release.

Would be interesting to make those both more visible.

**Comment by hendrikebbers** [comment]
@karianna @gdams should we use https://dash-v2.adoptopenjdk.net or https://dash.adoptopenjdk.net ?

**Comment by gdams** [comment]
v2 now, we'd have to find a way to generate the URL with params

**Comment by hendrikebbers** [comment]
I created an additional issue for the status page: https://github.com/AdoptOpenJDK/openjdk-website/issues/816

**Comment by Joyce-O** [comment]
I will work on this issue

**Comment by karianna** [comment]
Not actually useful for end users, so won't implement this.
