### ISSUE TITLE
modify installation page for windows to simplify hash verification

### ISSUE THREAD

**Issue by userquin** [AdoptOpenJDK/openjdk-website#422]
Instead compare visually the hash, just provide a command to verify it (replace `XXXX` with the exe file and `XXXX_HASH` with the SHA256 hash):

```shell
certutil.exe -hashfile XXXX.exe SHA256 2>&1 | find /I "XXXX_HASH">Nul && ( echo "XXXX.exe: The SHA-256 fingerprint matches" ) || ( echo "XXXX.exe: The SHA-256 fingerprint does NOT match" )
```

spanish translation:

```shell
certutil.exe -hashfile XXXX.exe SHA256 2>&1 | find /I "XXXX_HASH">Nul && ( echo "XXXX.exe: La huella SHA-256 coincide" ) || ( echo "XXXX.exe: La huella SHA-256 NO coincide" )
```

**Comment by userquin** [comment]
When selecting windows JRE/JDK on https://adoptopenjdk.net/installation.html

**Comment by karianna** [comment]
Looks good, Pull Request welcome!

**Comment by userquin** [comment]
@karianna I'll take a look to make a PR...

**Comment by userquin** [comment]
@karianna It is posible to request server api to returns the sha256 on the response? If no, then we need to resolve the url and parse the text async 

If the answer is NO,  can I use Promises on the project?:

```javascript
module.exports.loadChecksum = url => {
  return new Promise((resolve, reject) => {
    loadUrl(url, (response) => {
      try {
        resolve(toJson(response));
      } catch (e) {
        reject(e);
      }
    });
  });
}
```

```json
```
![imagen](https://user-images.githubusercontent.com/6311119/54464573-82a45980-4777-11e9-9805-c1398c1e17d5.png)

**Comment by userquin** [comment]
I have a problem with cors requesting sha256.txt file to github, how can I fix it? (installing gulp-connect and add server:test task): i'm not an expert on gulp, normally I work woth webpack:

![imagen](https://user-images.githubusercontent.com/6311119/54468265-21868100-478b-11e9-86c9-dd0138896585.png)

**Comment by userquin** [comment]
I have upload some changes to https://github.com/userquin/openjdk-website:
- config.schema.json: added props for auto command and auto result command (as not required props)
- common.js: added logic to get these 2 props and retrieve sha256 text file from server (parsing it from xhr blob response)
- common.js: modification on loadUrl to allow get blob instead responseText
- installation.js: added logic to handle platform checksum; added listener to platform selector to hide/show checksum auto command container div; added logic to load platform checksum when configured

**Comment by karianna** [comment]
Hi @userquin Can you Pull Request that?  Then I think @gdams or @johnoliver can help with your questions on CORS and the API

**Comment by userquin** [comment]
Hi @karianna: the problem comes from api response to download the sha256 txt file, it do not include the CORS headers so chrome cancels directly the redirect, so it is not a problem with client. Due to the fact that the server api do not include sha256 hash we cannot generate the auto verification command.

I have enable cors on `gulp`, just add `cors: true` on `browser-sync` task:

```diff
gulp.task('browser-sync', () => {
    browserSync.init({
         server: {
             baseDir: './'
         },
+        cors: true,
         notify: false
     });
 });
```

**Comment by karianna** [comment]
OK, create the PR and we can discuss the merits of the approach in that - thank you!

**Comment by userquin** [comment]
PR 422 merged
