### ISSUE TITLE
OpenJDK12+OpenJ9 platforms with installers link to wrong Checksum file

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-website#430]
The Checksum file linked to for OpenJDK12+OpenJ9 for both Windows, MacOS and MacOS XL is incorrect - it links to the checksum file for the installer file rather than the tar.gz file.

See https://adoptopenjdk.net/releases.html?variant=openjdk12&jvmVariant=openj9#x64_win

**Comment by gdams** [comment]
https://github.com/AdoptOpenJDK/openjdk-api/pull/159 will fix the initial issue.

**Comment by gdams** [comment]
@ben-walsh please confirm that this is now fixed?
