### ISSUE TITLE
Add LJC details for Non-Profit behind Adopt

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#440]
* **Browser**:

**Comment by denisedube** [comment]
Hi Martijn, am at the Devoxx session on volunteering to contribute and came across this issue, it is missing information on where to update and what information needs to be added. Keen to do it as a first contrib though.

**Comment by karianna** [comment]
Hi, @denisedube Thanks!

If you fork this repo into https://github.com/denisedube/openjdk-website and then edit the about.handlebars source file that would be a good place to start.

I'll let you draft the text but Adopt is backed by the "London Jamocha Community CIC", which is a non-profit org that runs the London Java Community (LJC).

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
