### ISSUE TITLE
No Windows installer for OpenJDK 11

### ISSUE THREAD

**Issue by beruic** [AdoptOpenJDK/openjdk-website#443]
Is there a good reason why there are no installers available for OpenJDK 11?

It is an LTS version after all.

**Comment by karianna** [comment]
There are installers for the nightly builds and there will be installers for the upcoming 11.0.3 release in just a little over a week.

**Comment by beruic** [comment]
Good. I'm working on moving our entire organization away from Oracle JDK, and an up-to-date installer like this is a good selling point.

**Comment by karianna** [comment]
Cool, see https://adoptopenjdk.net/support.html for Support expectations/options.
