### ISSUE TITLE
HTTPS all the things

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#45]
All of the downloads, website, CI server etc should be SSL'd.  We can investigate something like letsencrypt.org for certificates

**Comment by gdams** [comment]
1. downloads already are https as they are hosted on aws by github
2. website can be set up with ssl but will need to be via cloudlflare - https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
3. CI is already set up (will need to be renewed every 3 months but I have a script that should automatically handle that

**Comment by gdams** [comment]
done
