### ISSUE TITLE
Testimonial Slider Bug

### ISSUE THREAD

**Issue by oliverjnash** [AdoptOpenJDK/openjdk-website#455]
Google Chrome - Version 73.0.3683.103 (Official Build) (64-bit)

The testimonial slider at the top of the testimonials page (https://adoptopenjdk.net/testimonials.html) scrolls sporadically on Chrome (Version 73.0.3683.103) making it difficult to read the testimonials. I've tested on Edge 44.17763.1.0 and IE 11.437.17763.0 and it appears to be working as intended.

**Comment by gdams** [comment]
fixed thanks for the report
