### ISSUE TITLE
Add a banner to the staging site so people know it's staging.

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#46]
It would be nice to add a banner to the staging server website to make it clear that it is for development only, Not sure how it would be best to do this, perhaps inject the html in using the jenkins job? CC @Joe-Brady 
<img width="1440" alt="screen shot 2017-03-24 at 23 52 50" src="https://cloud.githubusercontent.com/assets/20224954/24317233/2b790696-10ed-11e7-8ef2-28857b997f57.png">

**Comment by Joe-Brady** [comment]
Assigning to myself as I'm happy to do the HTML and CSS part of this when I'm in next Tues/Weds/Thurs.

The 'injecting via Jenkins' part isn't something I know how to do yet!

**Comment by gdams** [comment]
complete
