### ISSUE TITLE
Official AdoptOpenJDK icon for kiosks/websites

### ISSUE THREAD

**Issue by grahampugh** [AdoptOpenJDK/openjdk-website#462]
Hi all,

It would be great to have a square-shaped icon for use in “Self Service” kiosks such as Jamf Pro for macOS made available on the Branding page. Right now we are stuck with Oracle’s Java icon.

Cheers
Graham

**Comment by grahampugh** [comment]
Hi @karianna yes that would be easiest. I would think a `.png` of 1024x1024 px with transparent background would be sufficient for most people's needs.

**Comment by karianna** [comment]
Does https://adoptopenjdk.net/logos.html contain what you need?

**Comment by grahampugh** [comment]
Yes that suits my needs. Thank you for a very fast response.
