### ISSUE TITLE
Website does not show OpenJDK 11.0.3 release for ARM platform

### ISSUE THREAD

**Issue by mpe85** [AdoptOpenJDK/openjdk-website#464]
There is now an official release of OpenJDK 11.0.3 for ARM platform.
See https://api.adoptopenjdk.net/v2/info/releases/openjdk11?arch=arm&release=latest
or https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/jdk-11.0.3%2B7

But the web site does not show this release:
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot
ARM binaries aren't shown at all as it seems, not even nightly build.

**Comment by karianna** [comment]
Fixed via #465
