### ISSUE TITLE
Statement about jdk8u212-b04 release for OpenJ9

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-website#475]
I believe Adopt is going to create a Hotspot release build for jdk8u212-b04. The OpenJ9 release will continue to be on b03 as the b04 changes do not affect the OpenJ9 builds. Please make a statement on the website or the release notes that jdk8u212-b04 does not affect OpenJ9.

@sxa555 @andrew-m-leonard

**Comment by gdams** [comment]
@pshipton can this be closed?

**Comment by pshipton** [comment]
Yes, there was a respin of OpenJ9 to include IcedTea-Web, and the respin included b04 (although it doesn't affect OpenJ9) plus other OpenJ9 fixes.
