### ISSUE TITLE
Spanish translation for instalation page (PR 422)

### ISSUE THREAD

**Issue by userquin** [AdoptOpenJDK/openjdk-website#481]
This is not a issue, only spanish translation for instalation page:

Windows:
**ENGLISH**
`Alternative, you can download SHA-256 checksum file and verify downloaded binary using this command (the command must be run using Command Prompt in the same directory you download the binary file and requires PowerShell 3.0+):`
**SPANISH**
`Alternativamente, puede descargar el archivo de suma de comprobación SHA-256 y verificar el binario descargado con este comando (el comando debe ejecutarse utilizando el símbolo del sistema en el mismo directorio en el que ha descargado el archivo binario y requiere PowerShell 3.0+):`

Linux/Mac:
**ENGLISH**
`Alternative, you can download SHA-256 checksum file and verify downloaded binary using this command (the command must be run on a terminal in the same directory you download the binary file):`
**SPANISH**
`Alternativamente, puede descargar el archivo de suma de comprobación SHA-256 y verificar el binario descargado usando este comando (el comando debe ejecutarse en una terminal en el mismo directorio en el que ha descargado el archivo binario):`

Command ouput:
**ENGLISH**
`and confirm the command output succeeds.`
**SPANISH**
`y confirme que la salida del comando tiene éxito.`

Migration guide:
**ENGLISH**
`If you're migrating to AdoptOpenJDK, you can learn about the differences between Oracle JDK and OpenJDK in our Migration Guide and any steps that you might need to take. For example, how to use IcedTea-Web as an alternative to Webstart. `
**SPANISH**
`Si usted está migrando a AdoptOpenJDK, puede conocer las diferencias entre Oracle JDK y OpenJDK en nuestra Guía de Migración y los pasos que debe seguir. Por ejemplo, cómo utilizar IcedTea-Web como alternativa a Webstart.`

The link for `Migration Guide` can be set on `Guía de Migración` text.

**Comment by userquin** [comment]
@karianna translations for spanish, also for migration guide

**Comment by userquin** [comment]
@karianna we also need to translate windows command outputs (linux and mac checksum commands outputs are included on the commands itself), I dont know if those can be translated (we should only change texts at the end of the command):

**ENGLISH**
` ( echo "FILENAME: The SHA-256 fingerprint matches" ) || ( echo "FILENAME: The SHA-256 fingerprint does NOT match" )`
**SPANISH**
` ( echo "FILENAME: La huella SHA-256 coincide" ) || ( echo "FILENAME: La huella SHA-256 NO coincide" )`

Also for spanish translation, uppercase first letter for first instalation text heading on instalation page:

![instalation_head](https://user-images.githubusercontent.com/6311119/57193052-95e1d300-6f37-11e9-82fb-a15e1c7806c3.png)

The text for all plaforms and jre/jdk should start with `Instalación en`.

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
