### ISSUE TITLE
Performance tune the website

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#49]
Website is fronted by Cloudflare (CDN'd) but it could do with some optimisations for the Javascript etc.  Google page speed will probably help.

**Comment by Joe-Brady** [comment]
Just had a look at the network waterfall chart to see if anything was taking too long - looks like the TTFB (Time To First Byte) is by far the longest time spent for each file that needs to be loaded.

This means that the actual size of the files themselves, and the time taken to run the JavaScript etc, is a non-issue (have a look at the tiny blue sections at the end of the green lines - that’s the time taken to actually download each file)

I suspect there are a few different issues that could potentially be causing a wait period: Firstly, I have my suspicions (from past experience that) the HTTPS that we’ve added with Cloudflare could be increasing the TTFB to 388ms.

Secondly, the fact that we are loading a couple of 3rd-party CSS and JS files from the Cloudflare-hosted versions, in attempt to avoid putting them on our own repository - total of about 600ms delay. Thirdly, there is a 128ms wait for the .json file to be loaded from the website-backend repo, but that’s not really long enough to be an issue.

In total, it takes about 1 second to load without a cache - which is pretty quick, but with a reduction in TTFB across the board, it could be quicker

<img width="1440" alt="screen shot 2017-04-05 at 17 29 28" src="https://cloud.githubusercontent.com/assets/20062773/24716437/f3451d62-1a26-11e7-84fa-a0bcd86e0a80.png">
<img width="428" alt="screen shot 2017-04-05 at 17 29 35" src="https://cloud.githubusercontent.com/assets/20062773/24716438/f345ac46-1a26-11e7-8b59-a43a6906eba0.png">

**Comment by Joe-Brady** [comment]
<img width="1440" alt="screen shot 2017-04-24 at 11 33 21" src="https://cloud.githubusercontent.com/assets/20062773/25333411/00fcdb9c-28e2-11e7-832f-cef3350f02c7.png">
<img width="1440" alt="screen shot 2017-04-24 at 11 33 34" src="https://cloud.githubusercontent.com/assets/20062773/25333410/00fccb2a-28e2-11e7-95cf-ba4d86f10db2.png">

**Comment by karianna** [comment]
@Joe-Brady physical location of machines relative to where you are?  Can you get access to the logs on the main site (Apache / NginX)?

**Comment by Joe-Brady** [comment]
@karianna You're probably right - and that might be a question for @gdams ?
To be honest though, in my opinion, and on our admittedly very fast internet connection here, the current loading time isn't an issue really.

Is it still slow for you, Martijn? If yes, could you post a screenshot like mine above? (Just from the Network tab in Chrome's dev tools)

**Comment by karianna** [comment]
My TTFB is usually around 300-350ms

**Comment by karianna** [comment]
<img width="1671" alt="adoptopenjdk_ttfb" src="https://cloud.githubusercontent.com/assets/180840/25337277/25d9bd84-28f3-11e7-96fa-54755a6ca91b.png">

**Comment by Joe-Brady** [comment]
Ok, so it's pretty similar for you... shall I close this issue or do you think it needs some work?

**Comment by karianna** [comment]
I think we can close
