### ISSUE TITLE
Add instructions on how to use PPA/apt repositories on the download page

### ISSUE THREAD

**Issue by mauromol** [AdoptOpenJDK/openjdk-website#494]
Now that https://github.com/AdoptOpenJDK/openjdk-installer/issues/10 and https://github.com/AdoptOpenJDK/openjdk-installer/issues/25 are fixed, I suggest to also add instructions on how to use these at https://adoptopenjdk.net/releases.html for Linux downloads.

**Comment by SueChaplain** [comment]
I'm planning an update to the https://adoptopenjdk.net/installation.html page, so can take care of this.

**Comment by karianna** [comment]
@SueChaplain I've invited you to the team/org so you can self assign.
