### ISSUE TITLE
Create overview page on JDK options

### ISSUE THREAD

**Issue by gunnarmorling** [AdoptOpenJDK/openjdk-website#502]
As discussed with @karianna and others on the Java Champions mailing list, I'd like to suggest to create a page on adoptopenjdk.net, which concisely lists available options for obtaining JDK binaries and all related relevant information (license, support EOL etc.).

This is to address concerns in the Java community about hard to find information on which JDK install options exist. Eventually, this might feed into a page directly providing the different binaries for download, but having just the information available in one place would be a great contribution by AdoptOpenJDK to the Java community at large.

Here's what I have in mind on that so far; It's just a first draft and I'll re-structure/expand that table subsequently (ideally, as a joint effort with other folks here), as more requirements and info on this pops up.

Name | URL | License | Commercially Supported | Version | EOL | Supported Platforms | TCK-certified | JavaFX | Container Image | Notes
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
OpenJDK Upstream | https://adoptopenjdk.net/upstream.html | GNU General Public License, version 2, with the Classpath Exception? | | 11.0.3+7  | | Windows (x86_64), Linux (x86_64, aarch64) | Y | Y | |
AdoptOpenJDK | | | | | | | | | |
Amazon Corretto | | | | | | | | | |
Azul Zulu | | | | | | | | | |
Azul Enterprise | | | | | | | | | |
Oracle JDK | | | | | | | | | |
BellSoft | | | | | | | | | |
SAP? | | | | | | | | | |
IBM | | | | | | | | | |
Others | | | | | | | | | |

Some open questions:

* How to fit versions in there? Might be best to have this table once for each relevant JDK version (8, 11, 12 etc.) to convey exact versions, EOL info.
* How to fit distro-provided packages in?

**Comment by karianna** [comment]
Quick starting comments.  Suggest adding an `AQA Certified` column and an `ITW` column.  Also, change Version column to be Versions

I'd remove Azul Enterprise and change Oracle JDK to Oracle's OpenJDK build

Can also have license changes to GPLv2 and hyperlinked to save space

**Comment by hendrikebbers** [comment]
While I really like the idea I do not think that the issue description is a good place to create the table. I'm not able to modify it / add information. Maybe we can make a simple MD file in the repo and than work with PRs?

**Comment by gunnarmorling** [comment]
> Suggest adding an AQA Certified column and an ITW

What's AQA and ITW? Always loving some TLA :)

> change Oracle JDK to Oracle's OpenJDK build

By the latter, do you mean the GPL build for 12/13? If so, is it really the same? I.e. 100% the same bits, or still slightly different, e.g. vendor identifier etc.?

 > Can also have license changes to GPLv2 and hyperlinked to save space

**Comment by gunnarmorling** [comment]
> the issue description is a good place to create the table. I'm not able to modify it / add information

Ah, yes, agreed. Realizing that now, too. PRs might be a bit heavy at least for the initial information gathering. Perhaps a public Google Doc would do for that initial phase, before moving it over here and continuing with PRs from there on?

**Comment by hendrikebbers** [comment]
+1 for google doc :)

**Comment by gunnarmorling** [comment]
Ok, I've created a document here: https://docs.google.com/spreadsheets/d/1cgUKynjLsncjPoCNTkn-y9fy7_gNXkJtPz0qKANtKiA/edit#gid=0

In order to edit it, log in with Google and request edit rights (I wanted to prevent anonymous edits, and this seems to be the only way to do so).

**Comment by gunnarmorling** [comment]
Ok, figured AQA is "Adopt Quality Assurance". Added a column for that in the Google Doc. On versions I'm swinging forth and back; created three sheets in the doc for now (8, 11, 12), as several columns depend on that (e.g. EOL, link), so it might become unwiedly to have all this in a single table, and having one per major version makes more sense. We'll see :)

**Comment by karianna** [comment]
Marketplace in Adoptium will do this.
