### ISSUE TITLE
Java Web Start not bundled with Windows .msi

### ISSUE THREAD

**Issue by le-jawa** [AdoptOpenJDK/openjdk-website#504]
**Platform: Windows**

**Architecture: x64**

According to your migration guide: "Currently, IcedTea-Web is bundled only with the Windows MSI installer for OpenJDK 8 and 11.", but javaws.exe (maybe other components?) is not included in the x64 MSI installer for 8u212.  Your docuemtnation also says "IcedTea-Web is also available as an optional component of the AdoptOpenJDK installer for Windows that you can select from the Custom Setup panel.", but the option is not there.  Is this a feature that was originally supposed to make it into 212 but didn't, or is it an oversite?
![No javaws](https://user-images.githubusercontent.com/19916394/58586950-3b801d80-822a-11e9-9a66-a4161ec3f0cd.PNG)
![No javaws install option](https://user-images.githubusercontent.com/19916394/58586961-3fac3b00-822a-11e9-9550-4fe54dfcfb48.PNG)

BTW - thanks for setting up that migration guide; that's going to be useful for a lot folks.

**Comment by SueChaplain** [comment]
@karianna - there is a PR waiting to address this - I thought it was already merged. Please can you check and merge: https://github.com/AdoptOpenJDK/openjdk-website/pull/498

**Comment by karianna** [comment]
Just a merge conflict to fix and then it's good to land

**Comment by SueChaplain** [comment]
>You can download it as a separate component from https://adoptopenjdk.net/icedtea-web.html for now though - it's the same build that will be incorporated into the 8u212-b04

FYI: Although it is the same build, there are some differences to the Windows Registry entries that are made by the installers. There are discussions in our slack channel about this and gaps to close.
