### ISSUE TITLE
Quality page JCK / TCK agreement status update

### ISSUE THREAD

**Issue by Mooninaut** [AdoptOpenJDK/openjdk-website#505]
The page https://adoptopenjdk.net/quality.html states 

> Java Compatibility Kit (JCK) / TCK Compliance
> At this stage the London Jamocha Community CIC (aka LJC) has not been able to reach an agreement with Oracle to use the Java SE Technology Compatibility Kit (TCK) under the terms of the OpenJDK Community TCK License Agreement (OCTLA).
> 
> We will continue to work with Oracle on this matter.

However, http://openjdk.java.net/groups/conformance/JckAccess/jck-access.html says "The following organizations and individuals have signed the OpenJDK Community TCK License Agreement (OCTLA) and been granted access to the JCK."

* Signatories for Java SE 9, or later
  * ...
  * London Jamocha Community
  * ...
* Signatories for Java SE 8
  * ...
  * London Jamocha Community
  * ...

These statements seem contradictory.

**Comment by karianna** [comment]
That's a matter for Oracle to resolve on their site.
