### ISSUE TITLE
Install instructions - missing info for java -version check

### ISSUE THREAD

**Issue by spoole167** [AdoptOpenJDK/openjdk-website#51]
I was trying out the adopt website and following the installation  instructions https://adoptopenjdk.net/installation.html

The install worked for me ok  (on mac)  but the final step which says 'run java -version'   doesn't give any info about what the version string should look like to the end user. So if I have another Java installed already I may not be able to spot if anything went wrong with the install.

The other thing I noticed is that there are MD5 checksums available on the website.  It's good practise to provide optional instructions on how to check that your download matches that  checksum

**Comment by Joe-Brady** [comment]
This is a good suggestion.

If you are able to provide improvements to the ` java -version` step and some short MD5 instructions, as you suggest, then we can add it to the website.

**Comment by tellison** [comment]
The `java -version` info is set at the `./configure` stage of the build.  That part of the isse should be raised against openjdk-build.

The MD5 checking (are we really using MD5?!) is described, for example, [here for Linux](https://www.openoffice.org/download/checksums.html#hash_linux), and on the same page for Windows and macOS.

At some point we'll be signing the releases too, and that will require further instruction, but for now stick with hash checks to ensure the download was not corrupted.

**Comment by karianna** [comment]
@tellison - Are you saying we should pull the value from the `java -version` from the configure script dynamically into the website?

**Comment by karianna** [comment]
Agreed on the MD5 checksum - it's known to be broken, move to SHA-2 as a minimum I think (I'll raise an issue on openjdk-build for that).

**Comment by Joe-Brady** [comment]
Aren't we using SHA-256?
(I don't know much about this, but MD5 hadn't been mentioned up until now, only SHA-256)

**Comment by karianna** [comment]
@Joe-Brady Yeah I just checked SHA-256 it is, so we'll write up instructions to checksum that

**Comment by Joe-Brady** [comment]
Checksum instructions added, but please feel free to critique and suggest updates, as I'm probably not the right person to be writing them.

Currently in the process of discussing what to display (and therefore what users should look for) when running `java -version`.

**Comment by Joe-Brady** [comment]
@karianna 
What's the latest on your issue here? https://github.com/AdoptOpenJDK/openjdk-build/issues/93
Any estimate of when I will be able to add the 'what to look for' to `java -version` in the Install instructions?

**Comment by karianna** [comment]
@Joe-Brady I need to figure out where to make that change (Tim mentioned a properties file), will let you know when I've got it!

**Comment by tellison** [comment]
@karianna See my comment on #93

**Comment by karianna** [comment]
Version strings have stabilised

**Comment by hendrikebbers** [comment]
The documentation has changed and do not contain the "java -version" step anymore.
