### ISSUE TITLE
Installation help: Drop unsupported IcedTea for >=9

### ISSUE THREAD

**Issue by adlerweb** [AdoptOpenJDK/openjdk-website#513]
As of https://github.com/AdoptOpenJDK/openjdk-website/pull/498 the possibility to automatically install IcedTeaWeb with AdoptOpenJDK has been dropped for everything but AdoptOpenJDK8. The [Installation instructions for current Versions](https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#windows-msi) still list FeatureIcedTeaWeb/FeatureJNLPFileRunWith as valid MSI parameters on Windows. Using these will lead to errors due to missing installer support. The instructions should hide these options for AdoptOpenJDK >=9 and link to the [manual installation](https://adoptopenjdk.net/icedtea-web.html) for users who still want/need to use Java Web Start.

Ref: https://github.com/AdoptOpenJDK/openjdk-website/blob/f6257d4e9a9997e5bd5eebb31a64941e47bb81e9/src/handlebars/installation.handlebars#L175

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
