### ISSUE TITLE
Question about Server JRE

### ISSUE THREAD

**Issue by userquin** [AdoptOpenJDK/openjdk-website#518]
Hi:

Has Open JDK/JRE something similar to [Server JRE (Java SE Runtime Environment) 8 - Oracle](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiM6KSmn4XjAhXR5-AKHWRKBeQQFjAAegQIABAB&url=https%3A%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fserver-jre8-downloads-2133154.html&usg=AOvVaw03B8PqUzgjJmQ2Ae5IEIbR)

Bye.

**Comment by karianna** [comment]
Yes, you can download JREs from adoptopenjdk.net
