### ISSUE TITLE
Suggestions for wording improvements on website

### ISSUE THREAD

**Issue by spoole167** [AdoptOpenJDK/openjdk-website#53]
On the get involved page 

https://adoptopenjdk.net/getinvolved.html

In the description

**“We provide solidly made binaries to the highest quality possible utilising existing OpenJDK test suites (via jtreg, jcov test coverage) and possibly other OSS donated test suites. However, these binaries are not professionally supported. See Support for details.”**

How about changing  'not professionally supported'  to 'not commercially supported' ?

I think everyone on the project will attempt to do a professional job  so suggesting otherwise is a little off :-)

**Comment by Joe-Brady** [comment]
@tellison @karianna

**Comment by tellison** [comment]
Rewording is fine by me.
