### ISSUE TITLE
Wrong archive size

### ISSUE THREAD

**Issue by XakepSDK** [AdoptOpenJDK/openjdk-website#532]
Website show sizes in Mebibytes, not Megabytes and uses Mega prefix.

Possible solutions:
1. Switch to 10^3, so current prefix will be correct
2. Write MiB instead of MB, then current calculations will be correct

**Comment by gdams** [comment]
This is how we currently work out the size:

```js
size: Math.floor(aReleaseAsset.binary_size / 1024 / 1024),
```

What would you suggest we change to fix this?

**Comment by XakepSDK** [comment]
Change `MB` in interface to `MiB`

**Comment by XakepSDK** [comment]
It looks like this now:
![grafik](https://user-images.githubusercontent.com/4938483/61302501-66700200-a7d5-11e9-870b-30239ce32878.png)
Should look like this:
![grafik](https://user-images.githubusercontent.com/4938483/61302539-7851a500-a7d5-11e9-862a-92d4cfac9f55.png)

**Comment by karianna** [comment]
Whilst a more accurate notation, I'm not convinced our audience will appreciate the difference.
