### ISSUE TITLE
Website is showing wrong versions

### ISSUE THREAD

**Issue by exabrial** [AdoptOpenJDK/openjdk-website#537]
The website is showing last year's release, not the most current.

![Screen Shot 2019-07-18 at 1 21 37 PM](https://user-images.githubusercontent.com/1392297/61481994-29377b80-a95f-11e9-947f-a15ebab1f688.png)

**Comment by ParkerM** [comment]
Which OS/Arch did you have selected here? (or did the issue occur for all of them?)

**Comment by karianna** [comment]
Suspect that's a caching issue - I can't seem to reproduce that.

**Comment by exabrial** [comment]
Well now it's working correctly! No change on my side
