### ISSUE TITLE
v11 of Mac OS X download fails

### ISSUE THREAD

**Issue by RangaSamudrala** [AdoptOpenJDK/openjdk-website#545]
**Platform:**
Mac OS X
**Architecture:**
x86_64

Every time I try to download installer pkg file, the download stops at 58MB and fails.

**Comment by karianna** [comment]
Both OpenJ9 and Hotspot download fine for me (Mac OS X 10.14.6).  Can you try with an alternative browser or after a restart?

**Comment by RangaSamudrala** [comment]
It seemed to be an issue with my company's VPN. I logged out of the VPN and I was able to download.

This issue can be closed.

thanks

**Comment by RangaSamudrala** [comment]
Issue related to VPN connection.
