### ISSUE TITLE
Add organizational info to the "About" page

### ISSUE THREAD

**Issue by beruic** [AdoptOpenJDK/openjdk-website#550]
I am currently writing a bunch of documents about third parties we interact with in our company. We develop a lot of software for JVM, and thus I need to write something about AdoptOpenJDK.

I am however having a hard time figuring out which legal entity is behind AdoptOpenJDK. For now I have assumed that the legal entity is the _AdoptOpenJDK Community_, but I am in doubt. Especially because I cannot find any address or other organizational information on it.

It would be nice if this information could be added to https://adoptopenjdk.net/about.html

**Comment by karianna** [comment]
The legal entity is the "The London Jamocha Community Interest Company" - that is, the nonprofit that is behind the London Java User Group.

**Comment by beruic** [comment]
...which is then in turn the main stakeholder of AdoptOpenJDK?

Is that how I am to understand it @karianna ?

**Comment by karianna** [comment]
> ...which is then in turn the main stakeholder of AdoptOpenJDK?
> 
> Is that how I am to understand it @karianna ?

Not quite - the legal entity in the LJC who is certainly a large stakeholder.  I'd argue that:

IBM, jClarity, Red Hat, Karakun, Pivotal, Microsoft, Azul, Amazon are also large stakeholders.  See our adoptpenjdk.net/sponsors.html and TSC repo for influencers.

**Comment by beruic** [comment]
Yes, but wouldn't you agree that all those stakeholders are organized through the LJC?

The main point here is that I need a single entity to refer to, in stead of refering to "The AdoptOpenJDK Community".

**Comment by karianna** [comment]
The London Java Community would be it in that case.

**Comment by beruic** [comment]
Ok, I will use that then. Thank you. Sorry for the late answer.

By the way, I cannot find a physical address on http://londonjavacommunity.co.uk/about-us/, which would be nice, but for now, the city and country will do.

**Comment by akdsco** [comment]
Hi, @karianna let me know if you need to update the website with new info, I'd be happy to help :)

**Comment by akdsco** [comment]
Done. SSL is in the making.

**Comment by akdsco** [comment]
Ok, you can consider it done @karianna
SSL is working. I even managed to get the event timeline automatically display the next coming event.
The site is kind of slow, I'll investigate this but that's a different issue.

**Comment by karianna** [comment]
> Ok, you can consider it done on LJC website @karianna SSL is working.
> I even managed to get the event timeline automatically display the next coming event while working on SSL.
> The site is kind of slow, I'll investigate this but that's a different issue.
> 
> Should I assume you'd like to add the company details in https://adoptopenjdk.net/about.html as well?

That would be good yes or perhaps a link to the LJC website.

**Comment by akdsco** [comment]
Ok, if we'd like to add a link to LJC, then it would be good to settle on some sort of wording for it that fits best.
What I thought of doing is adding a paragraph to `Who's behind the AdoptOpenJDK.net Community?` section.

Maybe something like:

> AdoptOpenJDK is one of the projects created and run by the <a href="#">London Java Community</a>.

Then if anyone goes onto the LJC page, they should be able to find the official address in the footer.

**Comment by karianna** [comment]
> Ok, if we'd like to add a link to LJC, then it would be good to settle on some sort of wording for it that fits best.
> What I thought of doing is adding a paragraph to `Who's behind the AdoptOpenJDK.net Community?` section.
> 
> Maybe something like:
> 
> > AdoptOpenJDK is one of the projects created and run by the [London Java Community](#).
> 
> Then if anyone goes onto the LJC page, they should be able to find the official address in the footer.

Apologies, I was away on leave.  

That sounds find although the wording should be something more like:

> > AdoptOpenJDK is one of several community projects co-created by the [London Java Community](#).

**Comment by akdsco** [comment]
Ok perfect, I've created a pull request #788

**Comment by karianna** [comment]
That's all Eclipse Foundation now.
