### ISSUE TITLE
Adjust sponsorship text for Packet / Works on Arm for aarch64 (arm64) support

### ISSUE THREAD

**Issue by vielmetti** [AdoptOpenJDK/openjdk-website#562]
As part of the 2019-2020 Works on Arm project year, we're looking through all of the sponsored projects to identify how the sponsorship contributions are credited and to make this all consistent.

I'll sync up with @gdams to make sure that the source text at https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/handlebars/sponsors.handlebars accurately reflects current reality. I don't have updated text yet.

**Comment by vielmetti** [comment]
hey @gdams I have this in mind at the moment; would love to sync up with you regarding it.

**Comment by gdams** [comment]
hi @vielmetti! Sorry this slipped right past me! Drop me a message on slack when you're around and we'll work out a time to do this!

**Comment by vielmetti** [comment]
@gdams I am on Pacific Time this week, trying to stick to Eastern Time hours. Will ping in the a.m.

**Comment by vielmetti** [comment]
Best to plan this for next week as Arm TechCon conference travel (and announcements, including a bunch of CI-related announcements) have me fully committed for this week.

**Comment by vielmetti** [comment]
Thanks for tracking this, @karianna and @gdams . Since I last corresponded, Packet has a new logo as a consequence of our acquisition by Equinix. Looking forward to getting this sorted; you can let me know what assets we need to update.

**Comment by gdams** [comment]
Hi Ed, I'll try and get the new logo added this week!

**Comment by gdams** [comment]
@vielmetti logo updated here: https://github.com/AdoptOpenJDK/openjdk-website/pull/701

**Comment by vielmetti** [comment]
New text as well (reflecting acquisition) @gdams @karianna 

Packet, an Equinix company, is the leader in automated bare metal. We focus on making infrastructure a competitive advantage for digital businesses with developer-friendly bare metal and a neutral, secure, interconnected ecosystem of networks, software, and solution partners.

Packet combines unmatched geographic reach, interconnection prowess, and a neutral ecosystem approach with automation to create a trusted, friction-free customer experience. Our mission is to protect, connect, and power the digital world with physical infrastructure that moves at software speed.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/pull/705
