### ISSUE TITLE
Add information about installed "alternatives" for Linux RPM/DEB

### ISSUE THREAD

**Issue by ggam** [AdoptOpenJDK/openjdk-website#566]
This is related to https://github.com/AdoptOpenJDK/openjdk-installer/issues/161. I had a hard time finding how to use `javadoc` and `jlink` alternatives from AdoptOpenJDK. In the end, the problem was my lack of knowledge about what the `javac` alternative was about (all development tools and not just the `javac` command).

I doubt I'm the only one that has faced that problem, so I think it would be good to explain the `alternatives` installed on the Installation page. A few lines are enough given the behavior is pretty standard and in line with what the distros already do.

**Comment by karianna** [comment]
New instructions at Adoptium
