### ISSUE TITLE
Add website for JMC

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/openjdk-website#582]
It would be wonderful to have a website for AdoptOpenJDK builds of JMC.

Some relevant graphics that could be used can perhaps be found here:
http://hg.openjdk.java.net/jmc/jmc-graphics/

The site should probably have nice links to released versions of JMC as well as snapshot builds, as well as to the update sites. 

The builds can currently be found here:
https://ci.adoptopenjdk.net/view/JMC/job/jmc-latest/

The update sites could perhaps be unpacked and hosted directly on the site, under:
https://adoptopenjdk.net/jmc/updatesite/<version>/rcp
https://adoptopenjdk.net/jmc/updatesite/<version>/ide
for releases, and:
https://adoptopenjdk.net/jmc/updatesite/latest/rcp
https://adoptopenjdk.net/jmc/updatesite/latest/ide
for the latest EA builds.

(Here are update site examples from Oracle:
https://download.oracle.com/technology/products/missioncontrol/updatesites/base/6.0.0/eclipse/
https://download.oracle.com/technology/products/missioncontrol/updatesites/base/6.0.0/rcp/

Here are rcp application download examples from Azul:
https://www.azul.com/products/zulu-mission-control/

And from Bell-Soft:
https://bell-sw.com/pages/lmc/
)

**Comment by hendrikebbers** [comment]
I can give it a try :)

**Comment by karianna** [comment]
Cool, look to the iced tea web page as an example :-)

**Comment by reinhapa** [comment]
@hendrikebbers if I need to change something on the build side ot things let me know...

**Comment by hendrikebbers** [comment]
@reinhapa It looks good. Got it running on my machine and already see the new page in localhost :) Will create the content the next days.

**Comment by thegreystone** [comment]
This is great! When we know the final URL of the update sites, we should override the jmc/application/org.openjdk.jmc.rcp.application/src/main/resources/updatesites.properties to point to the published update sites in both jmc7 (JMC 7.0.0) and jmc (JMC 7.1.0 EA) and respin. That way the RCP applications will find them too.

**Comment by thegreystone** [comment]
Cool! A small typo: helpfull -> helpful

**Comment by hendrikebbers** [comment]
Done :)

**Comment by thegreystone** [comment]
For the RCP and Eclipse update sites to be usable, they must be unpacked somewhere. See https://download.oracle.com/technology/products/missioncontrol/updatesites/base/6.0.0/eclipse/
https://download.oracle.com/technology/products/missioncontrol/updatesites/base/6.0.0/rcp/

Or, for that matter, https://download.eclipse.org/eclipse/updates/4.11/

**Comment by reinhapa** [comment]
Also I think the actual `index.hml` needs a AdoptOpenJDK update somehow...

**Comment by thegreystone** [comment]
Yep, it's pretty neutral, but adopt-izing the update sites may be a good idea.

**Comment by hendrikebbers** [comment]
@reinhapa what do you mean?

**Comment by hendrikebbers** [comment]
ah, the index of the plugins. Got it ;)

**Comment by reinhapa** [comment]
@thegreystone do you think we can have a accordingly tweaked `stylesheet.css` somewhere?

**Comment by thegreystone** [comment]
Sure, you can just override the stylesheet during the build, just like you will override the jmc/application/org.openjdk.jmc.rcp.application/src/main/resources/updatesites.properties.

**Comment by reinhapa** [comment]
@hendrikebbers is there a way to upload/update the update site content dynamically? pushing by the build job or using a webhook to trigger an update?

**Comment by hendrikebbers** [comment]
I don't know. Never used handlebars.js before.

**Comment by thegreystone** [comment]
Maybe we can publish only the release update sites for now, manually?

**Comment by thegreystone** [comment]
Back from vacation! :) Is there anything I can do to help this move along?

**Comment by hendrikebbers** [comment]
From my point of view the PR can be merged (cc @karianna). Any other improvement can than be done based on this version. It do I miss something?

**Comment by thegreystone** [comment]
It's called JDK Mission Control. It was changed before open sourcing so that there wouldn't be any copyright problems.

**Comment by thegreystone** [comment]
Hi all! Anything I can do to help conclude this? It's so very close. :)
