### ISSUE TITLE
Instructions for removing framework from /System/Library/Frameworks/JavaVM.framework/ 

### ISSUE THREAD

**Issue by brandelune** [AdoptOpenJDK/openjdk-website#593]
The instructions to install AdoptOpenJDK are clear enough but there is nowhere instructions to uninstall the package.

**Comment by mrkapqa** [comment]
Please add an .uninstaller .pkg

**Comment by ellschi** [comment]
I claim this issue as mine! Does this mean that I am assigned automatically or do I need to get in touch with someone about that?

**Comment by ellschi** [comment]
Great! Thanks so much

Martijn Verburg ***@***.***> schrieb am Mi., 31. März 2021,
19:45:

**Comment by ellschi** [comment]
So, I have a collection of first questions - do I post them here or should I contact someone (@karianna?) directly about that?

**Comment by aahlenst** [comment]
Please ask questions here. This allows us to go back and see how something came together.

**Comment by ellschi** [comment]
Sooo, here go my questions:
If I get it right, to solve this issue, I would have to 
a) add an .uninstaller .pkg to this [code ](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-frontend/src/main/resources/JSON/platforms.json) and
b) add a description how to use it to this [website](https://adoptopenjdk.net/index.html).
Is this right so far?

If it is, I need directions for adding the uninstaller. Can I use the [installer](https://api.adoptopenjdk.net/swagger-ui/#/Installer/get_v3_installer_latest__feature_version___release_type___os___arch___image_type___jvm_impl___heap_size___vendor_) as a template? If not where do I get a template from?

My last question is where I will add the How To for using the uninstaller.

Thank you for answering this in advance!

**Comment by karianna** [comment]
I'd recommend trialing the steps in answer to https://stackoverflow.com/questions/25925752/uninstall-packages-in-mac-os-x - if that works for uninstalling our installer then I think you can write up those instructions.  I'm going to assume it's a 1-2 line command so I'm hoping we won't need to create an uninstaller.

**Comment by ellschi** [comment]
Oh, was this issue meant for mac os only? I can't test that, I'm so sorry!

**Comment by karianna** [comment]
It is Mac only, no worries, I'll unassign you.

**Comment by karianna** [comment]
Closing this as no longer needed (most folks have moved off AdoptOpenJDK some time ago).
