### ISSUE TITLE
JMC update site should be linked to

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/openjdk-website#594]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

On the website the Eclipse Update Site should be linked to, rather than the zip used:
https://adoptopenjdk.jfrog.io/adoptopenjdk/p2-jmc-snapshots/ide

Good URLs for the update sites:
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/7.0.0/ide/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/7.0.0/rcp/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/latest/ide/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/latest/rcp/

Also, in the landing page for the update site, the zip-archive should be linked to:
https://ci.adoptopenjdk.net/view/JMC/job/jmc-latest/lastSuccessfulBuild/artifact/application/org.openjdk.jmc.updatesite.ide/target/org.openjdk.jmc.updatesite.ide-7.1.0-SNAPSHOT.zip

These are the snapshot builds, and they should be clearly marked as such. It would be good to have the release versions available too.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by thegreystone** [comment]
I opened a separate Issue (#595) for the release builds, as this needs to be decided and fixed first.

**Comment by thegreystone** [comment]
Also, the RCP update site should not be linked to - it's something that is only used by the RCP application internally. No need to link to it explicitly.

**Comment by thegreystone** [comment]
The RCP update site is already removed. As soon as we have finalized the update site URLs, I'll fix this.

**Comment by thegreystone** [comment]
Good URLs for the update sites:
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/7.0.0/ide/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/7.0.0/rcp/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/latest/ide/
https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc/updatesite/latest/rcp/

**Comment by jwnmoon** [comment]
Hi, I'll start working on this issue! :)

**Comment by Apurwa96** [comment]
Hi, I have never contributed to Open Source before and would like to start with this task.

**Comment by aahlenst** [comment]
@jwnmoon @Apurwa96 Thanks a lot, but we haven't noticed that this task isn't ready for anyone to work on (totally our fault). Please pick something else.

@thegreystone @reinhapa I close this issue. You're now publishing to GitHub and Artifactory was never fit for the purpose. We should work out the distribution story at Eclipse. Please create a new ticket in the JMC repo, state your requirements and tag me.
