### ISSUE TITLE
Improve content for CONTRIBUTING.md

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#6]

**Comment by gdams** [comment]
@karianna are there any defined contributing guidelines for this organization?

**Comment by karianna** [comment]
@gdams Not at this stage no and I think we'd want to set our own guidelines for this openjdk build sub effort, so feel free to add something to start with and we can discuss and refine on the mailing list

**Comment by adoptopenjdk-admin** [comment]
Include a link to the new Jenkins farm (when DNS'd to ci.adoptopenjdk.net)

**Comment by karianna** [comment]
@Joe-Brady has pretty much nailed this.
