### ISSUE TITLE
Incorporate a 'std' browser and O/S detection lib so users are presented with the best download

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#60]

**Comment by Joe-Brady** [comment]
https://github.com/bestiejs/platform.js/
Perhaps?

**Comment by karianna** [comment]
Looks reasonable yeah.

**Comment by gdams** [comment]
This looks good, how are we serving Linux users at the moment? Do we ensure that they are all x64 users or can we differentiate s390x and ppc64le?

**Comment by karianna** [comment]
I'm honestly not sure how many folks would be using a s390 or ppc64le desktop / browser.  Would be cool if this lib detects that but probably not the worst thing in the world if it defaults to x64

**Comment by Joe-Brady** [comment]
The library can detect 64 and 32 bit, any of these operating systems, and the OS version.
I'm not sure it can detect the difference between x64/s390/ppc64le.
I'm currently implementing this detection library on the basis of what @karianna said (luckily), where any Linux-based OS shows the x64 download on the homepage.
  
    'Windows Phone',
      'Android',
      'CentOS',
      { 'label': 'Chrome OS', 'pattern': 'CrOS' },
      'Debian',
      'Fedora',
      'FreeBSD',
      'Gentoo',
      'Haiku',
      'Kubuntu',
      'Linux Mint',
      'OpenBSD',
      'Red Hat',
      'SuSE',
      'Ubuntu',
      'Xubuntu',
      'Cygwin',
      'Symbian OS',
      'hpwOS',
      'webOS ',
      'webOS',
      'Tablet OS',
      'Tizen',
      'Linux',
      'Mac OS X',
      'Macintosh',
      'Mac',
      'Windows 98;',
      'Windows '
