### ISSUE TITLE
x86 linux builds?

### ISSUE THREAD

**Issue by alexkoster** [AdoptOpenJDK/openjdk-website#602]
* **Browser**:

Great effort and project!  Is it possible to add x86/i386/i486/i586/i686/32-bit/ia32 32-bit x86 Linux builds?

**Comment by karianna** [comment]
Duplicate of the request in the openjdk-build repo.  FYI - We've not found volunteers to work on this yet.

**Comment by alexkoster** [comment]
Thanks @karianna I now see multiple issues and will follow and comment on the https://github.com/ojdkbuild/ojdkbuild repository.  My apologies for posting in the wrong repo.

**Comment by karianna** [comment]
@alexkoster that should be github.com/adoptopenjdk/openjdk-build for our binaries
