### ISSUE TITLE
JDK11/J9/macos large heap builds not labelled on website

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#603]
We seem to be producing two nightly macos builds, one of which is probably the large heap / XL version, but they are not labelled as such.

**Comment by ParkerM** [comment]
I think this may have already been fixed on the front-end at some point. The current macOS builds appear to be labeled correctly as "macOS x64" and "macOS x64 Large Heap" (see [here](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9)), and links appear to point to the correct artifacts.
