### ISSUE TITLE
Release Notes Paged Per version

### ISSUE THREAD

**Issue by jgkirschbaum** [AdoptOpenJDK/openjdk-website#604]
I think it would be a good idea to append release notes to the releases. Today, I don't know the difference between

- AdoptOpenJDK jdk-11.0.2+7
- AdoptOpenJDK jdk-11.0.2+9

The release notes should be noted in the https://github.com/AdoptOpenJDK/openjdk11-binaries repository.

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
