### ISSUE TITLE
x32 is not what Windows Intel 32-bit is using

### ISSUE THREAD

**Issue by PerMildner** [AdoptOpenJDK/openjdk-website#605]
Your [download pages](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot#x32_win) has links to installers for Windows x32, but "x32" has a [well defined meaning](https://en.wikipedia.org/wiki/X32_ABI) and is not related to what Windows is using.

**Comment by gdams** [comment]
@PerMildner thanks for your issue! Do I understand correctly that you want us to rename `Windows x32` to `Windows x86-64`?

**Comment by PerMildner** [comment]
I do not know what a suitable name is (perhaps whatever Oracle uses?). I just know that "x32" definitely is the wrong name.
