### ISSUE TITLE
Bug? Download page links to the JRE version

### ISSUE THREAD

**Issue by ijean** [AdoptOpenJDK/openjdk-website#611]
It seems that the download page from the AdoptOpenJDK webpage links to the JRE version of the installer instead of the full JDK. The button label claims that you download the JDK version but you get only the JRE.

I've checked this for both the Windows and macOS installers, in both cases the JRE is downloaded.

**Comment by gdams** [comment]
Thanks for the bug report! Fixed in https://github.com/AdoptOpenJDK/openjdk-website/pull/612
