### ISSUE TITLE
feature request: msi option do install only JRE

### ISSUE THREAD

**Issue by warichnict** [AdoptOpenJDK/openjdk-website#621]
hi,
this is not a report for the website but for your msi, i couldnt find the repository of it.

following feature i would like tor request:
![image](https://user-images.githubusercontent.com/57467778/69081110-3c557780-0a35-11ea-9fac-1b4e3045e75b.png)
as you can see the option to install is only if you want to enable it into path, file association and so on, but not what to install.

I know todays harddrives are big but on my server is only a 20GB SSD which makes me count any 100 mb, so could you add an option to install only the JRE without the JDK, maybe also through a special JRE only MSI embedded into the main msi (or for seperate download ) like sun did it and oracle just changed the name.

thanks a lot in advance

thanks for keeping java running even if oracle is a bitch, keep up the good work!

**Comment by aahlenst** [comment]
There is a MSI JRE on https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.5_10.msi

Or did I misunderstand?
