### ISSUE TITLE
Inconsistent experience between "Latest/archive/nightly" navigation

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#641]
Semi-related to https://github.com/AdoptOpenJDK/openjdk-website/issues/629 the navigation between "Release Archive", "Nightlies" and "latest" release is not intuative.
- The text at the top of the page tells you which page you are one
- Underneath that there are two buttons to switch to the other two pages
- The one on the left is shown in blue, the right one in grey (bear in mind neither are "active" so why are they different colours?) and since they move around depending on what's clicked it leads to confusion

Perhaps it would be preferable to have three buttons or tabs to make it clear how to navigate and which page you are on. Here are the three pages:

![image](https://user-images.githubusercontent.com/6487691/71588821-ce639c00-2b1a-11ea-8d1d-78629709cbd3.png)
![image](https://user-images.githubusercontent.com/6487691/71588824-d02d5f80-2b1a-11ea-86b1-612597dc47eb.png)
![image](https://user-images.githubusercontent.com/6487691/71588827-d28fb980-2b1a-11ea-9b19-5918d81c3cbf.png)

**Comment by sxa555** [comment]
Also the banner on the archive page means that the two buttons move to a different place on the screen on that page so perhaps should be moved to underneath the buttons

**Comment by karianna** [comment]
We're working on the new website at Adoptium.net
