### ISSUE TITLE
Meeting diary link broken

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-website#643]
* **Browser**: Firefox and Edge

The meeting diary link returns a 502 message. 

https://calendar.adoptopenjdk.net/

I'm told this should be fixed by logging into google in another tab, but that doesn't solve the problem.

Issue 1: The link doesn't work.

Issue 2: Even when the link did work, requiring you to be logged into google is something that people should be informed of. (Perhaps a url return code check, paired with a minimalist alt-text telling people about the google thing?)

**Comment by iemejia** [comment]
+1 still broken

**Comment by tellison** [comment]
Still have a "Meeting diary" link near the bottom of the home page.
