### ISSUE TITLE
Multiple pages using the "support" class

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#645]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

Several handlebar files use the `support` CSS class. We should probably clear this up a bit. Either rename the class from `support` or use individual ones for each page so the names look appropriate on each page:
```
faq.handlebars:  <div class="align-left support">
installation.handlebars:  <div class="align-left support">
installation.handlebars:  <div class="align-left support">
migration.handlebars:  <div class="align-left support">
quality.handlebars:  <div class="align-left support">
release_notes.handlebars:  <div class="align-left support">
supported_platforms.handlebars:  <div class="align-left support">
support.handlebars:  <div class="align-left support">
support.handlebars~:  <div class="align-left support">
```

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by brngylni** [comment]
Can I give it a try?

**Comment by vanichitkara** [comment]
I'd love to work on this issue and it would be my first time to make a PR in such a  big project so I'd be really glad if I could get the chance to work on this!

**Comment by smlambert** [comment]
Looks like 3 people want this one, @brngylni - you claimed it first, so go for it!  

@SondosAhmed and @vanichitkara - can you please select different ones from the Good First Issues list?

**Comment by brngylni** [comment]
> Looks like 3 people want this one, @brngylni - you claimed it first, so go for it!  
> 
> @SondosAhmed and @vanichitkara - can you please select different ones from the Good First Issues list?

Thanks. By the way can I get a bit more information about the task?
