### ISSUE TITLE
What links should be on the footer of each page?

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#646]
Mostly driven by a desire to determine where the FAQ should be linked, On the front page we have:

*On the bottom with arrows:*
- [Installation](https://adoptopenjdk.net/installation.html)
- [Migration](https://adoptopenjdk.net/migration.html)
- [Support](https://adoptopenjdk.net/support.html)
- [Get Involved](https://adoptopenjdk.net/getinvolved.html)

*Other links underneath:*
- [About](https://adoptopenjdk.net/about.html)
- [Sponsors](https://adoptopenjdk.net/sponsors.html)
- [Testimonials](https://adoptopenjdk.net/testimonials.html)
- [API](https://api.adoptopenjdk.net/)
- [Blog](https://blog.adoptopenjdk.net/)
- [Meeting diary](https://calendar.adoptopenjdk.net/) - Currently not openly accessible
- [Status](https://status.adoptopenjdk.net/)

*Top left "burger" icon:*
- [Latest release](https://adoptopenjdk.net/releases.html)
- [Build archive](https://adoptopenjdk.net/archive.html)
- [Nightly builds](https://adoptopenjdk.net/nightly.html)
- [Installation](https://adoptopenjdk.net/installation.html)
- Projects -> [IcedTea-Web](https://adoptopenjdk.net/icedtea-web.html)
- Projects -> [JDK Mission Control](https://adoptopenjdk.net/jmc.html)
- [Migration Guide](https://adoptopenjdk.net/migration.html)
- [Support](https://adoptopenjdk.net/support.html)
- [Get involved!](https://adoptopenjdk.net/getinvolved.html)
- Further information with the same set of links as in "Other links underneath"

Which links should be on the front page in the "arrow" row, which should be inderneath, and which should be in the burger menu. Should we have duplication between them?

I think the new FAQ should be quite prominent so I'd go with replacing "Migration" with FAQ on the "arrow" line.

Also most of the other pages (e.g. https://adoptopenjdk.net/installation.html) have three arrow links on the bottom - [Migration](https://adoptopenjdk.net/migration.html), [Support](https://adoptopenjdk.net/support.html) and [Submit an issue](https://github.com/AdoptOpenJDK/openjdk-build/issues) but "Submit an issue" isn't on the main page. I'd suggest replacing at least one of those with the FAQ link.

Actually scrub that the set of links at the bottom seem different depending on which page you're on ... So we need to introduce some consistency there regardless.

**Comment by DanHeidinga** [comment]
Should the Adopt Docker images at docker hub be linked to as well?  I thought had a link to docker hub previously but don't see it now

**Comment by sxa555** [comment]
@DanHeidinga You are correct - See #628

**Comment by rdenhof** [comment]
I would suggest getting rid of "Submit an issue" by replacing with FAQ. Then set with arrows could look like
- Installation
- Migration
- Support
- Get Involved
- FAQ

on all pages.

To other links underneath I'd add link to Docker repo.

On burger menu I think it would make sense to have all links appearing on bottom additionally but well structured.

**Comment by aahlenst** [comment]
@rdenhof It's hard for me to evaluate the proposed changes if I have to map the text here in my head to the website in a different window. Could you create a small sketch? Does not have to be fancy.

**Comment by rdenhof** [comment]
> @rdenhof It's hard for me to evaluate the proposed changes if I have to map the text here in my head to the website in a different window. Could you create a small sketch? Does not have to be fancy.

What about this (I didn't consider order below "Further information", yet):
![646](https://user-images.githubusercontent.com/4981146/91536045-6c12a380-e914-11ea-91b1-8200f76e7a0e.PNG)

**Comment by aahlenst** [comment]
The proposed changes make sense from my POV.

**Comment by sxa** [comment]
Yep FAQ needs to be more prominent. That doc is relatively new and absolutely should be a priority for inclusion on more pages. [Supported platforms](https://adoptopenjdk.net/supported_platforms.html) is the other one I sometimes get lost trying to find (you have to find the [Support page](https://adoptopenjdk.net/support.html) and then it's linked from the bottom of that :-)

**Comment by rdenhof** [comment]
What about placing 'Supported platforms' as first element in the section with the arrows (right before 'Installation')? If you're fine with it I could start with the change.

**Comment by rdenhof** [comment]
Any feedback to this topic?

**Comment by karianna** [comment]
@rdenhof - Apologies for the delay.  The project is mostly focusing on the adoptium version of this site (as we transfer to the Eclipse Foundation).  See https://github.com/adoptium/adoptium.net (current site) and https://github.com/AdoptOpenJDK/website-adoptium (future site - will get migrated to adoptium GitHub soon)

**Comment by karianna** [comment]
We're working on the new website at Adoptium.net
