### ISSUE TITLE
Architecture not detected when connecting from Chromium/Raspbian/arm32

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#649]
* **Browser**: Chromium on Raspbian

Testing on a Pi4 so it's a recent release.

The front page of adoptopenjdk.net does not appear to identify the platform properly so the blue download button does not go direct to the architecture-specific (arm32/armv7l) download, it just says "Latest release" and takes you to the page with the downloads for each architecture. I suspect this won't be too difficult to fix.

**Comment by gdams** [comment]
@sxa555 a simple PR here should work: https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/json/config.json#L308

see https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/json/config.json#L175 for an example
