### ISSUE TITLE
Negate the need for counters such as 'assetCounter'

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#65]
**Option 1:**
forEach loops can be replaced by standard 'for' loops that count from zero up to 'exampleArray.length'. Instead of referencing the counter, you can reference 'i'.

Example:
```
for (i = 0; i < platformDropDown.options.length; i++) {
          dropdownArray.push(platformDropDown.options[i].value);
}
```

**Option 2:**

We can use the forEach loop's built-in index counter, which is always the second argument passed into a forEach function.

Example:
```
example.forEach(function(abc, index) {
        console.log(index);
});
```

@karianna, you mentioned that "Usually when you have loop counters like assetCounter and a assetCounter2 it's a scoping or naming code smell...."

Which of these is a better solution in your opinion?

**Comment by karianna** [comment]
As a Java OO hacker I'd normally say Option 1.  But I've had enough good JS developers beat into me that 'function, function, function' so I think Option 2 is the more idiomatic way for modern JS.  But I really should be deferring to your expertise here :-)

**Comment by gdams** [comment]
yeah option 2 all the way here in my opinion

**Comment by Joe-Brady** [comment]
Ok, I shall use option 2!
I'm still learning a lot, so this is interesting stuff hearing your opinions on this

Interestingly, I discovered that there are some situations where JS doesn't like forEach - for example, if you create an array like this:

`var array = document.getElementsByClassName("my-class");
`
...and then try to do:
```
array.forEach(function(abc, index) {
        console.log(index);
});
```
...it errors to the console, saying that document.getElementsByClassName.forEach isn't a function, or something along those lines. Have you seen that before??
But a standard `for` loop works just fine...

Anyway, I'll use forEach wherever possible :-)

**Comment by karianna** [comment]
What does `document.getElementsByClassName("my-class")` return?

**Comment by Joe-Brady** [comment]
An array of all HTML elements that have `class="my-class"`.
For example, if you had these elements on your HTML page, they would all be added as entries in the array:

```
<p class="my-class example-class"></p>
<p class="example-class my-class"></p>
<h1 class="my-class"></h1>
<div class="xyz my-class abc"></div>
```

**Comment by Joe-Brady** [comment]
By the way, I'm almost finished with removing the 'counter' vars - working absolutely fine with Option 2. 
Will be doing a couple other bits before submitting a PR.
