### ISSUE TITLE
Download page dropdown boxes for filtering are not working as expected

### ISSUE THREAD

**Issue by JonasSchnoor** [AdoptOpenJDK/openjdk-website#659]
* **Browser**: Firefox 72.0.1 (64-bit)

The dropdown boxes on the download page for filtering according to OS and architecture are not working as expected:

- Select OS "Any" and architecture e.g. "x86":

   _Actual behaviour_: You can only select "Any" and "x86" in the architecture dropdown until you select "Any" architecture again.

   _Expected behaviour_: If OS "Any" is selected all options should be available in the architecture dropdown.

- Select OS "Any" and architecture "s390x". Now select OS "Linux" and change architecture back to "Any":

   _Actual behaviour_: You can only select "Linux" or "Any" in the OS dropdown.

   _Expected behaviour_: If "Any" architecture is selected all options should be available in the OS dropdown.

**Comment by jerboaa** [comment]
@JonasSchnoor Please mention what you would expect to happen. I.e. contrast *actual* vs. *expected* behavior. It's not clear what you'd want fixed from the description. At least to me.

**Comment by JonasSchnoor** [comment]
@jerboaa I've edited my original comment to reflect actual vs. (my) expected behaviour.
@gdams I'll try and have a look if I have some free time but I only know a little Javascript so maybe someone more knowledgeable would be better suited.

**Comment by gdams** [comment]
@JonasSchnoor nevermind, I've fixed it here: https://github.com/AdoptOpenJDK/openjdk-website/pull/660

**Comment by tellison** [comment]
@JonasSchnoor please check it is working as expected, and reopen this issue if required.
