### ISSUE TITLE
Nightly builds not filter on HotSpot/OpenJ9 - shows both

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#661]
FireFox ESR on Linux:

https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9

Regardless of whether the filter is set to HotSpot or OpenJ9 the table shows both and you can't tell which is which unless you hover over the filename.

**Comment by gdams** [comment]
This is actually a bug with the V3 API. `jvm_impl` doesn't seem to work.

Example: https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga?page_size=100&?jvm_impl=openj9&vendor=adoptopenjdk

returns j9 and hotspot binaries. FYI @johnoliver

**Comment by johnoliver** [comment]
@gdams your url has 2 `?` in it
