### ISSUE TITLE
Notice about '15th Jan 2020... update within 24-48 hours' still visible

### ISSUE THREAD

**Issue by patric42** [AdoptOpenJDK/openjdk-website#666]
The above notice is still shown on the page, which looks like it's been forgotten.

Other question is, the 11.0.6 release of OpenJ9/Hotspot is only, 8u242 only Hotspot is updated, OpenJ9 still missing. Also from the repos, btw.

What happened?

**Comment by aahlenst** [comment]
The OpenJ9 editions needed some additional fixes but should appear any minute now. That's why the notice is still there.
