### ISSUE TITLE
Port the infrastructure providers wiki to a supporters page

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#67]
we should add a link on the website to https://github.com/AdoptOpenJDK/openjdk-build/wiki/Infrastructure-Providers so that we promote our donators/supporters

**Comment by karianna** [comment]
As a minimum yes, I think supporters will expect that they are on the website though (since that's the wider audience).  How we do that in a tasteful manner I'm not sure yet.  I'm personally not against a supporters page or a row of logos in a footer.

**Comment by Joe-Brady** [comment]
A supporters page in the menu is pretty unobtrusive, so we could do that as a minimum.
In fact, we could just make the menu entry link directly to that wiki link above from George.

Also not against a row of logos in the footer - monochrome and semi-transparent would be nice, and not too big, to keep it unobtrusive and blending with the colour scheme. However, full colour would be ok at a push.

**Comment by karianna** [comment]
Wearing my "I'm a CEO of an org" that, I know that the footer would be a minimum requirement as I fully well know that developers won't go to the supporters page as a rule.  If the logos are subtle but 'above the line' on the home page then I think we can entice supporters.

**Comment by Joe-Brady** [comment]
By 'above the line', do you mean not in the footer? (On the home page, at least)

**Comment by karianna** [comment]
'above the line' was poor language on my part, I guess I mean 'visible without scrolling' on a modern desktop resolution.

**Comment by Joe-Brady** [comment]
Got it! Thanks

**Comment by karianna** [comment]
So I was thinking about this further and if we stick with the philosophy that the wiki is for core dev and the website is for consumers that we should definitely go ahead with this and port the wiki over so to speak.  I'll change the title of this Issue

**Comment by Joe-Brady** [comment]
@karianna This page is essentially finished - I just need:

- The remaining writeups for Linaro and Scaleway
- An idea of whether I should be removing Tier-1 temporarily (there's nothing in Tier-1)

**Comment by karianna** [comment]
@gdams - Do any of our providers qualify for Tier-1 in your opinion?

@Joe-Brady I think we can leave those writeup blanks and fill them in later.

**Comment by Joe-Brady** [comment]
I suggested to George that, for the time being, we could have a statement under the Tier-1 section that explains that we are looking for X Y and Z infrastructure?

**Comment by karianna** [comment]
@Joe-Brady sounds good!

**Comment by Joe-Brady** [comment]
@karianna @gdams any thoughts on what X Y and Z we're looking for?

**Comment by karianna** [comment]
Just realised that IBM should be listed as a Tier 1 and the LJC (or me ;p)

In terms of X, Y, Z - How about something like "Multiple Build and Test servers across various platforms that have significant CPU and Memory in order to quickly and continuously build and test multiple versions of OpenJDK"

**Comment by gdams** [comment]
yeah we'd need @tellison to provide the blurb/logo though

**Comment by karianna** [comment]
LJC blurb: 

The London Java Community (LJC) is a group of Java enthusiasts who are interested in benefiting from shared knowledge in the industry. Through our forum and regular meetings developers can keep in touch with the latest industry developments, learn new Java (& other JVM) technologies, meet other developers, discuss technical/non technical issues and network further throughout the Java Community.

The LJC has over 6000 members and holds a seat on the Executive Committee of the Java Community Process ([JCP](http://www.jcp.org)) - aka the Java standards body.  The LJC is a leading member in both the [Adopt a JSR](https://community.oracle.com/community/java/jcp/adopt-a-jsr) and [Adopt OpenJDK](https://community.oracle.com/docs/DOC-991498) programmes to contribute to Java standards and the leading implementations behind those standards.

**Comment by karianna** [comment]
![ljc_logo](https://cloud.githubusercontent.com/assets/180840/25474118/e20dd91c-2b29-11e7-93c0-73c5342e3a02.jpg)

**Comment by Joe-Brady** [comment]
Nice, thanks Martijn.

**Comment by karianna** [comment]
@Joe-Brady Missed your comment about the logo, but yes that would be fine.
