### ISSUE TITLE
Supported platforms page missing CentOS 8 and RHEL8 support

### ISSUE THREAD

**Issue by rodionmoiseev** [AdoptOpenJDK/openjdk-website#672]
* **Browser**:

Hi,

According to commit below, it appears that CentOS8 and RHEL8 support were officially added in the installer project, but the “supported platforms” page was not updates accordingly.

Related pull request: https://github.com/AdoptOpenJDK/openjdk-installer/pull/110

Regards

**Comment by sxa555** [comment]
At the moment we don't have any machines to test with, but we're in the process of getting playbooks set up for this to be able to run testing on at least one of those two :-)

**Comment by rodionmoiseev** [comment]
Wow, that would be great! If you have trouble deciding between RHEL8 and CentOS8, then I would vote for RHEL8 👍

**Comment by hendrikebbers** [comment]
@sxa can you give an hint of the current state of the test machines. Currently it is not clear what OS should be added to the support section.

**Comment by sxa** [comment]
Support page was updated under https://github.com/AdoptOpenJDK/openjdk-website/pull/783 so can be closed - we only have [one RHEL8](https://ci.adoptopenjdk.net/computer/test-aws-rhel8-x64-1/) system at the moment but will look to increase that capacity as we go forward.
