### ISSUE TITLE
Broken links to https://ci.adoptopenjdk.net/

### ISSUE THREAD

**Issue by luchsh** [AdoptOpenJDK/openjdk-website#674]
* **Browser**: Chrome 80.0.3987.106, x64, Mac OS 10.15.3
 

Hello Adopt-OpenJDK maintainers,

I found the link to "https://ci.adoptopenjdk.net/" from the bottom of page "https://adoptopenjdk.net/" was broken. see the screenshots below
<img width="501" alt="截屏2020-02-1718 19 04" src="https://user-images.githubusercontent.com/1205973/74644959-15cce700-51b2-11ea-9b1c-10f93b78eb16.png">
I used to download binary JTreg and recommend others to download from that link, but it is gone. 
may I ask if this is temporary unavailability or some changes in the release process?

Thank you
Jonathan

**Comment by aahlenst** [comment]
The Jenkins master has disk space issues. Should be back soon.

**Comment by luchsh** [comment]
> The Jenkins master has disk space issues. Should be back soon.

got it, thanks!
