### ISSUE TITLE
Typo on download page 

### ISSUE THREAD

**Issue by getthegroove** [AdoptOpenJDK/openjdk-website#678]
Seems like you mixed up German and English, as your download page says "[...]choice of either the OpenJDK HotSpot **oder** Eclipse OpenJ9 VM."
I don't know if Americans adopted _oder_ to their language, but for consistency reasons it should be _or_ instead.

Spotted on: https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

**Comment by sxa555** [comment]
Hmmm - definitely says `or` on my screen in both FireFox and Chrome on Linux - is your browser/OS set to a specific language (I'm in UK English, and which browser/OS is it?)
![image](https://user-images.githubusercontent.com/6487691/74960041-8454b380-5403-11ea-9583-eb5b728b1627.png)

**Comment by sxa555** [comment]
@jerboaa has reproduced it with language in firefox set to Deutsch
