### ISSUE TITLE
JDK14 nightly builds not visible on the web site

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-website#680]
No option for JDK14 on https://adoptopenjdk.net/nightly.html even though they are being built in jenkins

**Comment by karianna** [comment]
Hmm, have we ever displayed the next 'unreleased' versions on the website?  The frontpage also only allows 13 to be selected.

That said I think we should support this so folks can test out EA builds.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/pull/688 - makes it visible in nightly (as it should do)
