### ISSUE TITLE
website not showing latest Nightly OpenJ9 builds

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-website#681]
Website shows latest jdk11 openj9 nightly as dated 7th Feb 2020: https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

However, v2 API shows 25th Feb:
https://api.adoptopenjdk.net/v2/latestAssets/nightly/openjdk11?os=linux&arch=x64&heap_size=normal&openjdk_impl=openj9

**Comment by karianna** [comment]
Fixed by recent v3 API bug fix
