### ISSUE TITLE
Installation of JRE package not described

### ISSUE THREAD

**Issue by vitkalisz** [AdoptOpenJDK/openjdk-website#682]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

Installation was much harder because installation of JRE is not described at https://adoptopenjdk.net/installation.html#linux-pkg 
Maybe just add the line apt-get install <adoptopenjdk-8-hotspot-jre> or even better explain how to use `apt search adoptopenjdk`.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by aahlenst** [comment]
I'd prefer we'd explain how to use `apt search adoptopenjdk`.

**Comment by codeupall** [comment]
Hi, this is my first time trying to contribute, can I work on this? Thanks!

**Comment by smlambert** [comment]
For sure, welcome @codeupall !  If you have any questions, please feel free to ask in this issue!

**Comment by karianna** [comment]
Instructions updated at adoptium.net
