### ISSUE TITLE
Make debugimage archives available on the website

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-website#696]
It would be useful to have downloads of the debug image archives via the website. Ideally the debugimage archives will be preserved for every build. 

https://github.com/AdoptOpenJDK/openjdk-build/issues/1596 added debug image archives for OpenJ9 builds. Copying the contained debug-image folder over top of the jdk makes symbols available to greatly ease the task of debugging an issue with native code. 

See also https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/128

**Comment by andrew-m-leonard** [comment]
debugimage's for openj9 and hotspot are available on the website, eg: https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9
