### ISSUE TITLE
Access Old Nightly Builds from Adopt Build Website

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-website#698]
### Problem Description

Looking at https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9 for Linux x64, I noticed that the oldest build is from Jan 11, 2020. 

We should be able to get some older nightly builds from a few months ago so that we can use those builds to narrow down regressions that might have been reported or investigated far away from when the original issue started. 

Old builds can be found here: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases

### Example: 

![image](https://user-images.githubusercontent.com/10422081/74946946-0e7f2680-53c8-11ea-90b6-786ae1438f94.png)

**Comment by gdams** [comment]
@pilhuhn this should be fixed now, you can now use the date selector to go as far back as you like.

**Comment by piyush286** [comment]
Perfect! Thanks everyone for fixing this.
