### ISSUE TITLE
Get a Slack signin / I'd like to join page

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#70]
For some bizarre reason Slack doesn't have a request to join team option. Figure out a way to enable one.

**Comment by Joe-Brady** [comment]
https://github.com/rauchg/slackin
Currently trying to get my head around this... a fair few people suggesting that this is currently the best solution

**Comment by gdams** [comment]
I'm not sure that this will work without premium slack, we should message slack and ask if they can upgrade the account

**Comment by karianna** [comment]
Might be able to do: https://github.com/pidster/aws-lambda-slack

**Comment by Joe-Brady** [comment]
It's certainly better documented in terms of the setup process - would you or George perhaps be better placed than me for setting this up?

I'd be happy to, except I've never done stuff with AWS, so I'd definitely be slower!

**Comment by karianna** [comment]
Happy to give it a go this weekend (I'm currently in Dublin for a couple of talks) yeah.  I know the author of it.

**Comment by Joe-Brady** [comment]
Great, yes that would be a big help.

Cool, that's good news - more likely to get support if we can't work something out 😄

**Comment by karianna** [comment]
Fixed via #73
