### ISSUE TITLE
Downloaded file checksum doesn't match.

### ISSUE THREAD

**Issue by arnieAustin** [AdoptOpenJDK/openjdk-website#714]
I'm on Windows 10/64 and the checksums don't match.

SHA256 hash of OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.zip:
6980db87a3f921801fcf50d1a933304cf4d4b46ef2d35617c96fcc40ac1a1eb9
CertUtil: -hashfile command completed successfully.
4dce48e8c67d6191acc2e8fc1ec450ac7a51e6f15102c9c42cf3b564a5bb3df4

**Comment by sxa** [comment]
@arnieAustin Where is the second checksum coming from? The first one is correct for [the file](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.zip) (I've downloaded it, computed the checksum with `sha256sum` and it's the same one you mention ending in ` 1a1eb9` as what's in our  [sha256.txt file](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.zip.sha256.txt)

**Comment by ParkerM** [comment]
`4dce48e8c67d6191acc2e8fc1ec450ac7a51e6f15102c9c42cf3b564a5bb3df4` is the sha256 checksum for OpenJDK14U-jdk_x64_windows_hotspot_**14.0.1_7**.zip.

See [sha256.txt](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.1%2B7/OpenJDK14U-jdk_x64_windows_hotspot_14.0.1_7.zip.sha256.txt)

**Comment by sxa** [comment]
Well spotted. yes that makes sense. Hopefully that clarifies things for you @arnieAustin ... I close this - if you believe there's still an outstanding issue you can reopen it.
