### ISSUE TITLE
Change default download offered from 8 LTS to 11 LTS

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-website#716]
At present, when you visit adoptopenjdk.net you are offered by default the OpenJDK 8 (LTS) version.

Propose to leave all options as-is, but change the default selected radio button to be OpenJDK 11 (LTS), thereby requiring users to explicitly select the older version.

The rationale is that we should be encouraging people to use the latest LTS unless they choose otherwise.

Same default changes should apply elsewhere, such as releases.html page.

**Comment by gdams** [comment]
@tellison please change the line here: https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/json/config.json#L9

**Comment by karianna** [comment]
TSC has agreed to make this change
