### ISSUE TITLE
Tighten language around the use of the term OpenJDK

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#719]
AdoptOpenJDK builds binaries consisting of a Java Virtual Machine from:

* OpenJDK Hotspot
* Eclipse OpenJ9

Either of those is then combined with OpenJDK class libraries

The wording on our website sometimes isn't as clear between this distinction as it could be.

**Comment by tellison** [comment]
As you say, the two builds differ by JVM, hence isn't the distinction between "OpenJ9" and "HotSpot", rather than OpenJ9 and OpenJDK?

**Comment by karianna** [comment]
> As you say, the two builds differ by JVM, hence isn't the distinction between "OpenJ9" and "HotSpot", rather than OpenJ9 and OpenJDK?

Updated the comment above, I don't _think_ it materially changes the PR contents, LMK!
