### ISSUE TITLE
Update Slack Archive to custom URL

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#73]
They've enabled the custom domain (slackarchive.adoptopenjdk.net), so we can cname the DNS to adoptopenjdk.slackarchive.io (I think that's right) and we should be sorted.

karianna commented 12 days ago I asked:

"Quick question on the DNS, so do we need to set up a record pointing slackarchive.adoptopenjdk.net to adoptopenjdk.slackarchive.io or?"

From their support team -

"Just cname it to app.slackarchive.io. That will be sufficient. Archive import is running now."

Hope that makes sense...

**Comment by Joe-Brady** [comment]
@tellison I have a feeling this might require your assistance?

**Comment by gdams** [comment]
I have done this now
