### ISSUE TITLE
Provide "supported versions" information for ITW

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/openjdk-website#734]
Based on a discussion on the ITW slack channel.

Currently we do not define what GA releases of Adopt are supported by ITW. We should add additional information [here](https://adoptopenjdk.net/icedtea-web.html) and [here](https://adoptopenjdk.net/migration.html).

**Comment by hendrikebbers** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/662

**Comment by karianna** [comment]
@hendrikebbers Should the icedTeaWeb documentation now live at Karakun?

**Comment by karianna** [comment]
@hendrikebbers I'm closing this issue now as most folks use ITW with Adoptium binaries.
