### ISSUE TITLE
Archive page is missing: https://adoptopenjdk.net/archive.htm

### ISSUE THREAD

**Issue by vveider** [AdoptOpenJDK/openjdk-website#737]
Archive page is missing: https://adoptopenjdk.net/archive.htm
404

**Comment by aahlenst** [comment]
It's https://adoptopenjdk.net/archive.html. Did you find the link without the `l` at the end somewhere?

**Comment by vveider** [comment]
Dah... Thanks. I guess I missed l when copied it...
