### ISSUE TITLE
Add a row of social media links

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#75]
Possibly in the footer

**Comment by gdams** [comment]
Looks like we don't have a fb page? @karianna is it worth us creating one?

**Comment by karianna** [comment]
@neomatrix369 I thought you created one no?

**Comment by neomatrix369** [comment]
@karianna we have one for Adopt-a-JSR (https://www.facebook.com/AdoptaJSR/) but not for Adopt OpenJDK - do we need one?

**Comment by karianna** [comment]
@neomatrix369 I don't think we need one per say.  Has the Adopt a JSR one been a success?

**Comment by neomatrix369** [comment]
@karianna it has been popular despite us not pushing it too much into the community but not enough that we should have a separate one, currently I piggy back on it for AdoptOpenJDK news and it gets good coverage - there is a community overlap between Adopt-a-JSR & Adopt OpenJDK

**Comment by Joe-Brady** [comment]
Added in latest PR, will close this issue.
If you would like to add more social icons, that's easily done, please open a new issue :-)
