### ISSUE TITLE
API requests fail when using Tor

### ISSUE THREAD

**Issue by orexy** [AdoptOpenJDK/openjdk-website#750]
CloudFlare presents a captcha for Tor users, causing non-browser tools to fail.
```
curl -Lfo jdk.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk
curl: (22) The requested URL returned error: 403
```

Please explicitly allow Tor users on CloudFlare by configuring the [IP Access Rules](https://support.cloudflare.com/hc/en-us/articles/217074967-Configuring-IP-Access-Rules).

Thank you.

**Comment by tellison** [comment]
Closing this as WONTFIX.  While I have no objection to Tor, I think a Cloudflare 'challenge' is reasonable for browser users, and while I’ve not studied it closely there may be a way for scripts to access our API via the [Cloudflare onion service](https://blog.cloudflare.com/cloudflare-onion-service/).  If not you will likely have to seek out a non-tor gateway.
