### ISSUE TITLE
Cannot find where to download installers

### ISSUE THREAD

**Issue by nils-ten-hoeve** [AdoptOpenJDK/openjdk-website#756]
Admittedly, I am a bit clumsily and dyslectic and I did not read the whole https://adoptopenjdk.net/installation.html page, but I cannot find WHERE to download the installers (e.g. .msi for windows).

One would assume that this would be directly available via an easy click of a button on the top of the page, so that as many people download it as possible (easier download=more downloads).

https://adoptopenjdk.net/installation.html seems to refer to downloading the installers, but does not tell where……

Please improve this!!!!

Kind regards

Nils ten Hoeve

**Comment by karianna** [comment]
@nils-ten-hoeve - thanks for this issue.  It's a good first issue for folks to try, would you like to give making a PR for this one a go?

**Comment by gdams** [comment]
@niklas-ekman-telia take a look at https://adoptopenjdk.net/releases.html,

The installers are available in the same location as the tarballs, look for the `.msi` option in the downloads

**Comment by rdenhof** [comment]
Hi, please assign me the issue.

**Comment by nils-ten-hoeve** [comment]
How?

**Comment by rdenhof** [comment]
I guess @karianna or @gdams might be able to do this.

**Comment by aahlenst** [comment]
@rdenhof As you wish 🙂

**Comment by rdenhof** [comment]
Thanks, please review [PR 761](https://github.com/AdoptOpenJDK/openjdk-website/pull/761).

**Comment by rdenhof** [comment]
Updated [PR 761](https://github.com/AdoptOpenJDK/openjdk-website/pull/761).

**Comment by rdenhof** [comment]
Thanks for merging, @aahlenst . I guess this can be closed, now?
