### ISSUE TITLE
Release notes page is missing July 2020 update

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-website#758]
As posted on the `release` Slack channel, the release notes page https://adoptopenjdk.net/release_notes.html is missing the list of fixes for the July 2020 releases.

I see this blog post (which was posted before the jdk8u265-b01 respin), but nothing in https://adoptopenjdk.net/release_notes.html

**Comment by grimlock81** [comment]
Any updates on this issue?

**Comment by aahlenst** [comment]
Removing the "good first issue - candidate" label because this task requires JBS access to complete. Without JBS access, the JBS reports won't contain security issues.
