### ISSUE TITLE
Update NPM dependencies

### ISSUE THREAD

**Issue by rdenhof** [AdoptOpenJDK/openjdk-website#762]
Several NPM dependencies are `npm update` candidates. Additionally `npm audit fix` should be executed.

**Comment by aahlenst** [comment]
@gdams What about activating Dependabot?

**Comment by rdenhof** [comment]
@aahlenst , @gdams : If there is nothing to be said against it, I could introduce Dependabot. Cool feature, wasn't aware of it 🙂.

**Comment by aahlenst** [comment]
@rdenhof If you prepare a config, I'll happily review it.

**Comment by rdenhof** [comment]
checking behavior atm

**Comment by rdenhof** [comment]
I could imagine automerge would make sense, otherwise # of PRs might be exhausting: there's one per dependency. I suggest to update dependencies and to introduce Dependabot at the same time.

**Comment by aahlenst** [comment]
What's the behaviour of automerge? Does it wait for the CI to pass? If so, it might be an option if the CI catches problems created by incompatible updates. We don't do automerge over on the AdoptOpenJDK blog. Is it tedious? Absolutely. But we had multiple cases of incompatible updates proposed by Dependabot.

**Comment by rdenhof** [comment]
There's just mentioned after checks have been performed successfully. So for my understanding it should pass, yes.

`For all of the options below Dependabot will wait until all your status checks pass before merging. You can also set working hours for automerging in your dashboard account settings.`

Unfortunately I cannot verify right now, but your're right: it might be risky. I also saw that there are not too much dependencies updated automatically every time.

**Comment by aahlenst** [comment]
From my point of view, both options are fine: Enable automerge right away or skip automerge for the moment, see how it goes and then we can either leave it off or enable it.

**Comment by rdenhof** [comment]
I'll do so (1st option). That's also the recommended way as far as I understood.

**Comment by rdenhof** [comment]
Unfortunately not possible, so back to option 2. Please review [PR 763](https://github.com/AdoptOpenJDK/openjdk-website/pull/763).

**Comment by rdenhof** [comment]
Created two separate ones for [Dependabot](https://github.com/AdoptOpenJDK/openjdk-website/pull/764) and for [`npm audit fix`](https://github.com/AdoptOpenJDK/openjdk-website/pull/765). [PR 763](https://github.com/AdoptOpenJDK/openjdk-website/pull/763) was deleted.
