### ISSUE TITLE
Download pages don't work without JavaScript

### ISSUE THREAD

**Issue by KOLANICH** [AdoptOpenJDK/openjdk-website#792]
* **Browser**: Mozilla Firefox

The page should be usable without JavaScript.

**Comment by karianna** [comment]
We rely on Javascript to dynamically build those pages.

**Comment by KOLANICH** [comment]
It souldn't be done client side. JavaScript is considered harmful.

**Comment by aahlenst** [comment]
The desire to have a download page that works without JavaScript is legit. But nowadays it's not feasible because the page is deployed as a static page to Github Pages and all dynamism comes from JavaScript. An overhaul of our webpage is long overdue and I'll propose a Java-based back-end with some JS sprinkled on top.

**Comment by KOLANICH** [comment]
>Java-based back-end

How about just a static website generated automatically, without any mandatory JS-based interactivity, so no need to have a hosting capable to run code?

**Comment by karianna** [comment]
> > Java-based back-end
> 
> How about just a static website generated automatically, without any mandatory JS-based interactivity, so no need to have a hosting capable to run code?

Because of the sheer amount of permutations of platform and version combinations means we need to provide users some helpful Ux.  A gigantic spreadsheet in HTML form would not be popular :-)

Don't forget you can get your binary directly from the API if you choose to skip our website.

**Comment by KOLANICH** [comment]
>Don't forget you can get your binary directly from the API if you choose to skip our website.

I currently have to do it. Not a convenient way.
