### ISSUE TITLE
Unauth-ed GitHub API calls have a per-IP rate limit of 60 per hour

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#8]
The website relies heavily on the GitHub API.

The whole website should only use 1 call to the GitHub API in most browsers. After that, the browser caches the resulting JSON and does not use any more, so in normal situations, a limit of 60 per hour is not an issue.

However, inside some organisations, there are a limited number of external IP addresses that users can appear as. In this situation, 60 API calls per hour per IP becomes a problem.

It is possible to increase this limit by authenticating the API calls. However, after some initial attempts, the suggested solution of OAuth did not appear to be suitable for our situation.

Will need to find someone who has experience with the GitHub API to find the right solution.

**Comment by Joe-Brady** [comment]
Sean Cawood might have some answers. I will be messaging him soon.

**Comment by Joe-Brady** [comment]
**From Sean:** 
You will always need a secret/token, even if you use API keys to authenticate. The normal way to handle this is rather than bake it into the website code directly, have the code read the value in from another location. This could be a file with the details obfuscated, or going further from an external system like ldap which can store the credentials and pass them in as needed

**Comment by Joe-Brady** [comment]
Following more research: a good solution could be to have a Node.js application running server-side, the sole purpose of which is to call the GitHub API, using the OAuth system, and return the releases JSON from a specified repository.

This application will not be accessible to the public - so the client ID and client secret for OAuth can be stored safely there.

AdoptOpenJDK.net never contacts the GitHub API directly - it just queries the Node.js server and gets the JSON.

**Comment by Joe-Brady** [comment]
Perhaps the Node.js application could run the API request a couple of times per day, so that the JSON is pre-stored and readily accessible, rather than the user having to wait for a response from the GitHub API every time.

**Comment by Joe-Brady** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/20062773/24145762/8f460234-0e2a-11e7-9b0e-df1801b5803e.jpg)

**Comment by Joe-Brady** [comment]
George will create the above Node setup on Bluemix or similar.

@gdams - GitHub's approach for server-to-server authenticated API calls like this is to:

1. Create an OAuth application, note down the Client ID and Client Secret.

2. use this URL format in your GET request: 
https://api.github.com/repos/AdoptOpenJDK/openjdk-releases/releases?client_id=xxxxx&client_secret=xxxxx

(i.e. they say not to use a personal access token)

**Comment by tellison** [comment]
> George will create the above Node setup on Bluemix or similar.

We don't have enough machines under our own admin already that can do this?!

**Comment by gdams** [comment]
We don't need to host it as the app runs as a job on Jenkins

**Comment by gdams** [comment]
bad bot
