### ISSUE TITLE
QUESTION: Should the font weight be 'regular', instead of the current 'light'?

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#80]
**EDIT: I've tried just using the default 'sans-serif' font instead of Open Sans. Think this might be the solution, as it's a halfway-house in terms of font weight. See what you think, I'll post more screenshots than this one if wanted:**

<img width="1440" alt="screen shot 2017-04-30 at 20 08 18" src="https://cloud.githubusercontent.com/assets/20062773/25567219/f4c41bd4-2de0-11e7-975b-652f00faafff.png">

I originally used the lightest available font weight for the current font family "Open Sans". This was to achieve a modern and clean appearance.

However, I've noticed that it looks a bit TOO super-thin on some screens, especially mobile devices, and in some cases a bit hard to read.

I've attached screenshots of various pages of the website with a 'regular' font weight.

Thoughts?? @gdams @karianna @tellison 

<img width="1440" alt="screen shot 2017-04-30 at 19 12 29" src="https://cloud.githubusercontent.com/assets/20062773/25566923/14dc18a0-2ddb-11e7-8960-50132148b35c.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 13 22" src="https://cloud.githubusercontent.com/assets/20062773/25566913/ff626204-2dda-11e7-8111-6e0f7bd5f07f.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 12 42" src="https://cloud.githubusercontent.com/assets/20062773/25566922/14dc3c54-2ddb-11e7-8291-39cbf2f29de2.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 12 49" src="https://cloud.githubusercontent.com/assets/20062773/25566911/ff61a710-2dda-11e7-97a9-094d2f261f51.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 12 58" src="https://cloud.githubusercontent.com/assets/20062773/25566910/ff611c0a-2dda-11e7-8d1a-368cc5f5f9f2.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 13 05" src="https://cloud.githubusercontent.com/assets/20062773/25566914/ff629102-2dda-11e7-8384-f19a3286e0a5.png">
<img width="1440" alt="screen shot 2017-04-30 at 19 13 11" src="https://cloud.githubusercontent.com/assets/20062773/25566912/ff620476-2dda-11e7-8932-2f29089d45de.png">

**Comment by tellison** [comment]
"regular" looks fine to me, but happy to leave it to your judgement

**Comment by Joe-Brady** [comment]
Ok, I'm going with sans-serif for now.

**Comment by karianna** [comment]
Sans-serif screenshot looks crisp to me!
