### ISSUE TITLE
Download statistics are not part of the status page

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/openjdk-website#816]
https://status.adoptopenjdk.net does not contain https://dash.adoptopenjdk.net and https://dash-v2.adoptopenjdk.net

**Comment by gdams** [comment]
They are under the dashboard section if that's what you're looking for?

![Screenshot 2020-10-26 at 16 36 00](https://user-images.githubusercontent.com/20224954/97200606-56e9b200-17a9-11eb-8ef5-ae93b50224d6.png)
