### ISSUE TITLE
Set maximum length of Nightly Builds page

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#82]
we should set a maximum amount of nightly builds to be displayed per page and then have `next` and `back` buttons to navigate further into history

**Comment by Joe-Brady** [comment]
Instead of 'next' and 'back', how about a calendar date-picker? Otherwise we're going to end up with endless pages to click through and no way to jump to a date that they have in mind

**Comment by Joe-Brady** [comment]
Before doing this, I will fix #68, because it will make the JS a little clearer to work with.
