### ISSUE TITLE
Broken Link to OpenJ9 FAQ

### ISSUE THREAD

**Issue by andybissen** [AdoptOpenJDK/openjdk-website#823]
* **Browser**: Firefox 82.0 (64-bit)

Hello,

The hyperlink to 'OpenJ9 FAQ' on [AdoptOpenJDK FAQ](https://adoptopenjdk.net/faq.html) is returning a 404 response code on the eclipse site.
The link is under the headline **What is the difference between HotSpot and OpenJ9 downloads?**

The link currently points to https://www.eclipse.org/openj9/oj9_faq.html
But, I think it may need to point to https://www.eclipse.org/openj9/performance instead.

Thanks

**Comment by tellison** [comment]
@andybissen thanks for reporting that.
