### ISSUE TITLE
Debugimages for OpenJ9 GA levels are not easy to find

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#848]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/2245

The OpenJ9 debugimage downloads for the GA levels are not easy to find.

If you go to the nightlies e.g. https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9 you can see teh `debugimage` downloads, however on the GA pages then
- they are not visible 
- there is no direct link to the github release to let you find them (The `jdk-11.0.9+11_openj9-0.23.0` text on [the GA page](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9) does not link to the release in github) so you have to go hunting for it assuming you know of its existance
 
Related: https://github.com/AdoptOpenJDK/openjdk-website/issues/629

**Comment by karianna** [comment]
no longer required
