### ISSUE TITLE
Downloaded file comes with NO instructions.

### ISSUE THREAD

**Issue by dscotese** [AdoptOpenJDK/openjdk-website#861]
**What are you trying to do?**
Install jdk-11.0.9.1+1
**Expected behaviour:**
Extracting the tar file produces a file in the top level folder ("jdk-11.0.9.1+1") which instructs the user on how to get it installed so that `java -version` indicates that Java is installed.
**Observed behaviour:**
The extracted tar file contains no instructions on what to do with the extracted files.
**Any other comments:**
This is probably a simple  oversight on my part, but users shouldn't feel as stupid as I feel because of it.  There ought to be better clues somewhere.

**Comment by sxa** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-website/issues/941

**Comment by karianna** [comment]
installation page updated at adoptium.net
