### ISSUE TITLE
Review and Update the "Get Involved" page

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-website#865]
Going through a review of the [Get Involved page](https://adoptopenjdk.net/getinvolved.html), to make sure all personas are captured and to smooth out the onboarding experience at the project (prompted by the possibility we may be hosting some university programs in 2021, but also because its good to continue to improve the experience for all).

When I read this page with beginner eyes, I do not identify with any of the personas... if I am new, it is not yet true that "I'm an AdoptOpenJDK Developer".  We at the very least need to update for the case, "I want to help at the project, where can I start" (which is what I believe the intent of "I'm an AdoptOpenJDK Developer" guidance was meant for.

**Comment by karianna** [comment]
work done at adoptium.net
