### ISSUE TITLE
Macos installation instructions

### ISSUE THREAD

**Issue by ucchino** [AdoptOpenJDK/openjdk-website#890]
I see the istructions for archive installation : https://adoptopenjdk.net/installation.html#archives

Using Macos i see also : 

1 -> Extract the .tar.gz. You can use the following command: tar xzf OpenJDK11U-jre_x64_mac_hotspot_11.0.10_9.tar.gz
2 -> Add this version of Java to your PATH: export PATH=$PWD/jdk-11.0.10+9-jre/bin:$PATH
3 -> Check that Java has installed correctly: java -version

But... If i not use : jdk-11.0.10+9-jre/Content/Home/bin (adding "Content/Home") running java -version give an error of "not found" / "java runtime not present"

This is the path of instructions : jdk-11.0.10+9-jre/bin
This is the path i must use to have all working correctly : jdk-11.0.10+9-jre/Content/Home/bin

Is this a mistake?

Does the documentation should to be modified?

**Comment by aahlenst** [comment]
You should use the PKG because that's notarized. If you do not want to use the PKG, move jdk-11.0.10+9-jre to /Library/Java/JavaVirtualMachines/. You can then discover it via /usr/libexec/java_home and set the version with `JAVA_HOME`. That's the proper integration for macOS and allows to invoke `java` directly. https://medium.com/notes-for-geeks/java-home-and-java-home-on-macos-f246cab643bd explains most of it. So yes, the website needs an update.

**Comment by ucchino** [comment]
Actually, I noticed this because I want to use java bundled with my application. 
A self-contained archive with application and jre. 
Wanting to do so for now I have succeeded with that trick. 
But I was wondering if there was anything official

**Comment by aahlenst** [comment]
> But I was wondering if there was anything official

Could you please elaborate?

**Comment by ucchino** [comment]
The official java documentation doesn't helped me much

https://docs.oracle.com/javase/7/docs/technotes/guides/jweb/packagingAppsForMac.html

But this article does: http://www.balthisar.com/blog/bundle-the-jre/

In fact here this guy did like me, but it in a more thorough way. However i see that he set: export JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home

{JSDNuVFramework} /
   Java /
     vnu.jar
   PlugIns /
     Java.runtime /
       Contents /
         Home /
           {jlink-built-contents} <----------
         MacOS /
           libjli.dylib
   Resources /
   
If someone want to bundle java then I would recommend doing as I did. I've tried and it works fine.

**Comment by karianna** [comment]
latest instructions at adoptium.net
