### ISSUE TITLE
Commit references should be pulled from the GitHub API

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#9]
Links to commit references are already in place, but currently pulling random information as a placeholder.

Requires completion of AdoptOpenJDK/openjdk-releases#2

**Comment by Joe-Brady** [comment]
Commit references have been removed from the website until this issue is resolved.

Code has been commented out, but remains in the source.

**Comment by gdams** [comment]
closing for now.

**Comment by karianna** [comment]
I think we potentially want to add commit references as part of the meta data?  Probably an issue for the build repo though.  Thoughts?

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
