### ISSUE TITLE
Adding flyers

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/openjdk-website#900]
We created some AdoptOpenJDK flyers (see https://github.com/AdoptOpenJDK/openjdk-website/pull/881 and https://github.com/AdoptOpenJDK/openjdk-website/pull/891). We need to add them to the page.

Maybe we can add a new menu entry (flyers?) and change the top banner on the page for some time to download them? both PDFs and a preview image can be found in the assets folder

**Comment by karianna** [comment]
No longer required.
