### ISSUE TITLE
Switch away from apt-key in Debian/Ubuntu instruction

### ISSUE THREAD

**Issue by TobiX** [AdoptOpenJDK/openjdk-website#960]
The apt maintainer has recently announced that [apt-key is deprecated](https://blog.jak-linux.org/2021/02/18/apt-2.2/#deprecations) and its use is seen as an [antipattern by other Debian developers](https://michael-prokop.at/blog/2021/02/16/how-to-properly-use-3rd-party-debian-repository-signing-keys-with-apt/).

I would suggest to adopt something like the [Kubernetes instructions](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management) or even follow the guide in the [Debian wiki](https://wiki.debian.org/DebianRepository/UseThirdParty) for packaging the key inside the repository (in a package named `adoptopenjdk-archive-keyring`) to allow automatic key rollovers.

**Comment by aahlenst** [comment]
The information how to do this properly is super hard to find (at least for me). So thanks a lot for the links.

It's already planned to create a keyring package, but that won't happen with the old AdoptOpenJDK repository that's going to be replaced soon-ish anyway. Development happens in my private repository (ticket: https://github.com/aahlenst/adoptium-packages-linux/issues/2).

I'm happy to review a PR that updates the instructions on the website to match the Kubernetes instructions.

**Comment by aahlenst** [comment]
To turn it into an issue for newcomers, what to do:

1. Checkout the website (*this*) repository.
2. Look for the page that contains the install instructions and for the segment that mentions how to install using a Debian repository.
3. Change the existing instructions so that they no longer use apt-key. Instead [adapt the instructions provided for Kubernetes](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management) to AdoptOpenJDK.

The key parts from the Kubernetes instructions are:

**Download the Google Cloud public signing key** (*take AdoptOpenJDK's instead, change URLs*)
```
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
```

**Add the Kubernetes apt repository:** (*use AdoptOpenJDK's key, change URLs*)

```
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```

**Comment by Martins-O-U** [comment]
Hello @

> The information how to do this properly is super hard to find (at least for me). So thanks a lot for the links.
> 
> It's already planned to create a keyring package, but that won't happen with the old AdoptOpenJDK repository that's going to be replaced soon-ish anyway. Development happens in my private repository (ticket: [aahlenst/adoptium-packages-linux#2](https://github.com/aahlenst/adoptium-packages-linux/issues/2)).
> 
> I'm happy to review a PR that updates the instructions on the website to match the Kubernetes instructions.

@aahlenst I'm an Outreachy Applicant here and I am interested in updating the website instructions to match the Kubernetes instructions.
@smlambert @sophia-guo @llxia please could this task be assigned to me for my Outreachy contribution?

**Comment by Martins-O-U** [comment]
Thanks @karianna

**Comment by Martins-O-U** [comment]
Hello @karianna, I have opened a Pull Request ( https://github.com/AdoptOpenJDK/openjdk-website/pull/973 ) for the documentation update. I did it a little different from that of Kubernetes due to errors I had while testing theirs. 
Please review/test for confirmation. 
Thanks

Cc: @aahlenst

**Comment by karianna** [comment]
instructions updated at adoptium.net

**Comment by TobiX** [comment]
This one? https://github.com/adoptium/website-v2/blob/main/src/asciidoc-pages/installation/linux.adoc#deb-installation-on-debian-or-ubuntu - That still uses apt-key 😞 

I'll try to send a new pull request to that repo this evening...
