### ISSUE TITLE
Automate the creation of a website banner

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-website#967]
As briefly described in https://github.com/AdoptOpenJDK/TSC/issues/178, adding a release banner at the start of a release period is a task that needs to be done, but could be made easier/simpler.

- Create an issue template called "Add banner", which prompts for `contents of banner`
- Create a workflow file that is triggered on creation of issue, that takes content of banner and creates a PR (here is an example of a [PR](https://github.com/AdoptOpenJDK/openjdk-website/pull/702) for a previous release).
- Ideally on closing the issue, it triggers workflow to revert the PR.

**Comment by karianna** [comment]
Manual banners are required given changing state during a release
