### ISSUE TITLE
Make Archive and Latest platforms match the order of platforms array

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#97]
Currently, the platform arrays are built and displayed alphabetically.

Find a way to easily specify an order (probably using a new property in the global platforms array objects), and have the website display the platforms in this order.

**Comment by Joe-Brady** [comment]
Latest page platforms now appear in the order that they occur in the global `platforms` array (as a by-product of the JS rewrite and overall redesign).

**Comment by karianna** [comment]
Extra for experts - could / should we allow users to select the order?

**Comment by Joe-Brady** [comment]
Might not be particularly easy, at a guess...
What would be the proposed advantage for those users?

**Comment by karianna** [comment]
Yeah no real benefit actually.  So I think this can be closed?

**Comment by Joe-Brady** [comment]
I'll leave it open and change the name, as there is still related work on this to do
