### ISSUE TITLE
WebSite "Latest" Releases should not show OpenJ9 "Large Heap" any more

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-website#976]
OpenJ9 now provides "Large heap" support in the new "mixed" mode of the "Normal" image, so as such the Latest Releases web page should only show the "Normal" types now.

**Comment by sxa** [comment]
The web page is now pointing to IBM Semeru binaries so this should no longer be an issue. Closing.
