### ISSUE TITLE
checksum of lastest 8.x is wrong (OpenJDK8U-jdk_x64_linux_hotspot_2021-04-29-19-09.tar.gz)

### ISSUE THREAD

**Issue by AndreSchulz-IONOS** [AdoptOpenJDK/openjdk-website#986]
steps to reproduce
- open https://api.adoptopenjdk.net/v3/assets/version/%28%2C9.0%5D/?page_size=1&architecture=x64&image_type=jdk&jvm_impl=hotspot&os=linux&vendor=adoptopenjdk
  - cff73ce41d8879ca55b7a0b45ed5fb6c3829179633692ffaaf146259a969a8af
- download checksum_link https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2021-04-29-19-09/OpenJDK8U-jdk_x64_linux_hotspot_2021-04-29-19-09.tar.gz.sha256.txt
  - 84359ccca2e1cbf47282d964a809263fb99eada83341360e71692ae360810456
- compare values

**Comment by sxa** [comment]
Closing this - not sure what happened but the latest Temurin 8 one at the above links now seem consistent
