### ISSUE TITLE
Windows Installer text problems in OpenJDK11U-jre_x64_windows_hotspot_11.0.11_9.msi

### ISSUE THREAD

**Issue by hagman** [AdoptOpenJDK/openjdk-website#987]
* **Browser**: N/A

I post this issue here because I downloaded `OpenJDK11U-jre_x64_windows_hotspot_11.0.11_9.msi` from the website and followed the create an issue link on https://adoptopenjdk.net/releases.html . 
I suspect a better place might be the obenjdk-binaries repo, but it seems I cannot create issues there.

When running the *.msi (on Windows 2016), some issues exist with the labels and explanatory texts on the feature selection panel relating to two of the four installable features:
1) Localization (at least for German language) is missing for `Associate .jar` -- `Associate .jar files to run with AdoptOpenJDK`
2) Localization (at least for German language) is missing for `JavaSoft (Oracle) registry keys` -- and additionally the explanatory  text is buggy: It shows initially as `Overwrites the reg keys HKLM\Software\...\javapath" does not work. You need to reinstall it to recreate the registry keys` and after changing the installation type of this feaature, changes to `Overwrites the reg keys HKLM\Software\JavaSoft (Oracle). After installation of AdoptOpenJDK, Oracle Java runnig from PATH "C:\Program`

Expected behaviour: Explanatory texts are coherent, not subject to unexpected change, and preferably localized

**Comment by karianna** [comment]
@hagman Could you move this issue to https://www.github.com/adoptium/installer?

**Comment by sxa** [comment]
Closing as I've raised an issue in adoptium/installer to cover it
