### ISSUE TITLE
Nightly 'number of builds' improvement

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#99]
Currently, you can choose to view 10, 20, 50, or 100 nightly builds in the table.
You can also search these builds.

If you have selected '20' builds, and have searched for 'mac', you might expect to see 20 Mac builds. 
However, this is not the case. Instead, the 'mac' search is run **within** the 20 builds, so you might only see approx. 5 results.

Change the JS so the '20', for example, only shows the first 20 that are shown as a result of the search, and not the other way around.

**Comment by Joe-Brady** [comment]
Perhaps a better solution is to simply move the search bar beneath the datepicker, and change the placeholder text from 'Type to search' to 'Search these builds'.

This way, the user will know to expect the current behaviour.

Having the datepicker above the search bar is also more visually pleasing.

**Comment by karianna** [comment]
@Joe-Brady SGTM
